### ISSUE TITLE
NETStandard version of Bogus?

### ISSUE THREAD

**Issue by dfarrNTST** [bchavez/Bogus#103]
Is there a NETStandard version of this package available or on the roadmap?  We are moving all of our library development to .NETStandard 2.0.

**Comment by bchavez** [comment]
Hi @dfarrNTST ,

**Bogus** is already compatible (and built) with .NET Standard 2.0. Check the `README` here:
https://github.com/bchavez/Bogus#download--install

You can also verify the **Dependency** group on **NuGet**:
https://www.nuget.org/packages/Bogus/

:man: :checkered_flag: ***["Louie Louie, oh no... Me gotta go... Aye-yi-yi-yi, I said"](https://www.youtube.com/watch?v=4V1p1dM3snQ)***

**Comment by bchavez** [comment]
Hi @dfarrNTST ,

**Bogus** is already compatible (and built) with .NET Standard 2.0. Check the `README` here:
https://github.com/bchavez/Bogus#download--install

You can also verify the **Dependency** group on **NuGet**:
https://www.nuget.org/packages/Bogus/

:man: :checkered_flag: ***["Louie Louie, oh no... Me gotta go... Aye-yi-yi-yi, I said"](https://www.youtube.com/watch?v=4V1p1dM3snQ)***
