### ISSUE TITLE
Add feature for weighted values

### ISSUE THREAD

**Issue by dasiths** [bchavez/Bogus#107]
Some interface to pass a key value pair of value and percentage.
`
f => f.Random.Biased(new dictionary<string, double>() {{"some val", 0.2}. {"other value", "0.8"}}`

**Comment by bchavez** [comment]
Hi @dasiths ,

Thank you for the suggestion. I think this feature already exists though. Try:
```
f => f.Random.WeightedRandom(new[] { "some val", "other val"}, new[]{0.2f, 0.8f});
```

Let me know if that helps.

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by bchavez** [comment]
Hey @dasiths , feel free to reach out on the gitter channel if you have any other questions or if you'd like to talk about this more: https://gitter.im/bchavez/Bogus

Going to close this issue for now.

Thanks,
Brian

:violin: :palm_tree: ***["'Cause it's a bittersweet symphony, this life..."](https://www.youtube.com/watch?v=1lyu1KKwC74)***
