### ISSUE TITLE
DNX support

### ISSUE THREAD

**Issue by russcam** [bchavez/Bogus#11]
Do you have any intentions to support .NET Core [(**dotnet**)](http://oren.codes/2015/06/09/pcls-net-core-dnx-and-uwp/) DNX?

**Comment by bchavez** [comment]
Ah, I knew this would come up sooner or later. I thought about it. I think it would probably be a good idea to support it, but I haven't started any work on it yet.

I suppose I could try taking a stab at it. :+1:

**Comment by russcam** [comment]
Awesome :+1: I've just pulled the source to take a look at how much effort it might be

**Comment by bchavez** [comment]
Cool! I have another project called [**RethinkDb.Driver**](https://github.com/bchavez/RethinkDb.Driver) that is CoreCLR compatible. I would most likely take the existing infrastructure in the `RethinkDb.Driver` and use it in Bogus. The driver is setup perfectly to build `.NET 4.5` and `CoreCLR`.

The hardest part would probably be the reflection stuff in `Faker<>`.

**Comment by bchavez** [comment]
Alrighty, *I think* that should do it for CoreCLR. Give `v3.0.5-beta-2` a try on NuGet. :+1: 

:heavy_check_mark: Build CoreCLR build infrastructure done.
:heavy_check_mark: CrossPlatform reflection bridge between CoreCLR and .NET 4.5 full framework done.

Also, pending any future releases, please continue to use the **Bogus** beta releases until CoreCLR RTMs.

Feel free to close the issue if Bogus is working in CoreCLR.

Going to sleep now. :sleeping: I'll process any PRs or issues in the morning. Thanks.

**Comment by bchavez** [comment]
Hi @russcam ,

It's been a few days, since this issue has been open. I hope you were able to get Bogus working in CoreCLR.

I hope you don't mind I'm going to close the issue; if you have any problems with DNX support, feel free to reopen the issue.

Thanks,
Brian

**Comment by russcam** [comment]
Thank you so much for supporting DNX so quickly - I've pulled it in to the DNX build of [NEST](https://github.com/elastic/elasticsearch-net) and it seems to be working well :+1: 

If open any issues that come up. Thanks once again :smile:
