### ISSUE TITLE
Credit Cards can be obfuscated and only get the last four digits.

### ISSUE THREAD

**Issue by rjcarneiro** [bchavez/Bogus#114]
It would be nice generate CreditCardNumbers obfuscated, **** **** **** 4453 and also only the 4 last digits.

```
public System.String CreditCardNumber(CardType provider = null);
public System.String CreditCardNumber(bool obfuscate = false);
public System.String CreditCardNumber(CardType provider = null, bool obfuscate = false);
```

```
public System.String CreditCardNumberLastFourDigits(CardType provider = null);
```

**Comment by bchavez** [comment]
Hi @rjcarneiro ,

Thank you for posting your issue. I appreciate it. I'm always happy to see how devs are using **Bogus**.

However, I feel a little hesitant about the idea of obfuscating credit card numbers inside **Bogus**. 

My concerns are:

* Credit card obfuscation can vary widely across apps.
   * Some might use ` ` spaces; others might use `-`, while others might not use any separators.
   * Some might apps chose to reveal a combination of first 3 and last 4.
* The last group of digits of some credit cards can end with 2, 3, or 4. IE: `****-12`, `****-123`, `****-1234`.

Personally, I feel there's too much variability in the way credit card numbers are masked in apps to really hard-code this formatting into **Bogus**. My gut instinct here is to forward any obfuscation requrement to `ReplaceNumber`:

```
f.Random.ReplaceNumbers("****-****-****-####")
// "****-****-****-9841"
```

Using `ReplaceNumbers` avoids a lot of the concerns I outlined above.

Lastly, if anyone else would like to chime in about adding this to **Bogus** feel free to comment. I'd like to know what others think too.

:hourglass_flowing_sand: :mag: ***["But I still haven't found what I'm for..."](https://www.youtube.com/watch?v=wdCJRybAtso)***

**Comment by rjcarneiro** [comment]
Hi @bchavez ,

Thanks for your reply. 

I believe this new features can improve your package setting the framework more capable. Your concerns are valid and it's possible to create more overloads to solve that.

**Comment by bchavez** [comment]
Hi @rjcarneiro ,

I apologize for taking so long to get your code merged. I promoted your credit card obfuscation methods to **Extension Methods** and moved them from the core `Finance` dataset class to the `Bogus.Extensions.Extras` namespace.

I hope you feel this is okay. I think this is a good compromise for both of us. As I mentioned earlier about my concerns I'm okay letting them live in an extension namespace; just maybe not so much in the core API of `Finance` dataset class.

I'll have a new release for you soon.

Cheers,
Brian

:car: :police_car: :rotating_light: ***["Drive it like you stole it..."](https://www.youtube.com/watch?v=dd00Qh9yZUg)***
