### ISSUE TITLE
Please consider adding a Title property to person

### ISSUE THREAD

**Issue by grahamehorner** [bchavez/Bogus#116]
Please consider adding a Title property to Person, that holds a value based on the gender of Mr, Mrs, Miss, Ms, Dr, Prof etc.

**Comment by bchavez** [comment]
Hi @grahamehorner ,

Unfortunately, titles are currently not organized by gender. So, there's no way for me inside **Bogus** to discern which titles belong to specific genders.

Here are a few examples:

For the `en` locale:
https://github.com/bchavez/Bogus/blob/bee5ab42ded188cf569e03ab95c8981325159f62/Source/Bogus/data/en.locale.json#L8564-L8570

For the `sk` locale:
https://github.com/bchavez/Bogus/blob/bee5ab42ded188cf569e03ab95c8981325159f62/Source/Bogus/data/sk.locale.json#L3507-L3512

To make this truly work across locales, we need titles to be separated by gender.

The best way to get this feature implemented is to re-organize titles upstream in **faker.js** https://github.com/marak/Faker.js/ . Once **faker.js** makes those changes, we can update our locales here.

Feel free to re-open this issue if/when those changes happen upstream and I'll be happy to get this implemented for you (or you can send in a PR). :+1: 

Thanks,
Brian

**Comment by grahamehorner** [comment]
@bchavez please look into this as faker now has the required datasets

**Comment by bchavez** [comment]
@grahamehorner are prefixes separated into genders? If so, please provide a link to the datasets your seeing that contains the separated gender prefixes.

**Comment by grahamehorner** [comment]
@bchavez https://github.com/Marak/faker.js/tree/3d3e3732d959e6c2e541bff6efab0b37881498c5/lib/locales/pt_PT/name

**Comment by bchavez** [comment]
@grahamehorner The default locale `en` does not support gendered prefixes: https://github.com/Marak/faker.js/tree/3d3e3732d959e6c2e541bff6efab0b37881498c5/lib/locales/en/name

However, the Bogus public API is already available for those locales that already have gendered prefixed data. See below:

https://github.com/bchavez/Bogus/blob/71b26eac70d46745807a8f58660813c500dc254b/Source/Bogus/DataSets/Name.cs#L95
