### ISSUE TITLE
Thread Safety in Unit Tests

### ISSUE THREAD

**Issue by bchavez** [bchavez/Bogus#12]
User report from @PureKrome via twitter:

Bogus' Faker `RuleFor` actions isn't thread safe. Some test runners use multiple threads to run tests. So, some code like:

```
var userIds = 0;
var testUsers = new Faker<User>()
    .CustomInstantiator(f => new User(userIds++, f.Random.Replace("###-##-####")))
```

The above code, could produce multiple `User`s with the same ID. I think we could do a better job here since we're expected to run in test runners.

Two main areas we need to be careful are:
1. Careful accessing new randomness from `Randomizer.Seed` since `Random` isn't inherently thread-safe. This should protect against strange issues when using a `DataSet` by multiple threads. `DataSet` could possibly produce the same value multiple times when accessed by two or more threads.
2. `Faker<T>.Populate` needs a lock to prevent multiple `RuleFor`s from executing at the same time. Lambda closure outside-scope of `Faker` can be affected by multiple threads.

Possibly using a global lock, an internal lazy-static (`Randomizer.Locker`), to lock around `Seed` and `Faker<T>.Populate` should serialize threads and prevent from clobbering each other.

**Comment by bchavez** [comment]
@PureKrome, pushed **v3.0.5-beta-3** with thread-safety. Please give it a try. Let me know if you're issue has been resolved. Thanks!

**Comment by PureKrome** [comment]
Thanks :+1: - i'll give it a go, soon :smile:
