### ISSUE TITLE
Generate for IReadOnlyCollection<T> and IReadOnlyList<T>

### ISSUE THREAD

**Issue by qtty1234** [bchavez/Bogus#120]
I would suggest to add overload for method Generate that will return List<T> instead of IList<T>.

There is case:

```
public interface IWeightCalculator
{
  decimal Calculate(IReadOnly<Parcel> parcels);
  decimal Calculate(IReadOnlyCollection<Parcel> ourParcels, IReadOnlyCollection<Parcel> theirParcels);
}

public class WeightCalculator : IWeightCalculator
{
  public decimal Calculate(
    IReadOnlyCollection<Parcel> ourParcels, 
    IReadOnlyCollection<Parcel> theirParcels) 
  {
    // just for example
    return 0;
  }
}
```
So, In case I'm going to create items I have to use .ToList() extension. 
So this approach it seems a little bit redundant.

```
var faker = new Faker<Parcel>().RuleFor(x => x.Weight, x => x.Random.Decimal());

// act
var calculator = new WeightCalculator();
var result = calculator .Calculate(faker.Generate(10).ToList(), faker.Generate(5).ToList());

// assert
// checking
```

I hope this sample make sense.

Best regards,
Ivan.

**Comment by bchavez** [comment]
Hi Ivan,

You're absolutely correct. The `IList<T>` return type sucks and is annoying for common cases like this.

Originally, `IList<T>` was part of changes in #92, #91 (ref: v16.0.2: https://github.com/bchavez/Bogus/commit/1d7c1afb80d46d8da31835023d12033074a80f41), I was trying to be "API Correct" by following the old adage of only returning interfaces. Unfortunately, that choice made common scenarios like this more cumbersome.

I'll have another release out later today (v22.0.1) after I make a decision on #118.

Thanks,
Brian

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***
