### ISSUE TITLE
Movies and Tv Series Support

### ISSUE THREAD

**Issue by JaWiD2** [bchavez/Bogus#123]
Hi,
please add Multimedia data such as movie. for providing data you can look at [http://www.omdbapi.com/](http://www.omdbapi.com/) site. I think it's better to being internal but could be online.
thank you for this wonderful package.

**Comment by bchavez** [comment]
Hi @JaWiD2 ,

**Bogus** now has a [**`Bogus.Hollywood`**](https://www.nuget.org/packages/Bogus.Hollywood/) **NuGet** data set extension that lets you generate data like movies and TV shows.

However, the [**`Bogus.Hollywood`**](https://www.nuget.org/packages/Bogus.Hollywood/) **NuGet** data set is an exclusive dataset for people with a [**Bogus Premium**](https://github.com/bchavez/Bogus#bogus-premium-extensions) license which helps support the open source project.

Thanks,
Brian

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***
