### ISSUE TITLE
Randomly Null

### ISSUE THREAD

**Issue by Mardoxx** [bchavez/Bogus#124]
Would producing randomly nullable objects for reference and `Nullable<T>` types be useful? At the moment I've just been filling my nullables with values.

Not sure what sort of API would be appropriate? I think difficulty lies with `Nullable<T>` being a struct 😢 Anyone got any clever ideas?

For `Nullable<T>` perhaps just a method on `Randomizer` would be okay?

```csharp
namespace Bogus
{
    public static class RandomizerExtensions
    {
        public static T? Nullable<T>(this Randomizer randomizer, T? value)
            where T : struct
        {
            return randomizer.Bool() ? value : null;
        }

        public static T? Nullable<T>(this Randomizer randomizer, T value)
            where T : struct
        {
            return randomizer.Nullable(new T?(value));
        }
    }
}
```

But that leads to a more messy setup, e.g.
`faker.RuleFor(x => x.Guid, x => x.Random.Nullable(x.Random.Uuid()))`

How about a `NullableRandomizer`  class which does the same as `Randomizer` but randomly returns null? Then you could do something like `x.Random.Nullable.Bool()`

Maybe a method such as `x.Random.Nullable.Value<T>(T value) where T : class` for reference types, and `x.Random.Nullable.Value<T>() where T : struct` for enums?

Just some ideas! 😄

**Comment by bchavez** [comment]
Hi @Mardoxx ,

Good and challenging scenario here. One other idea is to *nullify* the result with an `.OrNull()` extension method like this:

```csharp
public static class ObjectExtensions
{
   public static T? OrNull<T>(this T? value)
      where T : struct
   {
      return value.GetHashCode() % 2 == 0 ? value : null;
   }

   public static T? OrNull<T>(this T value)
      where T : struct
   {
      return value.GetHashCode() % 2 == 0 ? (T?)value : null;
   }
}
```
Then your rule code starts looking like:
```csharp
[Fact]
public void test_nullable()
{
   var faker = new Faker<Person>()
      .RuleFor(p => p.Guid, f => f.Random.Uuid().OrNull())
      .RuleFor(p => p.Name, f => f.Person.FullName);

   console.Dump(faker.Generate(20));
}
```
Setups like `.RuleFor(p => p.Guid, f => f.Random.Uuid().OrNull())` look pretty clean to me. What do you think?

If I recall correctly I think `Guid`'s `.GetHashCode()` implementation is deterministic. That is to say, `Guid.Empty` is always 0 and
```
new Guid("82b32a64-78aa-415d-b50f-6647bf31c82e").GetHashCode() ==
new Guid("82b32a64-78aa-415d-b50f-6647bf31c82e").GetHashCode()
```

So, that's pretty cool. You get determinism in `Guid.GetHashCode()` for free without the need for sourcing deterministic randomness from a `Randomizer`.

The only "potential" problem with this approach is probably the non-determinism of `null` relying on `GetHashCode()` for some reference type `T`.  

Alternatively, you could new up a `new Randomizer()` in a static field in `ObjectExtensions` and use that but you'd be relying on the global static seed.

---

Also, if nullable `Guid?` is 90% of cases, I'd never shy away from keeping it simple:

```csharp
public static class ObjectExtensions
{
   public static Guid? UuidNullable(this Randomizer r)
   {
      return r.Bool() ? r.Uuid() : (Guid?)null;
   }
}
```
```csharp
var faker = new Faker<Person>()
   .RuleFor(p => p.Guid, f => f.Random.UuidNullable())
   .RuleFor(p => p.Name, f => f.Person.FullName);
```

Hope that helps! 

Thanks,
Brian

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***

**Comment by Mardoxx** [comment]
That is brilliant thanks so much!

**Comment by Mardoxx** [comment]
Hmm how would you go about creating a method that also works for reference types?

Not sure this is possible without a different interface for reference types is it?

**Comment by bchavez** [comment]
Hi @Mardoxx ,

Maybe try this `OrNull(this object value)` extension method instead:

https://github.com/bchavez/Bogus/blob/04b089b6e1d2277022d70778ec78e5e864a40b77/Source/Bogus.Tests/GitHubIssues/Issue124.cs#L110-L115

It seems to still pass all the unit tests in [`Issue124.cs`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/GitHubIssues/Issue124.cs):

https://github.com/bchavez/Bogus/blob/04b089b6e1d2277022d70778ec78e5e864a40b77/Source/Bogus.Tests/GitHubIssues/Issue124.cs#L34-L89

Feel free to close the issue if it works out.

Thanks, :sunglasses: 
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by bchavez** [comment]
Hey @Mardoxx ,

Was mentally chewing on the issue a little more and came up with the best of both worlds. Deterministic nullability in `.OrNull` by adding `Faker f` as a parameter without `GetHashCode()`.

https://github.com/bchavez/Bogus/blob/2fa9b21e62ce75e2b77511de783ce47e2d5d128a/Source/Bogus.Tests/GitHubIssues/Issue124.cs#L139-L147

https://github.com/bchavez/Bogus/blob/2fa9b21e62ce75e2b77511de783ce47e2d5d128a/Source/Bogus.Tests/GitHubIssues/Issue124.cs#L91-L118

```
.RuleFor(x => x.Bar, f => new object().OrNull(f)); 
```
Still pretty sweet and elegant imho. And the best part you is get deterministic nullable references. :sunglasses: 

-Brian

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***

**Comment by VictorioBerra** [comment]
In case anyone else stumbled upon this this was my idea and it does not require outside code.

`o.RetiredOn = f.PickRandom(new DateTime?[] { f.Date.Past(), null }); // Randomly choose a random date in the past, or null`

**Comment by Mardoxx** [comment]
@VictorioBerra so simple! Why didn't I think of that 😂

**Comment by simonvane** [comment]
Bogus now provides its own implementation of `OrNull` in the `Bogus.Extensions` namespace as follows:

```
public static object OrNull(this object value, Faker f, float nullWeight = 0.5f)
{
 if (nullWeight > 1 || nullWeight < 0) throw new ArgumentOutOfRangeException(nameof(nullWeight), $".{nameof(OrNull)}() {nameof(nullWeight)} of '{nullWeight}' must be between 1.0f and 0.0f.");
 return f.Random.Float() > nullWeight ? value : null;
}
```

**Comment by VictorioBerra** [comment]
@simonvane thanks for sharing this. One thing I would caution is that might need casting.

**Comment by simonvane** [comment]
@VictorioBerra Yeah, it would have been nice if it had been generic.

**Comment by bchavez** [comment]
@VictorioBerra @simonvane, try using **Bogus** `v29.0.1`. I made some small changes to the method signature that makes all calls type-safe using a compiler `in` parameter trick. Also, hopefully, resolves the ambiguity between value types `int?`, `struct`, and reference types `class`; where all three kinds of invocations to `.OrNull(f)` should be type-safe.

IE: the following unit test passes:

```csharp
public class Qux
{
   public int? Id { get; set; }
   public Guid? Gud { get; set; }
   public object Obj { get; set; }
   public string Str { get; set; }
}

[Fact]
public void nullable_int_and_nullable_reference_type()
{
   var faker = new Faker<Qux>()
      .RuleFor(x => x.Id, f => f.Random.Int().OrNull(f))
      .RuleFor(x => x.Gud, f => f.Random.Guid().OrNull(f, .8f))
      .RuleFor(x => x.Obj, f => new object().OrNull(f))
      .RuleFor(x => x.Str, f => f.Random.Word().OrNull(f));

   var q = faker.Generate(3);

   console.Dump(q);

   q[0].Id.Should().NotBeNull();
   q[0].Gud.Should().NotBeNull();
   q[0].Obj.Should().NotBeNull();
   q[0].Str.Should().NotBeNull();

   q[1].Id.Should().NotBeNull();
   q[1].Gud.Should().NotBeNull();
   q[1].Obj.Should().NotBeNull();
   q[1].Str.Should().BeNull();

   q[2].Id.Should().BeNull();
   q[2].Gud.Should().BeNull();
   q[2].Obj.Should().NotBeNull();
   q[2].Str.Should().NotBeNull();
}
```

**Comment by simonvane** [comment]
Thanks a lot @bchavez and thanks for Bogus in general. I use it a lot, It's a joy to use!

In my use case I am using `OrNull` conditionally in a `CustomInstantiator` to assign back to a `string` variable as follows:

```
var faker = new Faker<CustomType>().CustomInstantiator(faker =>
{
    var isPublished = faker.Random.Bool();
    var displayName = faker.Commerce.Department();
    var description = $"Description for {displayName}";

    // Some fields are mandatory ONLY when published.
    // When not published, make some of them null.
    if (isPublished == false)
    {
        displayName = (string)displayName.OrNull(faker);
        description = (string)description.OrNull(faker);
    }

    return new CustomType
    {
        Id = Guid.NewGuid(),
        DisplayName = displayName,
        Description = description,
        IsPublished = isPublished
    };
});
```

In this case I have to cast back from `object` to `string`.

To avoid this for reference types what I'd really like is something like the following to avoid casting (i.e. generic rather than on object):
`public static T OrNull(this T value, Faker f, float nullWeight = 0.5f) where T : class`

Does that make sense or is there a better way to use Bogus?

Thanks.

**Comment by bchavez** [comment]
Hi Simon,

No problem! I'm super glad you enjoy using **Bogus**! It gives me great happiness to hear **Bogus** is helping people be more successful in developing software.

-----

Just for general context (and for my reference), I had to rely on `object OrNull(...)` because the C# compiler doesn't allow overloading resolution by generic constraints. IE: the following won't compile:

```csharp
static T OrNull<T>(this T value, Faker f, float nullWeight = 0.5f) where T : class
{
}

static T? OrNull<T>(this T value, Faker f, float nullWeight = 0.5f) where T : struct
{
}
```
>**CS0111** Type 'ExtensionsForFakerT' already defines a member called 'OrNull' with the same parameter types

So, this is why I had to rely on `object` without a `<T>` generic parameter; so the compiler could be happy.
```csharp
static object OrNull(this object value, Faker f, float nullWeight = 0.5f)
{
}
```
However, after taking a 2nd look at the issue, I noticed we could use `in` as a parameter modifier that would cause the compiler to choose the correct overload. And it seemed to work! 

```csharp
static T OrNull<T>(this T value, in Faker f, float nullWeight = 0.5f) where T : class
{
}

static T? OrNull<T>(this T value, Faker f, float nullWeight = 0.5f) where T : struct
{
}
```
And there's no impact, as far as I could tell, from the user's perspective. :+1:

**Comment by simonvane** [comment]
Thanks for the background, very interesting.
