### ISSUE TITLE
Strict mode problem with read only property

### ISSUE THREAD

**Issue by andrejohansson** [bchavez/Bogus#13]
Hello,
Lovely lib!

I can't seem to use strict mode on an object which have read only properties. Bogus thinks that this object is not initialized.

Could this be a bug?

**Comment by bchavez** [comment]
Hi @andrejohansson thanks very much!

It could possibly be a bug, could you post an example of your model and faker setup?

It would help a lot and I'll take a look asap.

**Comment by bchavez** [comment]
@andrejohansson I have a possible fix for read-only properties. Please give **v3.0.5-beta-4** a try on NuGet. Bogus now ignores read-only properties.

Let me know if it fixes your issue. Thanks.
-Brian

**Comment by andrejohansson** [comment]
Hello again, sorry for the late reply. I updated on nuget to 3.0.5.0 but the problem remains.

The error is:
```
Cannot generate BokaMera.API.ServiceModel.Models.BookedEvent because strict mode is enabled on this type and some properties/fields have no rules.
```

I have rules for 17 of 19 properties and two properties are read Only. I have posted the model and rules in this gist: https://gist.github.com/andrejohansson/39926be13017cb607370

**Comment by bchavez** [comment]
Hi @andrejohansson ,

Thanks very much for your model and faker setup. I was able to reproduce the issue.

Bogus **v3.0.6** and **v3.0.6-beta-1** should have the fix published on NuGet.

Additionally, I added a new method that can be used in conjunction with `StrictMode`. You can use `.Ignore(c => c.SomePropertyOrField)` and the field will be removed from `StrictMode` checking.

Please give them a try and let me know if it works for you. Hope that helps.

Brian

**Comment by andrejohansson** [comment]
Works like a charm, thank you!

**Comment by Gakk** [comment]
This workaround also helped me on obsolete field that are marked to give compilation error on use, e.g.:

```csharp
[Obsolete("Use property 'xxx' instead", true)]
public string SomeOldProperty { get; set; }
```

When using `StrictMode(true)` there is no way to reference the property as an expression without the compiler throwing an error, so I had to do it by it's name:

```csharp
.Ignore("SomeOldProperty") // Obsolete property
```

Hopefully this comment might help someone in the future.

I have also created a new feature request to silently ignore obsolete fields that is marked to generate compile time errors: https://github.com/bchavez/Bogus/issues/450
