### ISSUE TITLE
Relations between rules

### ISSUE THREAD

**Issue by Flyingdot** [bchavez/Bogus#130]
Is there a way to set relations between various rules?

Eg. below, both Address.ZipCode() should return the same value.
```
new Faker<My>
  .RuleFor(x => x.Zip, f => f.Address.ZipCode()
  .RuleFor(x => x.Location, f=> $"{f.Address.ZipCode()} {f.Address.City()}");
```

**Comment by bchavez** [comment]
Hi Daniel,

It's a bit elusive and subtle, but as shown in the [**README**](https://github.com/bchavez/Bogus) on the homepage example shows:

```
void Main()
{
   var faker = new Faker<My>()
       .RuleFor(x => x.Zip, f => f.Address.ZipCode())
       .RuleFor(x => x.Location, (f, m) => $"{m.Zip} {f.Address.City()}" );
   
   faker.Generate().Dump();
}

public class My{
   public string Zip{get;set;}
   public string Location{get;set;}
}
```

![linqpad_1205](https://user-images.githubusercontent.com/478118/36688068-31af6a8e-1ae0-11e8-933e-cf1c182271d9.png)

If you have more questions on usage, please feel free to ask in the Gitter channel: https://gitter.im/bchavez/Bogus

Thanks,
Brian

:art: :dash: **[Marshmello - CoLoUR](https://www.youtube.com/watch?v=6UhNJC8OyVA)**
