### ISSUE TITLE
UtcNow support for Date generation

### ISSUE THREAD

**Issue by cjlotz** [bchavez/Bogus#139]
Currently dates are generated relative to `DateTime.Now`.  Is it possible to extend this to use `DateTime.UtcNow`.

**Comment by bchavez** [comment]
Hi Carel,

Thanks for your suggestion. For now, the only way I would recommend is to create one or more extension(s) methods to fit your use case that converts `DateTime` `.ToUniversalTime()`.

Some nice options are:
```csharp
void Main()
{
   var date  = new Date();
   
   //no extension
   date.Past().ToUniversalTime();
   
   //shortcut
   date.Past().ToUtc();
   
   //extension
   date.PastUtc();
}

public static class ExtensionsForDate{
   public static DateTime ToUtc(this DateTime dt){
      return dt.ToUniversalTime();
   }
   public static DateTime PastUtc(this Date d, int yearsToGoBack = 1, DateTime? refDate = null){
      return d.Past(yearsToGoBack, refDate).ToUniversalTime();
   }
}
```

Long term, maybe we could have a property on the `Date` data set that accepts `DateTimeKind`, but I'd have to think about it a bit more and I'd like to get some feedback from others on the idea.

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by SimonCropp** [comment]
ok here is my proposal https://github.com/bchavez/Bogus/pull/165/files  :)
