### ISSUE TITLE
Question about failing unit tests

### ISSUE THREAD

**Issue by JvanderStad** [bchavez/Bogus#14]
Hi there,

in the locale files there is support for alternative combining of address strings. For example in the locale nl (Dutch) the cities can be combined using the following rules:

https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/nl.locale.json#L44
```
"city": [
        "#{Name.first_name}#{city_suffix}",
        "#{Name.last_name}#{city_suffix}",
        "#{city_prefix} #{Name.first_name}#{city_suffix}",
        "#{city_prefix} #{Name.last_name}#{city_suffix}"
      ]
```

Those rules are now hardcoded in https://github.com/bchavez/Bogus/blob/master/Source/Bogus/DataSets/Address.cs#L40

I have commited support for thore rules in the following commit: 

https://github.com/JvanderStad/Bogus/commit/bfb57a0a7ff1395f85ef266c536f230e5d048688

However, some unittests are failing:

![image](https://cloud.githubusercontent.com/assets/5426370/13325145/e356dc4a-dbe0-11e5-9cf3-d2496d11425b.png)
![image](https://cloud.githubusercontent.com/assets/5426370/13325227/4193c304-dbe1-11e5-8a79-d0f29121cf1a.png)

eg:
```
Expected string to be 
"1860 Bechtelar Rest" with a length of 19, but 
"60643 Oberbrunner Bypass" has a length of 24.

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\eed5b735bfe0fb8d\Shared\Execution\LateBoundTestFramework.cs:line 30
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Primitives\StringEqualityValidator.cs:line 40
   at FluentAssertions.Primitives.StringValidator.Validate() in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Primitives\StringValidator.cs:line 42
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] reasonArgs) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Primitives\StringAssertions.cs:line 40
   at Bogus.Tests.AddressTest.can_get_a_street_address() in c:\Workspace\Ontwikkeling\GitHub\Bogus\Source\Bogus.Tests\AddressTest.cs:line 40

```
As far as I understand this is how the unit tests in this project work:

The seed is predetermined and every ```Seed.Next()``` will return predictable results ( :grey_question: )

Because I have changed the the lookup of string values, the amount of calls to ```Seed.Next()``` has changed, as a result the unit tests are failing.

That's my assumption or am I missing something?

**Comment by bchavez** [comment]
Hi @JvanderStad , right-o and on point, I think your assumption is correct. `Seed` is only predictable on the random values pulled from `Seed.Next`. So, if the number of calls to `Next` changes it can disrupt the order in which unit tests expect output.

**Comment by JvanderStad** [comment]
thanks :+1: 

I'll fix the tests, pr coming soon..

**Comment by bchavez** [comment]
You bring up a good point tough... If you checkout `Person.cs`, a person is being `Initialized` (and values pulled including address) when a `Faker` is constructed. The more correct way is to probably lazily delay person initialization this until a person is actually needed. I think this is what's goofing up the unit tests for you :(

**Comment by JvanderStad** [comment]
I've created 2 new methods: ```GetRandomValue()``` and ```ParseTokens``` the ParseTokens is  recursive. So the amount of calls to ```Seed.Next``` is changed by my commit. 

Also, I made another branch with lazy loading the Person.. https://github.com/JvanderStad/Bogus/commit/6695892731a0d346e7e3513ed8ea3067dc5cca2a

**Comment by JvanderStad** [comment]
pr https://github.com/bchavez/Bogus/pull/15

**Comment by bchavez** [comment]
**SUPER** cool! Thanks so much. I'll get a release out today for you.

**Comment by bchavez** [comment]
@JvanderStad You changes are live in **v5.0.1** and **v5.0.1-beta-2**. Thanks again for your contribution! Should appear soon when nuget index catches up.

https://www.nuget.org/packages/Bogus/

Brian
