### ISSUE TITLE
Fill a string only if a boolean property is set to true

### ISSUE THREAD

**Issue by advapiIT** [bchavez/Bogus#140]
Hello,
I'm using Bogus to mockup some data I've got on DB in order to generate word files.
I was wondering if it's possible to fill some string only when a value is set to true.

Consider this snippet

```
.RuleFor(x => x.DocGroundingCheck, f => f.PickRandom<int>(0, 1))
.RuleFor(x => x.DocGroundingCheckDesc, f => "DocGroundingCheckDesc")
```

I wish to have the ```DocGroundingCheckDesc``` only filled when ```DocGroundingCheck``` is set to 1

Thanks

**Comment by bchavez** [comment]
Hi @advapiIT ,

Try:
```
.RuleFor(x => x.DocGroundingCheck, f => f.PickRandom<int>(0, 1))
.RuleFor(x => x.DocGroundingCheckDesc, (f,x) => x.DocGroundingCheck == 1?
                                                 "DocGroundingCheckDesc" : null)
```
If you have more questions, I'll try to answer them in the morning. Have to get some sleep. :sunglasses: 

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***
