### ISSUE TITLE
Pass parameter to Constructor

### ISSUE THREAD

**Issue by mqueirozcorreia** [bchavez/Bogus#142]
Is it possible to fake a class with no default constructor? I just need to set the constructor parameter like:
`new Faker<MyClass>(constructorParameter1)`

**Comment by bchavez** [comment]
Hello @mqueirozcorreia ,

Thank you for your question. Yea, it should be possible. Here's how:

```
var myclassFaker = new Faker<MyClass>
    .CustomInstantiator(f => new MyClass(constructorParameter1))
    .RuleFor(...)
```

If you have any other questions, comments or feedback, feel free to post here or use our Gitter.IM chat: https://gitter.im/bchavez/Bogus

Also, you can read more about the capabilites of **Bogus** in the **Great Example** on the README page here: https://github.com/bchavez/Bogus#the-great-c-example

Have a good day, and thanks again for your question.
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***
