### ISSUE TITLE
DataSets.Currency Always return null

### ISSUE THREAD

**Issue by Jzeemo** [bchavez/Bogus#146]
Currently, I am using Bogus Version 22.1.1.0. When I use currency format, like that=> 

```
Bogus.DataSets.Currency cur = new Bogus.DataSets.Currency();
            var TempCode= cur.Code;
            var TempDes= cur.Description;
            var TempSymbol = cur.Symbol;
```
All of value are return null.Is this Bug?

**Comment by bchavez** [comment]
Hi @Jzeemo,

Thank you for the code example.

The `Currency` class is mostly just a model used by the `Finance` class.

https://github.com/bchavez/Bogus/blob/28807caa96a86e17a17e0d3e57de9c40da1f25fc/Source/Bogus/DataSets/Finance.cs#L11-L32

The way to get a random currency is to actually new up a `Finance` data set. Here's how:

```csharp
var finance = new Bogus.DataSets.Finance();

var currency = finance.Currency();

currency.Dump()
```
![linqpad_1677](https://user-images.githubusercontent.com/478118/40696409-985b5ba2-637a-11e8-9c6d-73385693b890.png)

Hope that helps. Sorry for the confusion. I should move utility/helper classes like `Currency` out of the `DataSets` namespace to something like `DataSets.Models` at some point to avoid the confusion.

Thanks,
Brian

:fallen_leaf: :leaves: **[Distance - Falling (ft Alys Be)](https://www.youtube.com/watch?v=WIfwIv4wNCE)**
