### ISSUE TITLE
Add premium offerings/nugets to the main readme

### ISSUE THREAD

**Issue by SimonCropp** [bchavez/Bogus#150]
IMO they are a little too difficult to discover ATM

**Comment by bchavez** [comment]
Hey Simon, Thanks!

Sorry it took so long but **Bogus Premium** is officially out, supported, and detailed in the main README: 

https://github.com/bchavez/Bogus#bogus-premium-extensions

I had to finish up revamping my small business website and lower the price for the **Bogus Premium** license before making  an official announcement. :+1: 

Official announcement on the Twitters tomorrow morning! :balloon: 

Thanks again Simon for being part of the community and your awesome extensions! :sunglasses: 

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
