### ISSUE TITLE
first and last name

### ISSUE THREAD

**Issue by SimonCropp** [bchavez/Bogus#154]
This is a very minor suggestion and feel free to close as "not worth the effort"

Note that in many cultures "first and last name" are ambiguous. See map below.

I general find that a less ambiguous. although not perfect, approach is the combination of "given names" and "family names". "family names" is what you have inherited from your family/region/clan etc, "given names" is the names u have been given to you by your parents that distinguish you within your family/region/clan etc

![image](https://user-images.githubusercontent.com/122666/42089612-5bfbf322-7be1-11e8-8ba3-c432e87749c8.png)

**Comment by bchavez** [comment]
Hi Simon,

Thanks for your suggestion.  That's pretty interesting. I'm not an expert on this particular subject especially in this region of the world. So, I'm not sure how much I can contribute besides providing guidance on how something like this could get merged in Bogus. The `Name` dataset has changed quite a bit over the years with better refinements over time (re: #148). I suspect the trend will continue.

More fundamentally, however, this feels kinda like a deeper change that [**faker.js**](https://github.com/marak/Faker.js/) should take on (and one that we would follow).

Ultimately, the implementation details matter. You're right it might not be "worth the effort" in the sense if the implementation complexity is far greater than a demand/benefit we get from the community. Ideally, I'd like to stick to using faker.js data files as much as possible without significant modification.  We do have the facility in place if this is really an important issue for the Bogus community. There is a special folder in Bogus called ([`data_extend`](https://github.com/bchavez/Bogus/tree/master/Source/Bogus/data_extend)) that extends faker.js data files by patching `data_extend` on top of faker.js. `data_extend` basically gives us a way to patch/extend raw locale files without modifying the original faker.js source. If this is something really important to the community the `data_extend` would probably be the starting point.

I'll leave the issue open for a few months, and we'll see if we get any traction on the topic.

Thanks,
Brian

:zap: :runner: ***["I was struck by lighting. Walkin' down the street..."](https://www.youtube.com/watch?v=iypUpv9xelg)***

**Comment by SimonCropp** [comment]
Hey @Marak, thoughts on the above?

**Comment by SimonCropp** [comment]
given the lack of response i will close this
