### ISSUE TITLE
Add DatetimeOffset generation

### ISSUE THREAD

**Issue by SimonCropp** [bchavez/Bogus#158]

**Comment by SimonCropp** [comment]
Happy to PR this. But what do u want the method called. We currently have .Date(). So a parallel would be .DateOffset(). But from my perspective i think .Date() is misleading. I would preder to obsolete with warn on .Date(). Then add two new methos .DateTime() and .DateTimeOffset(). 

Thoughts?

**Comment by bchavez** [comment]
Hi Simon,

Yea, this has come up in the past (re: #24).  We should start figuring this one out.

Where is the `.Date()` method you reference? Are you referencing facade `Date` property on `Faker`? `f.Date.Method()` part?

IIRC, we have methods like `.Past()`, `.Soon()`, `.Future()`, `.Between()`, and `.Recent()` in `Date` dataset: 
https://github.com/bchavez/Bogus/blob/master/Source/Bogus/DataSets/Date.cs

Methods could be?
```
f.Date.Past()
f.Date.PastOffset()
f.Date.Soon()
f.Date.SoonOffset()
f.Date.Future()
f.Date.FutureOffset()
...
```
Or are we looking to obsolete `f.Date` in favor of `f.DateTime.Soon()` and `f.DateTimeOffset.Soon()`?

Kinda feels like the `Offset()` prefix might work without obsoleting `f.Date`. I agree with you, looking back `f.Date` was probably not the best choice.

Let me know your thoughts.

Thanks,
Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by SimonCropp** [comment]
> Or are we looking to obsolete f.Date in favor of f.DateTime.Soon() and f.DateTimeOffset.Soon()?

yes that is what i was proposing

another thing to consider here is the timezones and UTC concepts

**Comment by bchavez** [comment]
My initial impulse is to keep the *date* and *time* code in one place. Mostly for maintenance reasons and issues like #139.

`f.Date` dataset has methods like `string .Month()` and `string .Weekday()` and `TimeSpan .Timespan()` that aren't necessarily related to the `DateTime` and `DateTimeOffset` types.
It seems we'd have duplicate code split across `f.DateTime.Weekday()` and `f.DateTimeOffset.Weekday()` if we went down the path of obsoleting `f.Date` and broke it off into two based on type.

My feeling is the `f.Date.*Offset()` suffix for indicating `DateTimeOffset` return types might still be a decent choice.

For what it's worth, if we ever break `f.Date`, I'd probably consider `f.Time` an improvement over `f.Date` tho.

Let me know your thoughts.

:thought_balloon: :mag: ***["I want to know... what you're thinking..."](https://www.youtube.com/watch?v=ijAYN9zVnwg)***

**Comment by SimonCropp** [comment]
I can run with f.date.*offset.  Want a pr for that?
