### ISSUE TITLE
Generate Random Address Class

### ISSUE THREAD

**Issue by aherrick** [bchavez/Bogus#167]
I'm trying to generate a single random Address that has all associated properties available (City, State, Postal)

I don't want to use "FullAddress" as I need each property to stand on its own, yet it to a valid and complete address.

```
				var faker = new Faker();
				var address = faker.Address;
```

How is this possible?

**Comment by bchavez** [comment]
Hi Andrew,

Thanks for posting your question. I really appreciate it.

Echoing Curtis' (@digitalcoyote) suggestion, you'll want to access city/state/postal by calling the methods on `f.Address`, for example:

```csharp
var f = new Faker();

var city = f.Address.City();
var state = f.Address.State();
var postal = f.Address.ZipCode();
```
```
South Mossie
Ohio
75371-5712
```
If you really want to make an "object" with properties that is returned, create an extension method over `Faker` like this:
```csharp
void Main()
{
   var f = new Faker();
   
   var myAddress = f.Address.MyAddressModel();
   myAddress.Dump();
}

public class MyAddressModel{
   public string City{get;set;}
   public string State{get;set;}
   public string Postal{get;set;}
}

public static class MyFakerExtensions{
   public static MyAddressModel MyAddressModel(this Bogus.DataSets.Address a){
      return new MyAddressModel{
         City = a.City(),
         State = a.State(),
         Postal = a.ZipCode()
      };
   }
}
```
![linqpad_1920](https://user-images.githubusercontent.com/478118/43087206-22ff26b8-8e54-11e8-8374-21a6bd1fd4b6.png)

Also, just to clarify, Faker.js and Bogus don't create real "valid" addresses that be found on Google Maps or anything. The addresses are fake.

The closest thing to "real"/"valid" Geocode-able addresses are in Bogus Premium's Healthcare dataset: `HospitalCity()`, `HospitalState()`, `HospitalZipCode()` which are real addresses that can be found on Google Maps.

Feel free to reach out and continue the discussion if you have any more questions.

Hope that helps. 

Thanks,
Brian
