### ISSUE TITLE
CardAddress does not contain State

### ISSUE THREAD

**Issue by rlightner** [bchavez/Bogus#168]
But has all other properties of an address

**Comment by rlightner** [comment]
Thanks!

**Comment by bchavez** [comment]
Hi Raine,

No problem, thank you for creating an issue pointing out the oversight.

A new version of **Bogus** **`v23.0.1`** is ready with the changes/fixes:
https://www.nuget.org/packages/Bogus/23.0.1

Should be available for download soon as NuGet refreshes its search index.

Thanks,
Brian

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
