### ISSUE TITLE
Feature: add distinct as an option

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#17]
Hello,

Sometimes when inserting Usernames, Emails and other properties to a database the values must be unique. It would be nice to have a Distinct option in Bogus.

Thank You,
Miguel

**Comment by bchavez** [comment]
Hi Miguel,

Thanks very much for taking the time to write up your feature request.

I think it might be possible to do with *some* methods like `UserName` and `Email`. Are there any other data methods that you might have in mind?

Off the top of my mind, the only way to ensure distinct usernames and emails is to carry a static value and increment the value on every call for for data like `Email` and `UserName`.

Let me know if you have any other ideas.

Thanks,
Brian

**Comment by mdmoura** [comment]
Hi,

Yes, using an index would be a good option. Something like this?

    var index = 0;
    var users = new Faker<User>()
      .RuleFor(u => u.UserName, f => f.Internet.UserName(index))
      .Generate(20).ToList();

I think a Full Person name could also allow this ... The reason is that many times the username and email are created from the first and last name ... 

Consider you have a list of 40 first names and 40 surnames. With a cross product:

    var fullNames = firstNames.SelectMany(x => lastNames.Select(y => $"{x} {y}")).OrderBy(z => Guid.NewGuid()).ToList()

This would give 1600 full names ... If the index would become bigger than the available fill names then would go to 1 and stop being unique.

So then the following could be used:

    var users = new Faker<User>()
      .RuleFor(u => u.FullName, f => f.Name.FullName(index))
      .RuleFor(u => u.UserName, (f, u) => u.Internet.Username(f.FullName))
      .Generate(200).ToList();

Thank You,
Miguel

**Comment by bchavez** [comment]
Hi @mdmoura / Miguel,

I thought about this over the week and I'm having some reservations about building uniqueness into Bogus.

Here are some of my concerns:

* The upstream project, faker.js, doesn't have any infrastructure to support uniqueness.
* Building uniqueness into Bogus would seem to impose a specific/fixed formatted implementation for unique values.
* I'm not sure building LINQ cross products in memory is the best solution.
* Uniqueness imposes an additional maintenance cost on us for existing and future API's.
* Some contexts, such as telephone numbers, uniqueness would seem appropriate. But, as you know, telephone numbers have a finite number space. So, there's no easy way to enforce uniqueness among telephone numbers.

It seems to me the *appropriate* level of uniqueness would depend on the developer's perspective specific to the project use case. I'm not totally convinced we should internally impose a format within Bogus that ensures uniqueness.

The best we can provide, I think, is what we've already provided: A lambda function to allow the developer to format a value in anyway he/she sees fit; including formatting a value that ensures uniqueness for a generated value. For example:

```
int uniqueValue = 0;
var users = new Faker<User>()
  .RuleFor(u => u.FullName, f => f.Name.FullName())
  .RuleFor(u => u.UserName, (f, u) => $"{uniqueValue++}{u.Internet.Username(f.FullName)}")
  .Generate(200).ToList();
```

My gut feeling here is: we may have to forego this feature request for the reasons/concerns I mentioned above. I'd be happy to hear if you have anything else to say. Additionally, I hope this doesn't put you off from contributing ideas or code in the future. I really value your input to the project.

Thanks,
Brian

**Comment by mdmoura** [comment]
Hello Brian,

I understand your point but let me make a suggestion. Consider I have the following:

      var users = new Faker<User>()
        .RuleFor(x => x.Email, x => x.Internet.Email() + index)        
        .RuleFor(x => x.UserName, x => x.Internet.UserName() + index++)
        .Generate(10).ToList();

I will have users with email and username ending in "0, 1, ...". However, sometimes I need to perform some calculations based on index and having the ++ creates a problem. And frequently the following also happens:

      var users = new Faker<User>()
        .RuleFor(x => x.Email, x => x.Internet.Email() + index)        
        .RuleFor(x => x.UserName, x => x.Internet.UserName() + index++)
        .RuleFor(x => x.Alias, x => x.Person.Alias() + index)
        .Generate(10).ToList();

Alias will not have the same number of Email and Username unless I move UserName to the end.

Why not expose an internal Index, as you do with x.Random, that increments in each object created? 

It would be also a good option being able to change the way that is calculated. You have:

    Randomizer.Seed = new Random();

Why not also have (note: update is just an example. name it whatever you feel like it):

    var hashids = new Hashids("this is my salt");
    Indexer.Update(x =>  hashids.Encode(x));

    HashIds: http://hashids.org/

Then when using 

    .RuleFor(x => x.UserName, x => x.Internet.UserName() + x.Index)

Would add not 0, 1, 2, ... to UserName but something like "abf", "xyh", ...

Or any other rule ... This could also be done locally at each rule and not only globally:

    .RuleFor(x => x.UserName, x => x.Internet.UserName() + x.Index(y => hashids.Encode(y))

What do you think? This would help a lot with uniqueness.

Thanks, 
Miguel

**Comment by bchavez** [comment]
Hi Miguel,

You have a very reasonable suggestion. I've implemented your suggestion here:

https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/UniquenessTests.cs

Please let me know if this looks reasonable for your use.

Thanks,
Brian

**Comment by mdmoura** [comment]
Hi,

That looks great. When do expect to publish this version on Nuget?

Thanks,
Miguel

**Comment by bchavez** [comment]
Hi Miguel,

[`v5.1.1-beta-1`](https://www.nuget.org/packages/Bogus/5.1.1-beta-1) should be available now (and in search when NuGet's Index finally gets updated).

This should contain fixes for #17 and #20 .

Let me know if it works for you. Thanks!
-Brian

**Comment by mdmoura** [comment]
Hello,

I was testing UniqueIndex and realized that you defined as long ... I am not sure this is a good idea because when using, for example, list[index] it expects an int ... In fact I think the range of the int is quite enough (https://msdn.microsoft.com/en-us/library/5kzh1b5w.aspx) and using it avoids having casts everywhere including in lists indexes.

What do you think?

Thanks

**Comment by mdmoura** [comment]
Hi,

I tried the following:

    List<Post> posts = new Faker<Post>()
      .RuleFor(x => x.Title, y => new List<String>() {  "A", "B", "C", "D" }[y.UniqueIndex])
      .Generate(2).ToList();

And I get the following error:

     Index was out of range. Must be non-negative and less than the size of the collection.

Maybe UniqueIndex is being null? Not sure as I tried to add and subtract 1 but looking at the source the UniqueIndex is starting at 0 so this error should not happen.

Thanks

**Comment by bchavez** [comment]
Hi Miguel,

I don't think that's how `y.UniqueIndex` is meant to be used. `UniqueIndex` is a monotonically increasing value that is increased anytime `Generate` is called. `UniqueIndex` will eventually get out of bounds if you use it as an indexer into a list.

Something better would probably be to use `y.UniqueIndex modulo 4`:

```
.RuleFor(x => x.Title, y => new List<String>() {  "A", "B", "C", "D" }[y.UniqueIndex % 4])
```

**Comment by mdmoura** [comment]
Hi Brian,

My code was an example. In fact I have a long list of unique titles.

But note that I am generating only 2 posts when I have 4 titles so it should not get out of bonds.

I figured out what was wrong. I had two Fakes so I needed to do something as follows:

      List<Tag> tags = new Faker<Tag>()
        .RuleFor(x => x.Name, y => new String[] { "A", "B", "C", "D" }[y.UniqueIndex])
        .Generate(4).ToList();

      Faker.GlobalUniqueIndex = 0;

      List<Post> posts = new Faker<Post>()
        .RuleFor(x => x.Title, y => new String[] { "A", "B", "C", "D" }[y.UniqueIndex])
        .Generate(4).ToList();

Should not GlobalUniqueIndex be set to 0 on Generate start?

Thanks,
Miguel

**Comment by bchavez** [comment]
Hi Miguel,

The `y.UniqueIndex` is used as a global, monotonically increasing, unique integer, across multiple `Faker<T>` objects so it can be used as a unique value that helps solves your original issue of generating unique faker values. `y.UniqueIndex` shouldn't be used directly as an index into an array. `y.UniqueIndex` should only be used to help generate a unique value to help pass a database uniqueness constraint (between `int.MinValue` and `int.MaxValue`).

You shouldn't use `Faker.GlobalUniqueIndex` directly; I only chose to expose it for advanced scenarios for those that want control over the global index. `Faker.GlobalUniqueIndex = 0` shouldn't be used directly or set directly, especially in a scenario like this.

If you require an index into an array, you need to use the `modulo` operator to loop around values inside the array.

```
new String[] { "A", "B", "C", "D" }[y.UniqueIndex % 4 //length of array]
```

Alternatively, if you need a deterministic iteration of string values in the array: ie:
```
A, B, C, D, A, B, C, D, A, B, C, D, A ... etc
```
then you'll need to drive the sequence manually with an index under your control.

```
int indexer = 0;
var faker = new Faker<User>()
    .RuleFor(u => u.FirstName, f => f.Name.FirstName())
    .RuleFor(u => u.LastName, f => new[] {"A", "B", "C", "D"}[indexer % 4])
    .FinishWith((f, u) => indexer++);

var fakes = faker.Generate(10).ToList();
```

and `LastName` will have on each generate, `A` or `B` or `C` or `D`, for each user generated, in a deterministic sequence.

I hope this helps.

**Comment by mdmoura** [comment]
Fair enough ... I was just not sure if this was intended. As it is is fine. 

Thanks

**Comment by bugproof** [comment]
So what's the solution for this?

**Comment by ABIOLI-COM** [comment]
I found this thread, and I took the idea as a challenge. With some functional programming it's possible to have a good solution, without even touching the original library code...
I implemented the following:

```
        private static readonly Dictionary<Guid, List<string>> uniqueStrings = [];
        private static readonly Dictionary<Guid, List<decimal>> uniqueDecimals = [];
        private static readonly Dictionary<Guid, List<int>> uniqueInts = [];
        private static Dictionary<Guid, List<T>> GetDictionary<T>()
        {
            if (typeof(T) == typeof(string))
            {
                return (Dictionary<Guid, List<T>>)Convert.ChangeType(uniqueStrings, typeof(Dictionary<Guid, List<T>>), CultureInfo.InvariantCulture);
            }
            if (typeof(T) == typeof(decimal))
            {
                return (Dictionary<Guid, List<T>>)Convert.ChangeType(uniqueDecimals, typeof(Dictionary<Guid, List<T>>), CultureInfo.InvariantCulture);
            }
            if (typeof(T) == typeof(int))
            {
                return (Dictionary<Guid, List<T>>)Convert.ChangeType(uniqueInts, typeof(Dictionary<Guid, List<T>>), CultureInfo.InvariantCulture);
            }
            throw new BogusException("Dictionary not yet implemented");
        }
        private static Func<Faker, T> GetUnique<T>(Guid guid, Func<Faker, T> func, int limit = 1000)
        {
            Dictionary<Guid, List<T>> uniques = GetDictionary<T>();

            if (!uniques.TryGetValue(guid, out List<T>? value))
            {
                uniques[guid] = [];
            }

            return f =>
            {
                T t = func(f);
                int i = 0;
                while (uniques[guid].Contains(t))
                {
                    t = func(f);
                    i++;
                    if (i == limit)
                    {
                        throw new BogusException("Cannot generate a further unique element");
                    }
                }

                uniques[guid].Add(t);
                return t;
            };
        }

```

This leads us to be able to write code like the following:

```
    internal sealed class Person
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Salary { get; set; }
    }


        [Fact]
        public void GetUniqueTest()
        {
            Person _ = new ();

            Faker<Person> personFaker = new Faker<Person>()
                .RuleFor(c => c.Id, GetUnique(Guid.NewGuid(), f => f.Random.Int(1, 100)))
                .RuleFor(c => c.Name, GetUnique(Guid.NewGuid(), f => f.Person.FullName))
                .RuleFor(c => c.Salary, f => f.Random.Decimal(1000, 2000));

            List<Person> people = [];
            for (int i = 0; i < 100; i++)
            {
                people.Add(personFaker.Generate());
            }

            bool anyDuplicateId = people.GroupBy(x => x.Id).Any(g => g.Count() > 1);
            Assert.False(anyDuplicateId);

            bool anyDuplicateName = people.GroupBy(x => x.Name).Any(g => g.Count() > 1);
            Assert.False(anyDuplicateName);
        }

```

A few comments:
- The implementation is quite rough, but I don't have the time right now to improve it, but it shouldn't be difficult.
- There's a limit on iteration, while trying to find the next 'free' element, and as you can see in the test, in the case of an integer, we generate 100 ids in the interval (1, 100): this means that with a limit of 1,000 we are anyway able to generate any single integer in the interval (and unique, of course).
- The Guid is added in the dictionaries to have different sets of elements in different parts of the definitions (for example, to have distinct strings in different fields).
- I didn't consider at all the composition of elements, where having a unique combination of non-unique elements could be enough, but this is left as an excercise! :-) (I don't have any clue, at the moment, on how to implement this...)

Have fun!
