### ISSUE TITLE
Could not Find DumpAsJson() method

### ISSUE THREAD

**Issue by defyjoy** [bchavez/Bogus#173]
HI I am not able to find DumpAsJson() or Dump() . Where is that located . The documentation lack for this functionality

**Comment by bchavez** [comment]
Hello,

The demos were run in [**LINQPad**](https://www.linqpad.net/). The `.Dump()` method is a [**LINQPad**](https://www.linqpad.net/) extension.

If you're looking for similar functionality, it can be found here:
https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/ExtensionsForTesting.cs

It's just **Newtonsoft.Json** with an `Indented` format.

Hope that helps.

Thanks,
Brian

:black_circle: :dizzy: ***["Black magic... bla-a-a-ack... black magic..."](https://www.youtube.com/watch?v=3SnlsTtUZK0)***
