### ISSUE TITLE
Support new locale (fr-ch)

### ISSUE THREAD

**Issue by jfreyre** [bchavez/Bogus#175]
Hi guys,

My PR on faker.js has just been merged into master (https://github.com/Marak/faker.js/pull/668).

Any way to support this culture in the c# port :)

Thanks in advance

**Comment by bchavez** [comment]
Hi Jérome,

[**Bogus `v24.0.0`**](https://www.nuget.org/packages/Bogus/24.0.0) is now available with latest data/locale parity with faker.js.

Your new `fr_CH` locale should be added in `v24`.

Enjoy,
Brian :sunglasses: 

:fallen_leaf: :leaves: **[Distance - Falling (ft Alys Be)](https://www.youtube.com/watch?v=WIfwIv4wNCE)**

**Comment by jfreyre** [comment]
Hi Brian,

Thanks for your reactivity ;)

Have a good day
