### ISSUE TITLE
Bogus Premium Generate RuleFor() Abstract Classes

### ISSUE THREAD

**Issue by morrisandy** [bchavez/Bogus#184]
Hi There,

I was utilizing a premium feature of bogus to generate bogus test data for a model with an abstract base class associated with it. However, I noticed that field's within the model's base class do not get populated by the generator tool.

For example:

```
public abstract class Person
{
 public string FirstName {get; set;}
 public string LastName {get; set;}
}

public class Employee : Person
{
 public DateTime HireDate {get; set;}
}

var employee = new Faker<Employee>();
```

If I try to use the generator tool on the var employee Faker, it will only generate the HireDate and not the additional FirstName and LastName fields within the base class.

Is there a way to include fields from a model's base class and have bogus test data generated for them?

Thanks

**Comment by bchavez** [comment]
Hi Andrew,

Thank you for the bug report. I'll get to work on that. It's very possible I missed something. I'll do some testing for this case and I'll try to have a fix for you as fast as possible.

Thanks,
Brian

:zap: :runner: ***["I was struck by lighting. Walkin' down the street..."](https://www.youtube.com/watch?v=iypUpv9xelg)***

**Comment by bchavez** [comment]
Hi Andrew,

I think I have a fix ready. Please try out [**Bogus.Tools.Analyzer** `v24.3.0.4`](https://www.nuget.org/packages/Bogus.Tools.Analyzer/24.3.0.4) and let me know if it works for you.

Thanks again for your support!
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by morrisandy** [comment]
Hi Brian,

Thank's for the speedy response and resolution. Just managed to test it out and seems to be working as described.

Thanks greatly
