### ISSUE TITLE
LoremPixel is down, probably move to a different service.

### ISSUE THREAD

**Issue by peek4y** [bchavez/Bogus#186]
- LoremPixel is down
  - Move to service like [unsplash](http://unsplash.com)
  - Or [Picsum Photos](https://picsum.photos/)

**Comment by bchavez** [comment]
Hi @peek4y ,

Thanks for raising the issue. For now, the best thing you could do is to:
1. Derive from `Bogus.DataSets.Images` and override `ImageUrl`, then replace the `Faker.Image` property. You can do that by again, deriving `MyFaker : Faker`, then in the constructor, replace the `.Image` property with your own fix.
1. If you're working in a Browser, another solution is using `Images.DataUri()` which produces SVG place holder images.

Ultimately, I glanced at **Upsplash**'s API terms of service and I do not think those terms would work for **Bogus**.
https://unsplash.com/api-terms

Also, **Picsum Photos** uses **Upsplash**. Perhaps also subject to their API terms as well. This issue will have to be put on hold until we can work out the details.

Thanks,
Brian

:dizzy: :boom: **[Chaos Chaos - Do You Feel It?](https://www.youtube.com/watch?v=MH17AHIklCM)**

**Comment by bchavez** [comment]
I spoke with David Marby, creator of Picsum Photos, and he clarified the API usage with **Upsplash**. I will look at integrating **Picsum Photos** for **Bogus**. Thank you for the issue Gautham.

![chrome_2321](https://user-images.githubusercontent.com/478118/47943638-35a0a480-deb4-11e8-9332-5573a9016542.png)


Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Comment by bchavez** [comment]
Hi Gautham,

Sorry for the late response. I had a really bad day yesterday but I'm back in action. New **Bogus** `v24.3.1` release has support for **Picsum Photos**. Just use:
* `f.Image.PicsumUrl(...)`
* `new Faker().Image.PicsumUrl(...)`
   etc.

Also, thank you for the offer. I really appreciate it. Thanks again for keeping **Bogus** honest. :+1: 

https://www.nuget.org/packages/Bogus/24.3.1

Enjoy,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by peek4y** [comment]
Nice! Thanks for the update, Brian.
