### ISSUE TITLE
Add Country to Person.Address

### ISSUE THREAD

**Issue by NoofSaeidh** [bchavez/Bogus#189]
Faker.Person.Address now doesn't contain Country, but contain State. It's a little bit strange.
It would be good to add it too.

**Comment by bchavez** [comment]
Hi Alexey,

Thank you for your issue. I appreciate it.

The original intention behind `Person.Address` was more about local addresses within a country/locale, not so much as a means to generate international addresses. At least here in the USA, we don't usually add our country name to mail items sent within the territory. So, that was the original thinking behind `Person.Address`.

It was assumed that the address generated by `new Person(locale)` would be local to the locale that was specified. IIRC, the `address.default_country` is used for this purpose. As it stands now, even if we added a `Country` field, the `Country` field would have to remain somewhat constant for the given locale. For example, `new Person("en_US")` currently includes US state names:

![linqpad_2370](https://user-images.githubusercontent.com/478118/48429010-165e0e80-e721-11e8-8004-242b5f38e5b8.png)

If `Country` was random, it would look less realistic when US states like **California** start showing up in countries like **Australia**. So, we can't do that.

Additionally, there are some locales that don't have `address.default_country` specified. For example, the [**Korean** locale](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/ko.locale.json) doesn't specify a `address.default_country` entry, so `new Person("ko").Address.Country` would fall back to the ["United States of America"](https://github.com/bchavez/Bogus/blob/57ae562c903b9917d0482479b13ed500663d54bf/Source/Bogus/data/en.locale.json#L1043-L1045) with the `en` locale, which would make things, again, less-realistic.

![linqpad_2371](https://user-images.githubusercontent.com/478118/48433216-6b9f1d80-e72b-11e8-9a3b-18c520a32997.png)

So, in the end, [`faker.js`](https://github.com/Marak/faker.js/) needs to specify an `address.default_country` for every locale for this to reasonably work well. I hope that makes sense. I think it might be better to raise this issue with Faker.js.

Let me know if you have any other thoughts.

Thanks,
Brian
