### ISSUE TITLE
Create a well defined way to extend Bogus

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#19]
Hello,

I think it would be really useful to have a common way to extend bogus. I am using:

```
public static String DummyImage(this Images images, Int32 width = 640, Int32 height = 480) {
  return $"https://placehold.it/{width}x{height}";
}
```

But I feel that extending Bogus is not very clear ... A common API for extending would be great.

BTW, Images return a URL but most of the cases what I need is a BYTE array of the image to save on da database filestream or on a folder. So I am using the following:

```
public static class HttpFileLoader {

  private static IDictionary<String, Byte[]> files = new Dictionary<String, Byte[]>();

  public static Byte[] Load(this String url) {
    return LoadAsync(url).Result;
  } 

  public async static Task<Byte[]> LoadAsync(this String url) {

    if (files.ContainsKey(url))
      return files[url];

      using (HttpClient client = new HttpClient()) { 
        Byte[] file = await client.GetByteArrayAsync(url);
        files.Add(url, file);
        return file;
      }          
  }
} 
```

Note: I am saving the URL and File on a dictionary for caching.
         I think for dummy data that is enough ...

And I use it:

```
      List<File> files = new Faker<File>()
        .RuleFor(x => x.Id, y => 0)
        .RuleFor(x => x.Content, y => y.Image.DummyImage(80, 80).Load())
```

And now I got the Image content and not just an URL.
I am not sure if it makes sense to have this included on Bogus ... 
Just explaining the way I am using it.

Thank You,
Miguel

**Comment by mdmoura** [comment]
I think having a class to extend instead of a String would be better

**Comment by bchavez** [comment]
Hi Miguel,

I think in this particular case, using an Extension method like you've done already is a great start to extending Bogus. I would probably do the following:

```
public static class ExtensionsForBogus{
   public static String DummyImageUrl(this Images images, Int32 width = 640, Int32 height = 480) {
      return $"https://placehold.it/{width}x{height}";
   }
   public static byte[] DummyImageBytes(this Images images, Int32 width = 640, Int32 height = 480)
   {
      var url = DummyImageUrl(null, width, height);
      return HttpFileLoader.Load(url)
   }
}
```

Then you can use it like this:

```
List<File> files = new Faker<File>()
       .RuleFor(x => x.Id, y => 0)
       .RuleFor(x => x.Content, y => y.Image.DummyImageBytes(80, 80))
```

**Comment by mdmoura** [comment]
The reason why I have the Load extension and not DummyImageBytes is because it also allows to load images from the URLs that Bogus already includes and not only from placehold.it.

But in fact, at the moment, I am doing something like this:

          FileClient client = new FileClient();

          List<File> files = new Faker<File>()
            .RuleFor(x => x.Id, 0)
            .RuleFor(x => x.MimeType, "image/jpeg")
            .RuleFor(x => x.Content, y => client.GetFromUrl(y.Image.Dummy(80, 80)))

The reason why I am doing this is it feels strange to me to have a String extension such as:

     public async static Task<Byte[]> LoadAsync(this String url) { }

That can only be applied to certain types of Strings, e.g., urls ... That is why I said the extension entry point of Bogus could be a class, or even better, an interface. Then any extension would be applied to a specific Bogus object and not to a String with some restriction.

BTW, File Client is the following:

    public class FileClient {

      private static IDictionary<String, Byte[]> files = new Dictionary<String, Byte[]>();

      public Byte[] GetFromPath(String path) {

        if (files.ContainsKey(path))
          return files[path];

        Byte[] file = File.ReadAllBytes(path);
        files.Add(path, file);
        return file;

      } // GetFromPath

      public Byte[] GetFromUrl(String url) {
        return GetFromUrlAsync(url).Result;
      } // GetFromUrl

      public async Task<Byte[]> GetFromUrlAsync(String url) {

        if (files.ContainsKey(url))
          return files[url];

        using (HttpClient client = new HttpClient()) {
          Byte[] file = await client.GetByteArrayAsync(url);
          files.Add(url, file);
          return file;
        }

      } // GetFromUrlAsync

    } // FileClient
