### ISSUE TITLE
Consider upgrading NewtonSoft.Json to 7.0.0.0

### ISSUE THREAD

**Issue by Mpdreamz** [bchavez/Bogus#2]
Getting bit by the following in my test project referencing Json.NET 7.0: 

> System.TypeInitializationException: The type initializer for 'Tests.Framework.MockData.Project' threw 
> an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, 
> Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. 
> The located assembly's manifest definition does not match the assembly reference. (Exception from 
> HRESULT: 0x80131040)
> at Bogus.DataSets.Name.FirstName()

Love `Bogus` so far, it's replacing AutoPoco as my go to tool to create mock poco's :+1:

**Comment by bchavez** [comment]
@Mpdreamz Wow. Cool. Thank you for your contributions & your vote of confidence. Your changes have been merged, nuget release soon.
