### ISSUE TITLE
Feature: add new RuleFor method

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#20]
Hello,

When using Faker usually the following is used:

    .RuleFor(x => x.Flag, y => "EBook File")

But in this simple cases why not have a new method do be used as:

    .RuleFor(x => x.Key, "EBook File")

No need for the lambda expression ... So maybe adding a new RuleFor method:

    public Faker<T> RuleFor<TProperty>(Expression<Func<T, TProperty>> property, TProperty setter)

Thank You

**Comment by bchavez** [comment]
Hi Miguel,

Thanks for your suggestion. I really appreciate it. This looks pretty good and very reasonable.

I'll try implement your suggestion this coming weekend.

Thanks again!
Brian

**Comment by mdmoura** [comment]
You are welcome!

Cheers

**Comment by bchavez** [comment]
Hi @mdmoura ,

Finally got this implemented in e8c4a3a4d02d810ae11a7363000d4cb2a52f4f7f

Thanks again,
-Brian

**Comment by mdmoura** [comment]
Hello,

This is not working as expected. I have the following:

            .RuleFor(x => x.Id, 0)
            .RuleFor(x => x.CreatedAt, null)
            .RuleFor(x => x.IsAccepted, false)

Id is an Int, CreatedAt is a datetime and IsAccepted is a Boolean.

This does not work in any of them because it is always expecting a String and not the type of the property.

Thanks

**Comment by bchavez** [comment]
Hi Miguel,

I've made some changes per your suggestion. Please give [`beta-2`](https://www.nuget.org/packages/Bogus/5.1.1-beta-2) a try. Also, made `UniqueIndex` as an integer.

Let me know how it goes. I will also take a look at #19 later next week.

Thanks,
Brian

**Comment by mdmoura** [comment]
Hi,

I still find a bug. For example:

    .RuleFor(x => x.Name, null)

The method does not accept nulls which would be useful when setting

    .StrictMode(true)

Thanks

**Comment by bchavez** [comment]
Hi Miguel,

I don't think there's anything I can do about this. It seems to be an ambiguous call to `RuleFor`:

```
RuleFor<TProperty>(Expression<Func<T, TProperty>> property, Func<Faker, TProperty> setter )
RuleFor<TProperty>(Expression<Func<T, TProperty>> property, TProperty constantValue)
```

The best you can do, I think, is to resolve the ambiguous call by:

```
.RuleFor(x => x.Name, null as string)
.RuleFor(x => x.Name, (string)null)
```

You can also use `.Ignore( x => x.Name )` to exclude it from `.StrictMode(true)`.

**Comment by mdmoura** [comment]
Yes, I miss the Ignore option. That is fine.

Is there any reason why in the following example the Guid is always the same:

              new Faker<File>()
                .RuleFor(x => x.Key, Guid.NewGuid())
                .Generate(6).ToList()

But on the following the Key is always different:

              new Faker<File>()
                .RuleFor(x => x.Key, y => Guid.NewGuid())
                .Generate(6).ToList()

Should both cases work the same way?

**Comment by bchavez** [comment]
```
new Faker<File>()
  .RuleFor(x => x.Key, Guid.NewGuid())
  .Generate(6).ToList()
```
is equivalent to passing an argument once:

```
var constant = Guid.NewGuid()
new Faker<File>()
  .RuleFor(x => x.Key, constant)
  .Generate(6).ToList()
```
The followoing `.RuleFor` can only be evaluated one time because it is not a lambda function.
```
  .RuleFor(x => x.Key, constant)
```
The following `.RuleFor` is a lambda function:
```
.RuleFor(x => x.Key, y => Guid.NewGuid())
```
And it can be called many times, hence generating a new value on every time a value is needed.

**Comment by bchavez** [comment]
Also, you can use the gitter channel here: https://gitter.im/bchavez/Bogus if you need more help
