### ISSUE TITLE
Generate Anonymous Type with Bogus

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#207]
Hello,

I am using Entity Framework Core to Seed Data in Migrations:
https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding

When using seeding data in the new EF model the best option is to use anonymous type.

Is it possible to generate anonymous type using Bogus?

Thank You,
Miguel

**Comment by bchavez** [comment]
After a quick experiment with the idea; I found it is possible to generate anonymous type objects with `Faker<AnonType>` rules. Check it out. LOL. I just don't know if I should add this code to Bogus and if it is a good idea or not. By doing this we are violating some serious C# language rules for immutable anonymous types.

I'm going to re-open this for public comment. If the community thinks this facility in Bogus could be useful; we could add it.

![devenv_2789](https://user-images.githubusercontent.com/478118/52949733-fd718480-3331-11e9-829a-206e3a4c9cb6.png)

![devenv_2788](https://user-images.githubusercontent.com/478118/52949751-0bbfa080-3332-11e9-978e-71cef19062df.png)



If you want to experiment with it, here's a diff of the changes to Bogus' source that made the hack work. There's nothing stopping you from doing this in your own code. The main magic that made everything work is the `AnonBinder` class that can be already be accepted by `Faker<T>(binder:)` constructor parameter. If you wanted to do this on your own, you could just create any static class with a static method with:
```csharp
public static Faker<U> FromAnonymousType<U>(U obj) where U : class
{
   int FindConstructorLength()
   {
      return typeof(U).GetConstructorsX().First().GetParameters().Length;
   }

   var count = FindConstructorLength();

   var args = new object[count];

   var anonBinder = new AnonBinder();

   return new Faker<U>(binder: anonBinder)
      .CustomInstantiator(_ =>
         Activator.CreateInstance(typeof(U), args: args) as U);
}
```


```diff
Source/Bogus.Tests/FluentTests.cs          | 33 ++++++++++++++++++++++++++++++
 Source/Bogus/Binder.cs                     | 27 ++++++++++++++++++++++++
 Source/Bogus/Faker.cs                      | 18 ++++++++++++++++
 Source/Bogus/Faker[T].cs                   |  1 +
 Source/Bogus/Platform/ExtensionsForType.cs | 10 +++++++++
 5 files changed, 89 insertions(+)

diff --git a/Source/Bogus.Tests/FluentTests.cs b/Source/Bogus.Tests/FluentTests.cs
index 48a9b6c..8b9e29e 100644
--- a/Source/Bogus.Tests/FluentTests.cs
+++ b/Source/Bogus.Tests/FluentTests.cs
@@ -5,11 +5,19 @@
 using Bogus.Extensions;
 using FluentAssertions;
 using Xunit;
+using Xunit.Abstractions;
 
 namespace Bogus.Tests
 {
    public class Examples : SeededTest
    {
+      private readonly ITestOutputHelper console;
+
+      public Examples(ITestOutputHelper console)
+      {
+         this.console = console;
+      }
+
       [Fact]
       public void TestAPIDesign()
       {
@@ -412,5 +420,30 @@ public void can_generate_forever()
             if( count > 99 ) break;
          }
       }
+
+      [Fact]
+      public void can_get_faker_from_anon_type()
+      {
+         var anon = new { age = 0, name = "" };
+
+         var anonFaker = Faker.FromAnonymousType(anon)
+            .RuleFor( x => x.age, f => f.Random.Number(1, 60) )
+            .RuleFor( x => x.name, f => f.Name.FullName() );
+
+         anonFaker.Populate(anon);
+         anon.age.Should().NotBe(0);
+
+         var newAnonObjects = anonFaker.Generate(3);
+         
+         foreach( var o in newAnonObjects )
+         {
+            o.age.Should()
+               .BeGreaterOrEqualTo(1).And
+               .BeLessOrEqualTo(60);
+            o.name.Should().NotBeNullOrWhiteSpace();
+         }
+
+         console.Dump(newAnonObjects);
+      }
    }
 }
\ No newline at end of file
diff --git a/Source/Bogus/Binder.cs b/Source/Bogus/Binder.cs
index ca6a829..fe4a586 100644
--- a/Source/Bogus/Binder.cs
+++ b/Source/Bogus/Binder.cs
@@ -94,4 +94,31 @@ public Binder(BindingFlags bindingFlags)
          return group.ToDictionary(k => k.Key, g => g.First());
       }
    }
+
+   public class AnonBinder : Binder
+   {
+      public override Dictionary<string, MemberInfo> GetMembers(Type t)
+      {
+         var group = t.GetMembers(BindingFlags)
+            .Where(m =>
+               {
+                  if( m is FieldInfo fi )
+                  {
+                     return fi.IsPrivate;
+                  }
+
+                  return false;
+               })
+            .GroupBy(mi =>
+               {
+                  return mi.Name
+                     .Replace("i__Field", "")
+                     .Replace('<', ' ')
+                     .Replace('>', ' ')
+                     .Trim();
+               });
+
+         return group.ToDictionary(k => k.Key, g => g.First());
+      }
+   }
 }
\ No newline at end of file
diff --git a/Source/Bogus/Faker.cs b/Source/Bogus/Faker.cs
index 4b38305..5612d29 100644
--- a/Source/Bogus/Faker.cs
+++ b/Source/Bogus/Faker.cs
@@ -3,6 +3,7 @@
 using System.Threading;
 using Bogus.DataSets;
 using System;
+using Bogus.Platform;
 
 namespace Bogus
 {
@@ -11,6 +12,23 @@ namespace Bogus
    /// </summary>
    public class Faker : ILocaleAware, IHasRandomizer, IHasContext
    {
+      public static Faker<U> FromAnonymousType<U>(U obj) where U : class
+      {
+         int FindConstructorLength()
+         {
+            return typeof(U).GetConstructorsX().First().GetParameters().Length;
+         }
+
+         var count = FindConstructorLength();
+
+         var args = new object[count];
+
+         var anonBinder = new AnonBinder();
+
+         return new Faker<U>(binder: anonBinder)
+            .CustomInstantiator(_ =>
+               Activator.CreateInstance(typeof(U), args: args) as U);
+      }
       /// <summary>
       /// The default mode to use when generating objects. Strict mode ensures that all properties have rules.
       /// </summary>
diff --git a/Source/Bogus/Faker[T].cs b/Source/Bogus/Faker[T].cs
index 0d1410a..65f745f 100644
--- a/Source/Bogus/Faker[T].cs
+++ b/Source/Bogus/Faker[T].cs
@@ -5,6 +5,7 @@
 using System.Reflection;
 using System.Text;
 using Bogus.Extensions;
+using Bogus.Platform;
 
 namespace Bogus
 {
diff --git a/Source/Bogus/Platform/ExtensionsForType.cs b/Source/Bogus/Platform/ExtensionsForType.cs
index f074208..b026e7f 100644
--- a/Source/Bogus/Platform/ExtensionsForType.cs
+++ b/Source/Bogus/Platform/ExtensionsForType.cs
@@ -1,4 +1,5 @@
 using System;
+using System.Linq;
 using System.Reflection;
 
 namespace Bogus.Platform
@@ -31,6 +32,15 @@ public static Assembly GetAssembly(this Type type)
          return type.GetTypeInfo().Assembly;
 #else
          return type.Assembly;
+#endif
+      }
+
+      public static ConstructorInfo[] GetConstructorsX(this Type type)
+      {
+#if STANDARD13
+         return type.GetTypeInfo().DeclaredConstructors.ToArray();
+#else
+         return type.GetConstructors();
 #endif
       }
    }
```

**Comment by mdmoura** [comment]
The reason why I close it, a few minutes after, is because I just opted to do this:

      Faker<Category> categoryFaker = new Faker<Category>()
        .RuleFor(x => x.Id, y => ++y.IndexVariable);

      var categories = categoryFaker.Generate(4).Select(x => new { Id = x.Id });

So I think it is better then adding adding Anonymous to Bogus as you mention ... No?

**Comment by bchavez** [comment]
I see. That's pretty cleaver. :)

Yea, I'd prefer and *recommend* still using a formal `Faker<T>` / POCO model to keep things sane. But let's leave the issue open for a week or two and see if anyone else comments on the subject.

I mean for a quick hack, `Faker.FromAnonymousType()` is kinda neat. :sunglasses:

**Comment by mdmoura** [comment]
> But let's leave the issue open for a week or two and see if anyone else comments on the subject.

Sure.

> I mean for a quick hack, `Faker.FromAnonymousType()` is kinda neat.

Yes, it is. :-)

**Comment by bchavez** [comment]
I slept on this issue of anonymous type generation in Bogus and woke up with another solution to generate anonymous types:
```csharp
var f = new Faker();
var categories = from i in Enumerable.Range(1, 20)
                 select new { id = i, name = f.Lorem.Word() };
```
Alternatively,
```csharp
var f = new Faker();
var categories = Enumerable.Range(1, 20)
                  .Select(i => new { id= i, name = f.Lorem.Word() });
```
![linqpad_2790](https://user-images.githubusercontent.com/478118/52971997-434c3e00-336e-11e9-8218-80f579878686.png)

It works; and it's a lot more safe, and dare I say a little more elegant? What do you think?

:sleeping: :zzz: :bulb: :sunglasses: 

:crescent_moon: :stars: ***["Nothing good happens past 2am..."](https://www.youtube.com/watch?v=VOlcDBXKhSU)***

**Comment by mdmoura** [comment]
> It works; and it's a lot more safe, and dare I say a little more elegant and proper? What do you think?

Yes, I think it is a good option ... I used Enumerable.Range(1, 20) before ...

You could also have something like the following (maybe it does not make sense):

```
var f = new Faker();
var categories = f.Generate(20)
                  .Select(i => new { id= i, name = f.Lorem.Word() })
                  .ToList();
```

Generate could have another name and it is just something to obfuscate Enumerable.Range.

Like this would be part of Faker ... But again I am not even sure it is a good idea ...

**Comment by AntLaC** [comment]
what about using a DynamicObject class?

**Comment by bchavez** [comment]
Hi @AntLaC ,

For `dynamic` objects, here are 3 different styles to try (mostly just variations of the first one):
```csharp
var f = new Faker();
var dynamicObjects = Enumerable.Range(1, 20) 
            .Select( i => {
               dynamic item = new ExpandoObject();
               item.id = i;
               item.name = f.Name.FullName();
               return item;
            })
            .ToList();;
            
dynamicObjects.First().other = f.Random.Number(100,200);

Dump(dynamicObjects);   
```
----
```csharp
var f = new Faker();
var dynamicObjects = Enumerable.Range(1, 20)
            .Select(_ => new ExpandoObject() as dynamic )
            .Select(d =>
            {
               d.id = f.IndexVariable++;
               d.name = f.Name.FullName();
               return d;
            })
            .ToList();;
            
dynamicObjects.First().other = f.Random.Number(100,200);
```

------
```csharp
var f = new Faker();
var dynamicObjects = Enumerable.Range(1, 20)
            .Select(i => (id: i, obj: new ExpandoObject() as dynamic ))
            .Select(x =>
            {
               x.obj.id = x.id;
               x.obj.name = f.Name.FullName();
               return x.obj;
            })
            .ToList();;

dynamicObjects.First().other = f.Random.Number(100,200);
````


All produce similar results:
![linqpad_2800](https://user-images.githubusercontent.com/478118/53141320-7fd19280-3544-11e9-8e82-b76fb9bdee48.png)

**Comment by AntLaC** [comment]
Thanks for the help, I went a different route since I will have an unknown number of properties:

`		public static ExpandoObject Generate(Dictionary<string, PropertyTypes> properties)
		{
			var faker = new Faker();
			var item = new ExpandoObject() as IDictionary<string, object>;
			var person = new Person();
			properties.ToList().ForEach(props =>
			{
				switch (props.Value)
				{
					case PropertyTypes.FullName:
						item.Add(props.Key, faker.Name.FullName());
						break;
					case PropertyTypes.LastName:
						item.Add(props.Key, person.LastName);
						break;
					case PropertyTypes.FirstName:
						item.Add(props.Key, person.FirstName);
						break;
					case PropertyTypes.UserName:
						item.Add(props.Key, person.UserName);
						break;
					default:
						item.Add(props.Key, faker.IndexVariable++);
						break;
				}
			});
			return (ExpandoObject)item;`

**Comment by bchavez** [comment]
Hey Miguel,

I finally decided to not add `Faker.FromAnonymousType` method unless we have a good use case for something like this in future.

For those who want to generate anonymous types with Bogus, you should use patterns similar to my previous [comment here](https://github.com/bchavez/Bogus/issues/207#issuecomment-464849451). And @AntLaC 's comment for [dynamic types with dynamic properties](https://github.com/bchavez/Bogus/issues/207#issuecomment-466145811).

**Comment by oddgames-david** [comment]
I would like to test all my data objects in my project that derive from a base class. I'd prefer to use reflection to find all the data classes to be sure each one is being tested and re-use the same rule set RuleForType etc.

Simplifies creating quick unit tests.
