### ISSUE TITLE
Rude/inappropriate email when using default settings.

### ISSUE THREAD

**Issue by bartdebever** [bchavez/Bogus#209]
Used the default settings of the Internet's Email generator and manged to get the email "Gaylord56@hotmail.com". As you can understand, this is not what a business application would want.

I wasn't using any particular seed, just using a Faker of my user type.

**Comment by bartdebever** [comment]
So this is intended by Faker as it is a legitimate first name...
Names will continue to amaze me, closing issue.

**Comment by bchavez** [comment]
Yea, the name appears in names of people, business names, places, and names of cities within the United States as well. https://en.wikipedia.org/wiki/Gaylord
