### ISSUE TITLE
PickRandom to accept a N parameter an return more than one item

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#21]
Hello,

I think it would be really useful that PickRandom could return more than one item.

    .RuleFor(x => x.Tags, y => tags.OrderBy(z => Guid.NewGuid()).Take(4).ToList())

I think instead the following could be done:

    .RuleFor(x => x.Tags, y => y.PickRandom(tags, 4))

Internally, the following could be used:

    collection.OrderBy(x => Guid.NewGuid()).Take(n)

or any other option ...

Thanks,
Miguel

**Comment by bchavez** [comment]
Hi Miguel,

The API already has something similar. You could do this also:

```
.RuleFor(x => x.Tags, y => y.Random.Shuffle(tags).Take(4) )
```

**Comment by mdmoura** [comment]
Got it ... missed that. Thanks
