### ISSUE TITLE
Use Faker.PickRandom outside Rules() or RuleFor()

### ISSUE THREAD

**Issue by NayanPerron** [bchavez/Bogus#215]
Is it possible to use the Bogus.Faker.PickRandom outside of the methode  Rules() or RuleFor()?

Exemple: 

`var gender = Bogus.Faker.PickRandom<GenderEnum>();`

When i try this, i got an error "An object reference is required for the property, the method or non static field Bogus.Faker.PickRandom<GenderEnum>() ".

**Comment by bchavez** [comment]
Hi Nayan,

Yes, you can use `.PickRandom()` or any method/property used in rules by using the `Faker` facade.

Read more about this usage here:
https://github.com/bchavez/Bogus#without-fluent-syntax

To summarize, your code would look like:
```csharp
var f = new Bogus.Faker();
var g = f.PickRandom<GenderEnum>();
Console.WriteLine(g);

//OUTPUT:
Female
```

**Comment by NayanPerron** [comment]
Hi bchavez,

Thanks for the info and the exemple.
