### ISSUE TITLE
Can we make the Analyzer work with AutoBogus?

### ISSUE THREAD

**Issue by adamhill** [bchavez/Bogus#217]
The Analyzer does not give me a Rosyln tooltip for AutoFaker declarations, I wish it would.

The workaround is simple but it's a piece of friction in an awesome library to help reduce friction. I would even be willing to do the coding for it. 

Thanks.

**Comment by bchavez** [comment]
Hi Adam,

Thanks for the recommendation! That's a great suggestion. Let's see if we can make that magic happen.

Could you give me a sample `AutoFaker` declaration you'd like to see work? A sample would be great so I can get a general bearing and make sure we're thinking about the same idea.

Thanks!
Brian

:crystal_ball: :dolls: ***["Magic and technology. Voodoo dolls and chants. Electricity. Were makin weird science..."](https://www.youtube.com/watch?v=Jm-upHSP9KU)***

**Comment by bchavez** [comment]
Oooo, hey, it works now! Actually, works for any derived generic type that inherits from `Faker<T>`!

New release coming out shortly. :sunglasses: 

![Untitled](https://user-images.githubusercontent.com/478118/56840357-ff792780-683b-11e9-8db7-a6131b6fc4dc.gif)

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by bchavez** [comment]
Hi Adam,

This feature is implemented starting with v26.0.2.5 of `Bogus.Tools.Analyzer`! 
https://www.nuget.org/packages/Bogus.Tools.Analyzer/26.0.2.5

Let me know how it goes. Thanks again for the suggestion!

Cheers,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
