### ISSUE TITLE
Global strict mode not working

### ISSUE THREAD

**Issue by JoschaHemlep** [bchavez/Bogus#218]
Bogus v26.0.2
.NET CORE 2.1

`Faker.DefaultStrictMode = true;` is not working.

`new Faker<Foo>().StrictMode(true);` works

**Comment by bchavez** [comment]
Hi Joscha,

This should be fixed in **Bogus** `v27.0.1`. https://www.nuget.org/packages/Bogus/27.0.1

Thanks for reporting the issue! Let me know how it goes!

-Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
