### ISSUE TITLE
Seed per type / property

### ISSUE THREAD

**Issue by MartinJohns** [bchavez/Bogus#220]
I'd like to make a suggestion for a "_seed per type / property_" feature in addition to a global seed.

**The problem:**

- Using the global seed I get different values whenever I adjust any fakers rules or call a new faker before the others.
- Using the local seed I get different values when I add a new rule (even when added last).
- Using the same local seed for multiple fakers I get the same values across different fakers.

**The suggestion:**

Use the global/local seed, but adjust it based on the type / property.  
For example:

    globalSeed ^ typeof(T).GetHashCode()
    // or
    globalSeed ^ typeof(T).GetHashCode()
        ^ GetPropertyName(propertySelectorExpression).GetHashCode()

This way you would get reliable consistent random values depending on a single global seed, even when adding new rules or new fakers.

On a per-type basis this can be done already using the local seed:

    const int GLOBAL_SEED = 123456;
    int SeedFor<T>() => GLOBAL_SEED ^ typeof(T).GetHashCode();
    
    new Faker<SomeType>.UseSeed(SeedFor<SomeType>());

**Comment by bchavez** [comment]
Hi @MartinJohns,

Thanks for your suggestion. I really appreciate it.

I'm assuming [you've read Bogus' advanced topics on determinism](https://github.com/bchavez/Bogus#advanced-topics-guidance-and-best-practices). Determinism is something I've thought long and hard about. I'm always open to new ideas to improve the situation.

However, there are some issues deriving seeds from `typeof(T).GetHashCode()`. Most notably is `.GetHashCode()` itself depends on the order in which it executes in the runtime. See below:

```csharp
static void Main(string[] args)
{
   WriteLine("Book: "+typeof(Book).GetHashCode());
   WriteLine("Car:  "+typeof(Car).GetHashCode());
}
```
```
Hello World!
Book: 43495525
Car:  55915408
```
```csharp
static void Main(string[] args)
{
   WriteLine("Car:  "+typeof(Car).GetHashCode());
   WriteLine("Book: "+typeof(Book).GetHashCode());
}
```
```
Hello World!
Car:  43495525
Book: 55915408
```
(thanks for the help from people at the https://gitter.im/dotnet/roslyn chat)

Consequently, `Faker<T>`'s seed values would also change depending on the order in which `Faker<T>` execute in the runtime; which could arguably be just as brittle.

I also thought about using hashed property names for seeds too, but what happens when we refactor/rename `SurName` to `LastName`?

The only way I've found to isolate changes is to basically make a dedicated `Random` for each `Faker<T>` rule where the user is in full control of the deterministic seed on a per-property basis:

```csharp
var userFaker = new Faker<User>()
            .UseSeed(something)
            .RuleFor(u => u.LastName, f => f.Name.LastName(), seed: 1337);
```
The resulting `Random` source for each `.RuleFor` is derived from `something ^ 1337`. This could make it immune to property renames, but having to specify a seed for each property seems like a heavy burden for users.

Let me know what you think.

Thanks,
Brian

:thought_balloon: :mag: ***["I want to know... what you're thinking..."](https://www.youtube.com/watch?v=ijAYN9zVnwg)***

**Comment by bchavez** [comment]
> * Using the local seed I get different values when I add a new rule (even when added last).

Hey @MartinJohns, also could you give me an example of how you're using fakers that produce different values when adding a new rule?

The following code seems to work fine here:
```csharp
void Main()
{
   var orderIds = 0;
   var orderFaker = new Faker<Order>()
       .RuleFor(o => o.OrderId, f => orderIds++)
       .RuleFor(o => o.Item, f => f.Commerce.Product())
       .RuleFor(o => o.Quantity, f => f.Random.Number(1, 5));

   Order MakeOrder(int seed)
   {
      return orderFaker.UseSeed(seed).Generate();
   }

   var orders = Enumerable.Range(1, 5)
      .Select(MakeOrder)
      .ToList().Dump();
}

public class Order{
   public int OrderId{get;set;}
   public string Item{get;set;}
   public int Quantity{get;set;}
   public string Description{get;set;}
}
```

![LINQPad_3046](https://user-images.githubusercontent.com/478118/57183578-eb4cb000-6e63-11e9-84e2-beb8511f7639.png)

Then add the new rule:
```csharp
var orderFaker = new Faker<Order>()
    .RuleFor(o => o.OrderId, f => orderIds++)
    .RuleFor(o => o.Item, f => f.Commerce.Product())
    .RuleFor(o => o.Quantity, f => f.Random.Number(1, 5))
    .RuleFor(o => o.Description, f => f.Commerce.ProductAdjective()); //New Rule
```

![LINQPad_3047](https://user-images.githubusercontent.com/478118/57183591-13d4aa00-6e64-11e9-9a1c-08c0ff1612cf.png)

**Comment by bchavez** [comment]
Hey @MartinJohns, feel free to post more if you want to continue the conversation or have any more input on the topic. For now, I'm going to close the issue.

Thanks a bunch for your feedback. I appreciate it.
Brian

:fire: :volcano: ***["We're building it up, to break it back down..."](https://www.youtube.com/watch?v=dxytyRy-O1k)***

**Comment by bchavez** [comment]
I recently had an idea of using multiple `Faker<T>` of the same `T` to "layer over" previous runs. Essentially, each time we change a POCO schema, we generate a new random source for that batch of POCO schema change.

To illustrate, consider the following:

```csharp
public class Person
{
   public string Name { get; set; }
   public int Age { get; set; }
   public string NewField { get; set; }
}

void Main()
{
   var dataVersion1 = new Faker<Person>()
            .UseSeed(1337)
            .RuleFor(p => p.Name, f => f.Name.FullName())
            .RuleFor(p => p.Age, f => f.Random.Number(18, 30));

   var fakePeople = dataVersion1.Generate(10);
   fakePeople.Dump();
}
```
![LINQPad_3058](https://user-images.githubusercontent.com/478118/57425216-53d2be80-71cf-11e9-918a-66d936fc5783.png)

Now, let's overlay a new `.RuleFor( p => p.NewField, ...)` in a 2nd `Faker<Person>` over the existing data set by calling `.Populate(obj)` without affecting the previous run of data:

```csharp
void Main()
{
   var dataVersion1 = new Faker<Person>()
            .UseSeed(1337)
            .RuleFor(p => p.Name, f => f.Name.FullName())
            .RuleFor(p => p.Age, f => f.Random.Number(18,30));
            
   var dataVersion2 = new Faker<Person>()
            .UseSeed(7331)
            .RuleFor(p => p.NewField, f => f.Random.String2(27) );
            
   var fakePeople = dataVersion1.Generate(10);
   
   foreach( var p in fakePeople) dataVersion2.Populate(p);

   fakePeople.Dump();
}
```

![LINQPad_3059](https://user-images.githubusercontent.com/478118/57425308-9b594a80-71cf-11e9-88a9-0ad992aeb31c.png)

Notice our existing data from our first run remains intact. Fancy technique. Admittedly, it is very similar to adding "new rules last" except we rewind to the beginning of the generated data list and apply the new `.RuleFor(p => p.NewField,...)` values on the 2nd run which fills in the missing data in `Person.NewField` without affecting any other fields.

As a minor optimization, we could probably avoid the "list rewind" of `2n` by chaining `dataVersion1.Chain(dataVersion2)` which would execute `dataVersion1` rules first, then `dataVersion2` right after for each instance of `T`.

So, if you want more discrete control over deterministic data when POCO schemas change, this might be a good approach too. The basic idea here is we treat our first `Faker<T>` as immutable and create new `Faker<T>` if we want to change data/add/remove data on generated instances of `T`.

:thinking: :sparkles: ***["Do you ponder the manner of things... yeah yeah... like glitter and gold..."](https://www.youtube.com/watch?v=IrV90gXmOpA)***
