### ISSUE TITLE
Add RG to person on Bogus.Extensions.Brazil

### ISSUE THREAD

**Issue by rafael-calderani** [bchavez/Bogus#226]
RG is the official national identity document in Brazil. It is often informally called carteira de identidade (identity card), "RG" (from Registro Geral, General Registry) or simply identidade in Portuguese.

**Comment by bchavez** [comment]
Hello,

I can't find anything online about the format, algorithm, or standard regarding an RG number.

https://rogertakemiya.com.br/en/generator-de-rg/

>There is no standard
There is no single rule for numbering the identity document.
>
>This is because each federative unit (state) has the full autonomy to issue the RG (acronym for "General Registry") any way you want.
>
>Each state adopts the standard that suits you. In Rio de Janeiro and São Paulo, for example, the RG is composed of eight digits plus one digit of confirmation, type 12 345 678-9.
>
>To end disorganization and lack of standard, the federal government wants to unify the system of issuing identities. However for this there is no exact prediction.

Your best bet is to use something like `f.Random.Replace("## ### ###-#")` or whatever you're looking to generate in your region.

```csharp
void Main()
{
   var f = new Faker();
   var rgNumbers = Enumerable.Range(1, 10)
            .Select(_ => f.Random.Replace("## ### ###-#"));
            
   rgNumbers.Dump();
}
```

![LINQPad_3436](https://user-images.githubusercontent.com/478118/60129661-5de25980-974a-11e9-822a-db40423519b1.png)

If you want to extend Bogus, you can also do the following:
```csharp
void Main()
{
   var fakeUsers = new Faker<User>("pt_BR")
   .RuleFor(u => u.Name, f => f.Person.FullName)
   .RuleFor(u => u.RG, f => f.Person.RGPerson() );
            
   fakeUsers.Generate(10).Dump();
}
public class User{
   public string Name{get;set;}
   public string RG{get;set;}
}

public static class MyBogusExtensionsForBR{
   public static string RG(this Faker f){
      return f.Random.Replace("## ### ###-#");
   }
   public static string RGPerson(this Person p ){
      return p.Random.Replace("## ### ###-#");
   }
}
```
![LINQPad_3437](https://user-images.githubusercontent.com/478118/60129938-10b2b780-974b-11e9-999e-ae5279b5d9f7.png)

If you can point me to an algorithm or some reasonable way of generating RG numbers, feel free to post.

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***
