### ISSUE TITLE
Add CVV generator based on CreditCardNumber

### ISSUE THREAD

**Issue by rafael-calderani** [bchavez/Bogus#227]
When testing functions using credit card we often have the need to validate both the number and security code of card and they are dependent on each other to be valid.

So there should be an optional parameter for the Credit card number when calling Bogus.DataSets.Finance.CreditCardCvv method that creates a valid CVV based on the cradicard passed as parameter.

**Comment by bchavez** [comment]
Hello,

A credit card CVV does appear to be a calculated value, however, the CVV is derived by some cryptographic algorithm with keys that are only known to banks. How this algorithm works and how CVV verification occurs without bank's encryption keys is unknown to me.

https://security.stackexchange.com/questions/123315/is-cvv-calculated-or-merely-assigned
https://www.ibm.com/support/knowledgecenter/en/linuxonibm/com.ibm.linux.z.wskc.doc/wskc_r_csg.html

> Use the CVV Generate verb to generate a VISA Card Verification Value (CVV) or MasterCard Card Verification Code (CVC) as defined for track 2.
>
> This verb generates a CVV that is based on the information that the PAN_data, the expiration_date, and the service_code parameters provide. This verb uses the Key-A and the Key-B keys to cryptographically process this information. Key-A and Key-B can be single-length DATA or MAC keys, or a combined Key-A, Key-B double length DATA or MAC key. If the requested CVV is shorter than 5 characters, the CVV is padded on the right by space characters. The CVV is returned in the 5-byte variable that the CVV_value parameter identifies. When you verify a CVV, compare the result to the value that the CVV_value supplies.
>
> See CVV Key Combine (CSNBCKC) for information on combining two single-length MAC-capable keys into one double-length key.

You'll have to point me to a CVV verification algorithm or provide some pseudo code that describes this calculation process before I can consider adding it to Bogus.

Thanks,
Brian

:violin: :palm_tree: ***["'Cause it's a bittersweet symphony, this life..."](https://www.youtube.com/watch?v=1lyu1KKwC74)***
