### ISSUE TITLE
The word "ghetto" should be removed

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [bchavez/Bogus#228]
I used the Rant property and one of the items generated was: ""this Widget is ghetto."
This can be a very sensitive word to many people and should not be in the dataset for any purpose.

**Comment by WhatFreshHellIsThis** [comment]
(Also the word "Gypsy: appears in that same set and is widely considered racist in modern times)

**Comment by bchavez** [comment]
Hello,

Thanks for raising the issue. The items in the `.Rant` property were generated with [Rant][1] ([repo][2]), (more specifically, the [Rantionary][3]). **If you want words removed, you'll have to make the request with upstream data providers.**

Generally, with issues like this, my response is roughly the same as #209. If the `.Rant` property offends you, try the `.Lorem` property as shown below:

```csharp
var f = new Faker();
f.Lorem.Sentence().Dump();
// Deserunt iusto ullam sint sapiente aut.
```

You can also patch the runtime database by removing items you find offensive. The code below demonstrates how to remove reviews from the runtime database:

```csharp
void Main()
{
   var reviews = Database.Get("rant", "review") as BArray;
   reviews.Count.Dump();
   // 316 reviews

   ContentFilter.MakeBogusKidSafe();

   reviews = Database.Get("rant", "review") as BArray;
   reviews.Count.Dump();
   // 314 reviews
}

public static class ContentFilter
{
   public static void MakeBogusKidSafe()
   {
      var array = Database.Get("rant", "review") as BArray;

      var badWords = new string[] { "ghetto", "Gypsy" };

      var badReviews = array.OfType<BValue>()
                            .Where(r => badWords.Any(b => r.StringValue.Contains(b, StringComparison.OrdinalIgnoreCase)))
                            .ToArray();

      foreach (var badReview in badReviews)
      {
         array.Remove(badReview);
      }
   }
}
```

For the sake of argument, the `.Rant` property can help maintain developer awareness that there might be a need for content filters for whatever systems they are building. Using `.Rant` would be a good way to test those content filters or keep awareness early in the development process.

[1]:https://www.nuget.org/packages/Rant/
[2]:https://github.com/TheBerkin/Rant
[3]:https://github.com/RantLang/Rantionary

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by WhatFreshHellIsThis** [comment]
With respect, it's not at all like the other issue you referred to which is of course a proper name; these words will widely offend a lot of people and Gypsy is outright racist by today's standards.  

I will not use that feature to avoid offending people and I urge you to reconsider using that upstream provider rather than simply passing the blame.

The concept and feature of a product rant / review is great and would have been useful in my application however they implemented it poorly (many of the phrases are just copies of each other with nonsense words inserted it reads like a poor google translate, it could be done far better) aside from the racist term.
