### ISSUE TITLE
Looking for a cleaner way to generate distinct composite keys.

### ISSUE THREAD

**Issue by VictorioBerra** [bchavez/Bogus#236]
Hello, hopefully you might have some clever ideas on how to solve this simple problem. I feel like mine is a little more complicated than it needs to be? You be the judge.

## Entity

```csharp
// ProductId + OrderId form the composite key
// IE: `modelBuilder.Entity<ProductOrderLine>().HasKey(bc => new { bc.OrderId, bc.ProductId });`
public class ProductOrderLine
{
    public int OrderId { get; set; }
    public int ProductId { get; set; }

    public Order Order { get; set; }
    public Product Product { get; set; }
}
```

## Rules

```csharp
ProductOrderLineFaker = new Faker<ProductOrderLine>()
    .StrictMode(false)
    .UseSeed(5555)
    .RuleFor(d => d.ProductId, f => f.PickRandom(Products).Id)
    .RuleFor(d => d.OrderId, f => f.PickRandom(Orders).Id);

ProductOrderLines = ProductOrderLineFaker
    .Generate(300)
    .Distinct(new ProductOrderLineDeDupeComparer())
    .ToList();
```

## IComparer

`.Distinct` uses to de-dupe so we do not violate foreign key constraints (cant have two identical composite keys!)    

```csharp
public class ProductOrderLineDeDupeComparer : IEqualityComparer<ProductOrderLine>
{
    public bool Equals(ProductOrderLine x, ProductOrderLine y)
    {        
        return x.OrderId == y.OrderId && x.ProductId == y.ProductId;
    }

    public int GetHashCode(WuitInventoryServerProductLine obj)
    {
        return obj.OrderId.GetHashCode() ^ obj.ProductId.GetHashCode();
    }
}
```

**Essentially I was wondering if there was a "PickRandom" which saved state and tracked what I had already taken so that I can take from a finite pool and never get a duplicate?**

**Comment by VictorioBerra** [comment]
Slightly cleaner, is the use of MoreLinq `DistinctBy`: `.DistinctBy(x => new { x.ProductId, x.OrderId } )` instead of an entire comparer. But this still means that I might randomly end up not using an Id.

**Comment by bchavez** [comment]
Hi Victorio,

Thank you for your question.

From my point of view, I think you have a couple of approaches that can remove the need for a distinct comparer. At first glance, it seems an *iterative* approach to make `ProductOrderLine` objects is more natural than a *declarative* `Faker<ProductOrderLine>` approach.

In other words, there are two *iterative* approaches you can take:
* Pre-compute the list of all possible `.OrderId + .ProductId` that doesn't violate the composite key constraint. Then draw from that pre-computed pool and `.Take()` as needed.
* For each `Order`, take a random subset of `Products` and make `ProductOrderLine` objects. 

I'll demonstrate the latter with the following code example below:

```csharp
void Main()
{
   Randomizer.Seed = new Random(1339);
   
   var orderFaker = new Faker<Order>()
   .RuleFor( o => o.OrderId, f => f.IndexFaker )
   .RuleFor( o => o.CustomerName, f => f.Name.FullName() );
   
   var productFaker = new Faker<Product>()
   .RuleFor( p => p.ProductId, f => f.IndexFaker )
   .RuleFor( p => p.Description, f => f.Commerce.Product() )
   .RuleFor( p => p.SKU, f => f.Random.Replace("*********"));
   
   var orders = orderFaker.Generate(10);
   orders.Dump();
   
   var products = productFaker.Generate(10);
   products.Dump();
   
   var faker = new Faker();
      
   var orderLines = orders
      .SelectMany(o =>
      {
         return faker.Random.ListItems(products)
                     .Select( p => new ProductOrderLine
                       {
                          ProductId = p.ProductId,
                          OrderId = o.OrderId
                       });
      });
   
   orderLines.OrderBy(l => l.OrderId).Dump();
}

public class ProductOrderLine
{
   public int OrderId { get; set; }
   public int ProductId { get; set; }

   public Order Order { get; set; }
   public Product Product { get; set; }
}
public class Order{
   public int OrderId{get;set;}
   public string CustomerName{get;set;}
}
public class Product{
   public int ProductId{get;set;}
   public string Description{get;set;}
   public string SKU {get;set;}
}
```

#### `Order`
OrderId | CustomerName
-- | --
0 | Deondre Purdy
1 | Mervin Herzog
2 | Nathanial Quigley
3 | Rubie Donnelly
4 | Lorenza Bartell
5 | Omer Sporer
6 | Brayan Bosco
7 | Deja Gislason
8 | Misty Daniel
9 | Thora Sauer

#### `Product`
ProductId | Description | SKU
-- | -- | --
0 | Fish | 2YE357FEQ
1 | Bike | 78ZLFFH89
2 | Table | OU5CX0NI1
3 | Shoes | YS134226Y
4 | Sausages | 285D697Z1
5 | Bacon | 6F6678K06
6 | Computer | EC65N35V3
7 | Car | 293V56H6G
8 | Hat | 5D0M35S6N
9 | Ball | 7V9VAX5ZE


#### `ProductOrderLine`
OrderId | ProductId
-- | --
0 | 8
1 | 3
1 | 4
1 | 0
1 | 1
1 | 6
1 | 8
1 | 2
1 | 5
2 | 9
2 | 3
2 | 0
2 | 7
2 | 2
2 | 4
3 | 8
3 | 0
3 | 7
3 | 6
3 | 5
3 | 3
3 | 4
3 | 2
....|....

You can also generalize this approach with the following extension method and it cleans up the `.SelectMany` statement in the `Main()` method quite nicely:

```csharp
void Main()
{
   // ... same Faker<T> code for orders and products as previous example
   var faker = new Faker();

   var orderLines = faker.MakeRelation(orders, products,  
         (o, p) => new ProductOrderLine { 
                       OrderId = o.OrderId,
                       ProductId = p.ProductId }
       );
   orderLines.OrderBy(l => l.OrderId).Dump();
}

public static class MyCustomExtensions
{
   public static IEnumerable<V> MakeRelation<T, U, V>(
              this Faker f,
              List<T> parent, 
              List<U> children, 
              Func<T, U, V> creator)
   {
      return parent.SelectMany(a =>
      {
         return f.Random.ListItems(children)
                 .Select(c => creator(a, c));
      });
   }
}
```

Hope that helps!

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by VictorioBerra** [comment]
This is much cleaner I really like this solution. I learn more about Bogus every day like `f.IndexFaker`

Side note on that, any way to globally make `f.IndexFaker` start at 1 across the board? EntityFramework is not a big fan of int PKs of 0.

**Comment by VictorioBerra** [comment]
Also I do not have this situation but I want to point out that this needs to be tweaked kind of heavily if you ever need to add metadata to `ProductOrderLine` like `QuantityOrdered`. Im still investigating how you would do this.

**Comment by bchavez** [comment]
Hi Victorio,

Here are three ways you can use `f.IndexFaker` starting from a number other than zero for Entity Framework:

## Option A: +1 offset rule
```csharp
var orderFaker = new Faker<Order>()
      .RuleFor(o => o.OrderId, f => f.IndexFaker + 1)
      .RuleFor(o => o.CustomerName, f => f.Name.FullName());
```
![LINQPad_3464](https://user-images.githubusercontent.com/478118/60843165-c5f16080-a18a-11e9-9812-741ad34f120f.png)

## Option B: Custom `UseStartIndex` extension
```csharp
var orderFaker = new Faker<Order>()
      .StartIndex(7)
      .RuleFor(o => o.OrderId, f => f.IndexFaker)
      .RuleFor(o => o.CustomerName, f => f.Name.FullName());

public static class MyEfExtensions
{
   public static Faker<T> UseStartIndex<T>(this Faker<T> faker, int n ) where T : class
   {
      var hub = faker as IFakerTInternal;
      hub.FakerHub.IndexFaker = n - 1;
      return faker;
   }
}
```
![LINQPad_3468](https://user-images.githubusercontent.com/478118/60843769-6a27d700-a18c-11e9-965f-dd2039de28dc.png)


## Option C: Subclassed `EfFaker<T>`
```csharp
var orderFaker = new EfFaker<Order>()
      .RuleFor(o => o.OrderId, f => f.IndexFaker)
      .RuleFor(o => o.CustomerName, f => f.Name.FullName());

public class EfFaker<T> : Faker<T> where T : class
{
   public EfFaker(): base() {
      this.FakerHub.IndexFaker = 100;
   }
}
```
![LINQPad_3470](https://user-images.githubusercontent.com/478118/60843829-917ea400-a18c-11e9-83d1-9dd7ad4d149e.png)

-------

Take your pick, whichever you find is easiest, most appropriate, and maintainable for your situation.

Hope that helps,
Brian

:art: :dash: **[Marshmello - CoLoUR](https://www.youtube.com/watch?v=6UhNJC8OyVA)**

**Comment by bchavez** [comment]
Hey Victorio,

I don't think tweaking should be necessary. Creating metadata without major changes should be fine. If you need to add `QuantityOrdered` to `ProductOrderLine`, the extension method doesn't need to change because `faker` is still in scope. For example,

```csharp
var faker = new Faker();

var orderLines = faker.MakeRelation(orders, products,
      (o, p) => new ProductOrderLine
      {
         OrderId = o.OrderId,
         ProductId = p.ProductId,
         QuantityOrdered = faker.Random.Int(1, 5)
      }
    );
orderLines.OrderBy(l => l.OrderId).Dump();
```
OrderId | ProductId | QuantityOrdered
-- | -- | --
0 | 1 | 2
0 | 3 | 2
1 | 6 | 3
2 | 0 | 3
2 | 3 | 2
2 | 9 | 4
2 | 5 | 5
2 | 4 | 1
3 | 4 | 4

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by VictorioBerra** [comment]
Thanks all that makes a lot of sense. Is there any caution to using a global faker instance like that across multiple `MakeRelations`?  Right now i create a new `Faker<T>` for all my other entities. Should I create a new faker for each of my desired Line entities in order to not blow anything up when/if I start changing settings of the faker?

**Comment by bchavez** [comment]
Hi Victorio,

I don't see any immediate issue using a global `Faker`. However, to keep things sane, you'll probably want to avoid multiple threads partying on the ***same*** `new Faker()` global instance.

In my view, `new Faker` facades are cheap and free. If determinism is important to you, you might want to consider creating a new instance for some logical "generation" operation like maybe creating a dedicated `Faker` facade instance for `ProductOrderLine` generation. Sometimes localized `Faker` facades can help with determinism. Similar to `Faker<T>.UseSeed(n)`, you can also localize and seed `Faker` facade instances too. The example below shows how to create locally seeded `Faker` facade instances:

```csharp
public Faker NewFaker(int seed){
   var faker = new Faker();
   faker.Random = new Randomizer(seed);
   return faker;
}
```
Then your code looks something like:
```csharp
var orderLinesFaker = NewFaker(1337)

var orderLines = orderLinesFaker.MakeRelation(orders, products,
      (o, p) => new ProductOrderLine
      {
         OrderId = o.OrderId,
         ProductId = p.ProductId,
         QuantityOrdered = orderLinesFaker.Random.Int(1, 5)
      }
    );
orderLines.OrderBy(l => l.OrderId).Dump();
```

In some ways, creating localized `Faker` facades that are locally seeded can sometimes help maintain deterministic behavior in the face of change. See the [Advanced Topics, Guidance, and Best Practices](https://github.com/bchavez/Bogus#advanced-topics-guidance-and-best-practices) notes I wrote about on the main readme that delves into the topic a bit more. But the basic idea here is that localizing your use of `Faker` and local seeds can help isolate changes between different phases of object generation; *sometimes*.

The most important message I'm trying to convey in all of this is making sure whatever code you write, above all else, try to keep your code as simple, readable, and maintainable as possible. :smiley: 

Hope that helps!
Brian

:cloud: :sunny: **[Bassnectar - Chasing Heaven - Into the Sun](https://www.youtube.com/watch?v=a2BAia075lE)**

**Comment by VictorioBerra** [comment]
> The most important message I'm trying to convey in all of this is making sure whatever code you write, above all else, try to keep your code as simple, readable, and maintainable as possible. 😃

Agreed! Thanks a lot for all the help. This should simplify my code quite a bit.
