### ISSUE TITLE
Randomly generate 2 exclusive properties, on must always be null?

### ISSUE THREAD

**Issue by TheColonel2688** [bchavez/Bogus#238]
So say I have the following class and enum

```
public Enum StepType {Source, Destination, Neither}

public class Step
{
	public Source? Source {get;set;}
	public Destination? Destination {get;set;}
        public StepType {get; set;}
}
```
And I have the following collections

```
ICollection<Source> Sources; // Assume this is not empty
ICollection<Destination> Destinations; // Assume this is not empty
```

How can I create a rule where I select a random item from either list, but only one list, and the other is null, and also Set and Enum of StepType To Correspond. Deciding which one would be null would also be random.

So I would have a Collection of `Step` 

> {Source == *SomeSource*, Destination == null, StepType == StepType.Source},
> {Source == null, Destination == *SomeDestination*, StepType == StepType.Destination},
> {Source == null, Destination == *SomeDestination*, StepType == StepType.Destination},
> {Source == *SomeSource*, Destination == null, StepType == StepType.Source},
> {Source == null, Destination == *SomeDestination*, StepType == StepType.Destination},
> {Source == null, Destination == null, StepType == StepType.Neither},

`var stepFaker<Step> = new Faker<Step>`

**Comment by bchavez** [comment]
Hey there.

```csharp
void Main()
{
   ICollection<Source> Sources; // Assume this is not empty
   ICollection<Destination> Destinations; // Assume this is not empty

   Sources = Enumerable.Range(1, 10).Select(i => new Source(i)).ToArray();
   Destinations = Enumerable.Range(11, 20).Select(i => new Destination(i)).ToArray();

   var stepFaker = new Faker<Step>()
      .RuleFor(s => s.Source, f => f.PickRandom(Sources).OrNull(f))
      .RuleFor(s => s.Destination, (f, s) => s.Source is null ? f.PickRandom(Destinations).OrNull(f) : null)
      .RuleFor(s => s.StepType, (f, s) =>
      {
         if (s.Source is null && s.Destination is null) return StepType.Neither;
         if (s.Source is Source) return StepType.Source;
         return StepType.Destination;
      });

   stepFaker.Generate(10).Dump();
}

public enum StepType { Source, Destination, Neither }

public class Step
{
   public Source Source { get; set; }
   public Destination Destination { get; set; }
   public StepType StepType { get; set; }
}
public class Source
{
   public int Id;
   public Source(int i) => this.Id = i;
}
public class Destination
{
   public int Id;
   public Destination(int i) => this.Id = i;
}
```

Source | Destination | StepType
-- | -- | --
Source | null | Source
null | Destination | Destination
null | null | Neither
null | Destination | Destination
Source | null | Source
null | null | Neither
Source | null | Source
Source | null | Source
Source | null | Source
Source | null | Source

Hope that helps.
