### ISSUE TITLE
A few suggestions for additional fake types

### ISSUE THREAD

**Issue by RehanSaeed** [bchavez/Bogus#24]
Here are a few ideas for additional fakes that I have needed that could be built in:

- System.Version
- System.TimeSpan
- System.DateTimeOffset - Not major as DateTimeOffset has a conversion operator to DateTime.
- System.Guid - Not major as Guid.NewGuid is just as easy.
- Any Exception

**Comment by bchavez** [comment]
Hi @RehanSaeed ,

Thank you for your feedback. I really appreciate it.

Could you give me code some examples of how you're using Any Exception and some of the others?

IIRC, `System.Guid` can be found on `f => f.Random.Uuid()`.

Thanks,
Brian

**Comment by RehanSaeed** [comment]
Thanks for the info about GUID's, I guess I didn't spot it due to the non-standard name.

Currently, I am just randomly instantiating one of three different types of exceptions with a lorem message. For completeness, it would be cool if the exceptions were thrown and caught, then returned so that the StackTrace is populated with something. That would give a much more 'Bogus' exception.

**Comment by bchavez** [comment]
Hi @RehanSaeed ,

I've added `Semver` `Version` and `Timespan`, and `Exception` random generators are now in `/master`. They will be available in the next `6.1.2` release.

Thanks for your suggestions.

**Comment by RehanSaeed** [comment]
Cool. Good job!
