### ISSUE TITLE
Locales not working with Zipcodes?

### ISSUE THREAD

**Issue by gothboiclique** [bchavez/Bogus#242]
Seems that it generates completely random numbers and often completely different from the selected Locale.

**Comment by bchavez** [comment]
Hello,

Thank you for your question. Could you elaborate more about why you think zip codes Bogus generates is wrong or incorrect?

Also, could you let me know:
* What version of Bogus are you using?
* What locale are you using?

As far as I can tell, the behavior you are describing is kind of to be expected.

For example, let's examine the [`Address.ZipCode()`](https://github.com/bchavez/Bogus/blob/c509ca066a1dc6e84b9357c9a1a2e18b71ecb67e/Source/Bogus/DataSets/Address.cs#L32-L35) method. The `ZipCode` method accepts a `format` parameter. If you don't like the format of the zip codes, you can supply your own as shown below:

https://github.com/bchavez/Bogus/blob/c509ca066a1dc6e84b9357c9a1a2e18b71ecb67e/Source/Bogus/DataSets/Address.cs#L27-L35

Furthermore, if `format == null`  and no format is supplied, Bogus attempts to use the currently configured locale seeking `postcode` data. If your specific locale doesn't have a `postcode` data then `GetFormattedValue` falls back to an `en:postcode` which is shown below:

https://github.com/bchavez/Bogus/blob/c509ca066a1dc6e84b9357c9a1a2e18b71ecb67e/Source/Bogus/data/en.locale.json#L777-L780

 The fallback mechanism is described on the README page here:

> ***Note:*** Some locales may not have a complete data set. For example, [`zh_CN`](https://github.com/Marak/faker.js/tree/master/lib/locales/zh_CN) does not have a `lorem` data set, but [`ko`](https://github.com/Marak/faker.js/tree/master/lib/locales/ko) has a `lorem` data set. **Bogus** will default to `en` if a *locale-specific* data set is not found. To further illustrate the previous example, the missing `zh_CN:lorem` data set will default to the `en:lorem` data set.

If you discover that your specific locale doesn't have locale-specific zip code data, and you'd like to improve the data for your locale, then be sure to read this link here: https://github.com/bchavez/Bogus/wiki/Creating-Locales

This is the best help I can provide with the information you've supplied.

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**
