### ISSUE TITLE
Is nesting supported in Bogus

### ISSUE THREAD

**Issue by hyousuf** [bchavez/Bogus#244]
I have just started using Bogus v28.0.2 for the first time and looks very feature rich. Thanks for the wonderful library.

The problem I have is that it seems that nesting fakers does not work properly. Consider the following test scenario

```
        public static Faker<User> UserFixture()
        {
            return new Faker<User>()
                .RuleFor(u => u.FirstName, f => f.Name.FirstName())
                .RuleFor(u => u.LastName, f => f.Name.LastName())
                .RuleFor(u => u.Email, f => f.Internet.Email());
        }

        public static Faker<EntityUser> EntityUserFixture()
        {
            return new Faker<EntityUser>()
                .RuleFor(eu => eu.User, UserFixture())
                .RuleFor(eu => eu.RoleId, 1);
        }
```
 

if I now want to generate a list like this
```
            var users = UserFixture().Generate(2);
            var entityUser = EntityUserFixture().Generate(2);
```

The _users_ variable will provider unique values within users which is fine. But the User property in _entityUser_ seems to get duplicated 

Am I doing anything wrong here

**Comment by bchavez** [comment]
Hi @hyousuf ,

Thanks for your question. I appreciate hearing from users.

I think the problem you're seeing is that you're using the constant value overload of `.RuleFor` which is only evaluated once as `.RuleFor` is invoked rather than for each instance of `T`. For example, be sure to be aware of the following differences:

`.RuleFor(x.prop, constant_value)` - which `constant_value` is provided for every `T` instance.
```csharp
public static Faker<EntityUser> EntityUserFixture()
{
    return new Faker<EntityUser>()
        .RuleFor(eu => eu.User, UserFixture())
        .RuleFor(eu => eu.RoleId, 1);
}
```
vs

`.RuleFor(x.prop, f => func)` - which `f => func` is evaluated for every `T` instance.
```csharp
public static Faker<EntityUser> EntityUserFixture()
{
    return new Faker<EntityUser>()
        .RuleFor(eu => eu.User, f => UserFixture())
        .RuleFor(eu => eu.RoleId, f => 1);
}
```

Let me know if that resolves your issue.

Thanks,
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

**Comment by bchavez** [comment]
Related #20,
Related: https://github.com/bchavez/Bogus/issues/135#issuecomment-375089923

**Comment by hyousuf** [comment]
Thanks for the response, this works fine.

Thanks a mill again for the wonderful library and all the hard work supporting it

> Hi @hyousuf ,
> 
> Thanks for your question. I appreciate hearing from users.
> 
> I think the problem you're seeing is that you're using the constant value overload of `.RuleFor` which is only evaluated once as `.RuleFor` is invoked rather than for each instance of `T`. For example, be sure to be aware of the following differences:
> 
> `.RuleFor(x.prop, constant_value)` - which `constant_value` is provided for every `T` instance.
> 
> ```cs
> public static Faker<EntityUser> EntityUserFixture()
> {
>     return new Faker<EntityUser>()
>         .RuleFor(eu => eu.User, UserFixture())
>         .RuleFor(eu => eu.RoleId, 1);
> }
> ```
> 
> vs
> 
> `.RuleFor(x.prop, f => func)` - which `f => func` is evaluated for every `T` instance.
> 
> ```cs
> public static Faker<EntityUser> EntityUserFixture()
> {
>     return new Faker<EntityUser>()
>         .RuleFor(eu => eu.User, f => UserFixture())
>         .RuleFor(eu => eu.RoleId, f => 1);
> }
> ```
> 
> Let me know if that resolves your issue.
> 
> Thanks,
> Brian
> 
> 🚶 🚶‍♀ **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=DHAMh2-cviA)**
