### ISSUE TITLE
Generating dates, does not return deterministic results with a defined seed

### ISSUE THREAD

**Issue by sepl2604** [bchavez/Bogus#247]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |       28.0.2          |
| .NET Core?                   |        netcoreapp2.1         |
| .NET Full Framework?   |        -         |
| Windows OS?              |       Windows 10 Pro (10.0.18362 Build 18362)           |
| Linux OS?                    |        -          |
| Visual Studio?              |       2019           |

### What locale are you using with Bogus?
en
### What is the expected behavior?
Get a deterministic result for dates
### What is the actual behavior?
Result for generating a date increases each second
### How do you reproduce the issue?
```csharp
// Set a seed to get deterministic results
Randomizer.Seed = new Random(1234);
	
var faker = new Faker();
	
// not working (returns each time a different result)
var dateOfBirth = faker.Person.DateOfBirth;
var past = faker.Date.Past();
// ... ?

// working perfectly (just examples)
var number = faker.Random.Number(int.MaxValue);
var email = faker.Person.Email;
var fullName = faker.Person.FullName;
```
### If the bug is confirmed, would you be willing to submit a PR?

Could try

**Comment by bchavez** [comment]
Hi @sepl2604,

Thanks for posting the issue. For deterministic dates, there's a special static field on `Bogus.DataSets.Date` called `SystemClock` that lets you anchor down the time source of relative date calculations.

To get truly deterministic date calculations on every run, here's what you can do:

```csharp
void Main()
{
   Randomizer.Seed = new Random(1234);
   Bogus.DataSets.Date.SystemClock = () => DateTime.Parse("8/8/2019");
      
   var faker = new Faker();
      
   var dateOfBirth = faker.Person.DateOfBirth;
   dateOfbirth.Dump();
   var past = faker.Date.Past();
   past.Dump();
}
```
```
3/28/1952 12:48:42 AM
9/6/2018 4:31:08 AM
```
The `DateTime` output is deterministic on every run.

PS: You might want to avoid `faker.Person.DateOfBirth` unless you're creating a `new Faker()` on every instance you need a new person. The lifetime of a `faker.Person` property is tied to the lifetime of `Faker`. So, repeat calls to `faker.Person` on the same instance of `Faker` will yield the same person. If you need a new person, use `new Person()` instead.

To illustrate:
```csharp
var f = new Faker();
f.Person.FirstName;
f.Person.DateOfBirth;
f.Person.LastName;

f.Person.FirstName;   // same person as above
f.Person.DateOfBirth; // same person as above
f.Person.LastName;    // same person as above

f = new Faker();
f.Person.FirstName;   //now we have a different person

new Person().FirstName; // different person
new Person().FirstName; // also a different person
new Person().FirstName; // another different person
```

Hope that helps!

Thanks,
Brian

:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***

**Comment by sepl2604** [comment]
Thanks for your quick response and help! I set also the _SystemClock_ to a fixed value, and the generated dates are deterministic.
Anyway, I still have an issue, where I have a test, which creates a snapshot with the generated data. Locally I get a specific (deterministic) date, but on our build server I get a different date (from build to build still deterministic) The difference is 2 hours. Have to have a look at it. Thanks for your help, Brian!

**Comment by sepl2604** [comment]
Good Morning @bchavez , finally get the expected behavior. Currently I use your great library for generating objects, like contracts, persons & so on and store these in a mongoDB. When I now insert some dates, mongoDB assumes that these are not UTC and converts them. After reading the dates again, I get the wrong values. Specifying the dates as UTC like
``` c#
RuleFor(c => c.DateOfBirth, (f, c) => DateTime.SpecifyKind(f.Person.DateOfBirth, DateTimeKind.Utc)); 
```
does the trick. Thanks for the help and sorry for creating an issue due to lack of knowledge regarding the SystemClock field.

Have a great day,
Stefan
