### ISSUE TITLE
String overloads for .RuleFor and .Ignore

### ISSUE THREAD

**Issue by SuricateCan** [bchavez/Bogus#253]
Hey @bchavez,

I'm bringing the discussion from [**AutoBogus**](https://github.com/nickdodd79/AutoBogus/issues/21) over here, so we can consider the changes.

For anyone wanting to catch up, follow the [link](https://github.com/nickdodd79/AutoBogus/issues/21) to read @bchavez considerations, and my own, so far

**Context**

Currently, there is no simple way to configure a rule for hidden members other than inherit from `Faker`.

**Alternatives**

As above says, to accomplish this, we have to inherit from `Faker` and use already existing protected members.

**Has the feature been requested before?**

Not really, but it was requested over in [**AutoBogus**](https://github.com/nickdodd79/AutoBogus/issues/21)

**If the feature request is approved, would you be willing to submit a PR?**

I believe that exposing these members is more a design than technical concern, but given enough time (something we all need...), I'd be happy to help.

**Comment by bchavez** [comment]
Hi Cleverson,

Thank you for creating the GH issue. I'm going to wait for a response from @nickdodd79 and see what his thoughts are. I just want to consider everyone's perspective. I totally agree this is a design issue more than a technical concern.

I read your response and I think we agree on `.StrictMode(true)` throwing for non-existent members that are defined by an untyped `.RuleFor("string", f=>f...)` rule. :+1:

**Comment by nickdodd79** [comment]
Hey @SuricateCan and @bchavez,

Apologies for being late to the party, it's been a busy few days.

I definitely agree that strict is strict and that rule should be maintained across the board. 

In terms of the `.RuleFor("string", f=>f...)` implementation, I am 50/50 as well. However, part of me is included to say that it could be considered inclusive of the simple case. Is there any difference in defining a target property as an Expression or a string?

Nick.

**Comment by bchavez** [comment]
Hey @nickdodd79,

Thanks for the reply.

Truthfully, there's no functional or fundamental difference between the following:

* `.RuleFor("Prop", f =>f...)`
* `.RuleFor(nameof(T.Prop), f =>f...)`
* `.RuleFor(x => x.Prop, f=>f...)`

Except that `.RuleFor("Prop", f =>f...)` string overload will check the results from `IBinder` to ensure that "Prop" (passed in as a string) member exists on `T`. If the user tries to add a rule for a non-existant member **Bogus** will fail fast with an exception (regardless of `StrictMode` setting). For example, adding a rule to `T` where `hhhhh` is non-existent:

```
System.ArgumentException
The property or field hhhhh was not found on Bogus.Tests.Models.Order.
Can't create a rule for Bogus.Tests.Models.Order.hhhhh when hhhhh cannot
be found. Try creating a custom IBinder for Faker<T> with the appropriate
System.Reflection.BindingFlags that allows deeper reflection into
Bogus.Tests.Models.Order.
```

If you're okay with everything, I'll go ahead and merge #254.

**Comment by nickdodd79** [comment]
Yep. All good with me 👍

**Comment by bchavez** [comment]
Cool! Thanks so much for your feedbacks @nickdodd79 @SuricateCan. I'll have a new release out soon.

**Comment by SuricateCan** [comment]
Great! Can't wait to use the new feature! Thanks guys

**Comment by bchavez** [comment]
Okay friends, **Bogus 28.1.1** is out: https://www.nuget.org/packages/Bogus/28.1.1

Let me know if I broke anything :)

**Comment by bchavez** [comment]
Hey guys,

I totally forgot about `.RuleFor("string", (f, t) => )` overload. So, **Bogus 28.2.1** is out that contains the additional overload.

Also, renamed `.RuleForInternal` to `.AddRule`; internally simplified the internal overload call chain because it was getting a bit convoluted and confusing for me.

https://www.nuget.org/packages/Bogus/28.2.1
