### ISSUE TITLE
Generating a random time on a date?

### ISSUE THREAD

**Issue by fatmanmclone90** [bchavez/Bogus#26]
Is there any way to extend the rule to get a recent date, such that you can also get a random time on the date?

Currently the time element always seems the time when object was generated.  My rule looks like:

`.RuleFor(m => m.Timestamp, m => m.Date.Recent(0))`

I would like to be able to generate random times as well as dates.

**Comment by bchavez** [comment]
Hi @fatmanmclone90 ,

Thank you for your feedback. I really appreciate it. I totally agree with you, we should have better support for dates and times. It's somewhat related to #24 in supporting `DateTimeOffset`.

I'm currently on vacation and I'll have to get to this when I get back (probably around April 25th).

Thanks again for bringing this up to my attention. :+1:

**Comment by bchavez** [comment]
This is fixed in master. `.RuleFor(m => m.Timestamp, m => m.Date.Recent(0))` now generates random times between start of day and `now`.
