### ISSUE TITLE
What is "Seed Value"?

### ISSUE THREAD

**Issue by andre-idrive** [bchavez/Bogus#264]
Please excuse my very simple question but I couldn't understand from the documentation what Seed Value is in `Randomizer.Seed(int Seed)`. Can you please help me out?

**Comment by bchavez** [comment]
Hi Andre,

Checkout these links:
https://www.grasshopper3d.com/m/discussion?id=2985220%3ATopic%3A708634

https://docs.microsoft.com/en-us/dotnet/api/system.random.-ctor?view=netframework-4.8#System_Random__ctor_System_Int32_

Basically specifying a seed number will always generate the same random
sequence even across program restarts; hence the name "pusedo".

Thanks,
Brian
