### ISSUE TITLE
A way to generate a boolean with only one true in a set

### ISSUE THREAD

**Issue by sneakpodbob** [bchavez/Bogus#266]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |   28.4.1     |
| .NET Core?                   |    3.0         |
| .NET Full Framework?   |       x         |
| Windows OS?              |      10        |
| Linux OS?                    |        x         |
| Visual Studio?              |      2019   |

### What locale are you using with Bogus?
neutral

### What's the problem?
I want to generate a set of Persons. The objects contains a bool "isResponsible" which point out the one person which is responsible in this context. So I want to generate a set of these Persons where exactly one of the persons has responsible set to true. 

### What possible solutions have you considered?
`.RuleFor(property: pp => pp.IsResponsible, setter: fpp => fpp.Random.Bool(.1f))`
Doesn't work obviously, so I resorted to take care of the problem manually in the FinishWith-Block, is there a better way?

**Comment by bchavez** [comment]
Hi Robert,

Thank you for your question. I have to step out for work right now, but I'll answer your question more thoroughly later tonight when I get home more.

Quickly off the top of my mind, so you're unblocked:

### Option 1
```csharp
var people = personFaker.Generate(100);
people[0].IsResponsible = true
```
### Option 2
```csharp
var people = personFaker.Generate(100).WithOneResponsible();

public static List<Person> WithOneResponsible(this List<Person> people){
   people[0].IsResponsible = true
   return people;
}
```
### Option 3
```csharp
var personFaker = new Faker<Person>()
          .RuleFor(p => p.IsResponsible, f => f.IndexFaker == 0 ? true : false );
```
### Option 4
```csharp
var firstResponsible = true;
var personFaker = new Faker<Person>()
         .RuleFor(p => p.IsResponsible, f => {
                                if( firstResponsible){
                                     firstResponsible = true;
                                     return true;
                                }
                                return false;
                           });
```

Thanks,
Brian Chavez

Related #55.

**Comment by bchavez** [comment]
Hi Robert,

I cleaned up my answer a bit. Feel free to ask any more questions after I close the issue.

I hope that helps.

Thanks,
Brian
