### ISSUE TITLE
README Image docs inaccurate

### ISSUE THREAD

**Issue by mklaber** [bchavez/Bogus#27]
[README.md](https://github.com/bchavez/Bogus/blob/master/README.md) "Images" section is inaccurate:

* The header (**Images**) implies that the faker accessor is called `Images` but it's actually `Image`
* The list of options include `ImageUrl` which is actually a protected method

**Comment by bchavez** [comment]
@mklaber Hi there. This is fixed now. I agree there's a slight naming discrepancy between `f=>f.Image` and the actual data set names in `Bogus.DataSets.Images` This was mostly done to avoid naming conflicts between class/method `Image.Image()`.

So, the **README** mostly sources it's API information from `Bogus.DataSets.*` API not necessarily the faker facade `f=>f.Dataset`.

Hope that helps! If you have anymore thoughts, please feel free to comment below.

Thanks,
Brian
