### ISSUE TITLE
Commerce Data

### ISSUE THREAD

**Issue by CJ1789** [bchavez/Bogus#281]
Ecommerce Data

How to generate related data ie according to department price should be set and according to department product name should be generated.

Are there any validations??

**Comment by bchavez** [comment]
Hi @CJ1789,

Thank you for your question. **Bogus** doesn't have any "validations" for the prices of products.

Product and price validation depend on your particular scenario. You'll have to define those rules upfront. Out of the box, **Bogus** does not have any knowledge of how much things cost. Although, that might be a good idea for a new eCommerce premium data set.

If you have any more questions, please feel free to let me know. I'll be happy to help.

Thanks,
Brian
