### ISSUE TITLE
Bogus.Premium.ContextHelper does it require a premium licence? 

### ISSUE THREAD

**Issue by AlexKeySmith** [bchavez/Bogus#283]
Hi,

Am I right in thinking we can use Bogus.Premium.ContextHelper without a premium licence? And that the premium licence is for the supplementary nuget packages?

I'm experimenting with creating something similar to `Person` (i..e with contextually related data) for data which only makes sense for an internal project, but finding it challenging without overriding lots in `Faker` and `Faker<T>`.  I'm hoping the context helper is the secret sauce.

Keep up the great work btw! I hope to be able to support in someway as well.

**Comment by bchavez** [comment]
[1]:https://www.nuget.org/packages/Bogus/

Hi Alex,

Thanks very much for your question and consideration. I really appreciate it.

You are correct. You can safely use the `ContextHelper` class in the `Bogus.Premium` namespace in the [**`Bogus` NuGet**][1] package without a premium license. No special license is required to use or link against any code in the core [**`Bogus` NuGet**][1] package.

IIRC, some community extensions are already using `ContextHelper`. `ContextHelper` exists in `Bogus.Premium` mostly out of my haste to get the Premium extensions up and running. At the time, I didn't realize other people would be using `ContextHelper` to help extend Bogus for their own extensions.

You're also correct, a premium license is only required for supplementary NuGet packages. The NuGet packages that require a license are listed here indicated by an :x: which are not available for free: https://github.com/bchavez/Bogus/wiki/Bogus-Premium

I hope that helps! Also, thank you again for the question!
Brian

**Comment by AlexKeySmith** [comment]
Thanks for the quick reply @bchavez that's good to know, have a nice weekend!
