### ISSUE TITLE
generating unique random number?

### ISSUE THREAD

**Issue by bonesoul** [bchavez/Bogus#285]
is it possible to generate unique random numbers?

right now i'm calling it with;

```
var faker = new Faker();
faker.Random.Number(10000)
```

have no idea how to write a rule for it

**Comment by RodrigoRodriguesX10** [comment]
Bogus does not implement uniqueness constraint, because of performance issues, but you can create your own extension to do that, but keeping in mind that this can affect the performance of your tests.

Your faker variable is using for what purpose? Are your trying to make a faker to a model or just want to generate random integers?

**Comment by bonesoul** [comment]
this specific test uses faker for generating randoms.

anyway i've implemented uniqueness support using a hashset.

**Comment by RodrigoRodriguesX10** [comment]
Using HashSet is a good way to control uniqueness and I think any other alternative will be similar. To support unique generation you will need to store the generated values and make checks (try to avoid infinite loops). A simple example to control uniqueness for generate 100 unique random ints is:

```
var numbers = new HashSet<int>();
var f = new Faker();

for(int i = 0, v; i < 100; i++){
    do {
        v = faker.Random.Number(10000);
    } while(numbers.Contains(v));
    numbers.Add(v);
    Console.WriteLine("Unique value: " + v);
}

```

Anyway, you need to implement it yourself.

**Comment by bonesoul** [comment]
yea i did a similiar implementation. closing the issue thanks.

**Comment by bchavez** [comment]
Hi @bonesoul,

Thanks for posting your issue. I'm glad you found an answer. Also, thanks @RodrigoRodriguesX10 for helping out with the answer for everyone. :+1: 

Rodrigo is correct. Bogus does not implement uniqueness. If you want uniqueness you'll have to write code to implement uniqueness that works best for you. More information about why Bogus doesn't have uniqueness check out see #251. The TLDR is *uniqueness* basically boils down to costly space and runtime complexity.

In your particular case, if you need unique numbers to source from, here's another way to do it:
```csharp
void Main()
{
   var f = new Faker();
   var range = Enumerable.Range(1,10000);
   var randomized = f.Random.Shuffle(range);
   var unique = randomized.Take(100);
   unique.Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/77706858-bfa54d80-6f80-11ea-85dd-98c997105eae.png)

Or take an iterative approach with a local variable which *drives* the uniqueness. The idea here is to pre-generate everything you need upfront, then shuffle:
```csharp
void Main()
{
   var f = new Faker();
   var phoneNumbers = new List<string>();
   var uniqueIndex = 1;
   while( uniqueIndex <= 9999 ){
      var phone = f.Random.ReplaceNumbers($"(###) ###-{uniqueIndex:0000}");
      phoneNumbers.Add(phone);
      uniqueIndex++;
   }
   phoneNumbers.Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/77707546-adc4aa00-6f82-11ea-854b-fdfdbfb7a535.png)

And of course, shuffling the unique sequence yields a unique set of phone numbers without needing to check a `HashSet`:
```csharp
   var randomUniquePhoneNumbers = f.Random.Shuffle(phoneNumbers);
   randomUniquePhoneNumbers.Dump();
```

![image](https://user-images.githubusercontent.com/478118/77707608-dc428500-6f82-11ea-96dd-6aa34c89580b.png)

I hope that helps!

Thanks,
Brian

**Comment by bonesoul** [comment]
thanks!

**Comment by ABIOLI-COM** [comment]
There's maybe a more flexible solution, as I explain here: https://github.com/bchavez/Bogus/issues/17#issuecomment-2539044242
