### ISSUE TITLE
Support for Kazakh locale

### ISSUE THREAD

**Issue by sdjnaik** [bchavez/Bogus#289]
Hi Team,

I am using Bogus library for fake data generation to support localization, was wondering if you have any roadmap for supporting 'kazakh' language.

**Comment by bchavez** [comment]
Hi @sdjnaik,

Thank you for posting your issue. We don't have any immediate plans to support 'kazakh' but please feel free to contribute your locale to the community.

First, we still get the bulk of our data from faker.js here: https://github.com/marak/Faker.js/

To get 'kazakh' supported, you'd want to create a PR to faker.js for the 'kazakh' locale.

Once your PR is accepted upstream, then let us know by re-opening this issue or creating a PR with the newly imported data. On our side, we pull down faker.js and re-import and re-bundle locales from faker.js as described here: https://github.com/bchavez/Bogus#rebundling-locales

You can find more information about creating locales here:
https://github.com/bchavez/Bogus/wiki/Creating-Locales

I hope that helps!

Thanks,
Brian
