### ISSUE TITLE
Hierarchy support?

### ISSUE THREAD

**Issue by stannynuytkens** [bchavez/Bogus#290]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |        29.0.2         |
| .NET Core?                   |         netstandard2.1        |
| .NET Full Framework?   |        no        |
| Windows OS?              |         Windows 10         |
| Linux OS?                    |                  |
| Visual Studio?              |          2019 (16.5.2)        |

### What locale are you using with Bogus?
Default? (OS is set to English US)

### What's the problem?
I'd like to generate two sets but the second set relies on data used from the
first set (parent/childid, datetime that slides, ..) How would I go about that?

### What possible solutions have you considered?
Manually loop

### Do you have sample code to show what you're trying to do?
Nope, just seeing if Bogus can deliver.. 😛 

_(Please be complete. Include any class models necessary to run your code.)_

**Comment by bchavez** [comment]
Hi Stanny,

There's no ***inherent*** hierarchy support. You'll have to define what that means for your POCOs and application which is most meaningful to you.

For example, here are two ways you could do the same thing, 1) an imperative solution using `Faker`, and 2) a declarative solution using `Faker<T>` as shown below. Given the following class hierarchy:

```csharp
public class Human
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public DateTime Birthday { get; set; }

   public int Age
   {
      get
      {
         var age = DateTime.Now.Year - this.Birthday.Year;
         if (Birthday.Date > DateTime.Now.AddYears(-age)) return age--;
         return age;
      }
   }
}

public class Parent : Human
{
   public List<Child> Children { get; set; }
}

public class Child : Human
{
   public Parent Parent { get; set; }
}
```

## 1. An imperative solution using `Faker` facade
```csharp
void Main()
{
   var f = new Faker();

   var parents = Enumerable.Range(0, 10)
                           .Select( _ => MakeParent(f))
                           .ToList();;
   parents.Dump();
}

public static Parent MakeParent(Faker f)
{
   var p = new Parent()
   {
      FirstName = f.Name.FirstName(),
      LastName = f.Name.LastName(),
      Birthday = f.Date.Past(50, DateTime.Now.AddYears(-20))
   };
   
   var childrenCount = f.Random.Number(1, 3);
   
   var children = f.Make(childrenCount, () => MakeChild(p, f)).ToList();
   
   p.Children = children;
   
   return p;
}
public static Child MakeChild(Parent p, Faker f)
{
   var c = new Child()
   {
      Parent = p,
      FirstName = f.Name.FirstName(),
      LastName = p.LastName,
      Birthday = RandomChildBirthday()
   };
   
   return c;

   DateTime RandomChildBirthday()
   {
      var childBearingBeginDate = p.Birthday.AddYears(18);
      var childBearingEndDate = DateTime.Now.AddYears(-18);

      var childBirthDate = f.Date.Between(childBearingBeginDate, childBearingEndDate);
      return childBirthDate;
   }
}
```
![image](https://user-images.githubusercontent.com/478118/79403561-1ed4fd00-7f44-11ea-93c8-941930fad0f3.png)


## 2. A delcaritive solution using `Faker<T>`
```csharp
void Main()
{
   var childFaker = new Faker<Child>();
   
   var parentFaker = new Faker<Parent>()
      .RuleFor(p => p.Birthday, f => f.Date.Past(50, DateTime.Now.AddYears(-20)))
      .RuleFor(p => p.FirstName, f => f.Name.FirstName())
      .RuleFor(p => p.LastName, f => f.Name.LastName())
      .RuleFor(p => p.Children, (f, p) => childFaker.MakeChildrenWithParent(p, f));
   
   var parents = parentFaker.Generate(10);
   parents.Dump();
}

public static class ExtensionsForFakerChild
{
   public static List<Child> MakeChildrenWithParent(this Faker<Child> childFaker, Parent p, Faker f)
   {
      var amount = f.Random.Number(1, 3);
      return f.Make(amount, _ => childFaker.MakeChildWithParent(p)).ToList();
   }
   
   public static Child MakeChildWithParent(this Faker<Child> childFaker, Parent p)
   {
      childFaker
         // parent of the child is p
         .RuleFor(c => c.Parent, _ => p) 
         
         // the child can have any first name.
         .RuleFor(c => c.FirstName, f => f.Name.FirstName())
         
         // the child takes last name of the parent.
         .RuleFor(c => c.LastName, _ => p.LastName)

         // child's birthday must be within appropate child bearing age of parent
         .RuleFor(c => c.Birthday, f => RandomChildBirthday(f));
         
      return childFaker.Generate();
         
      DateTime RandomChildBirthday(Faker f){
         var childBearingBeginDate = p.Birthday.AddYears(18);
         var childBearingEndDate = DateTime.Now.AddYears(-18);
         
         var childBirthDate = f.Date.Between(childBearingBeginDate, childBearingEndDate);
         return childBirthDate;
      }
   }
}
```
![image](https://user-images.githubusercontent.com/478118/79403035-8ab66600-7f42-11ea-9383-b958a63bc1e4.png)

Both solutions are roughly the same amount of code. As guidance, you'll want to use whatever solution you feel is easier to read and maintain. The choice is yours. :sunglasses: 

I hope that helps.

Thanks,
Brian

**Comment by stannynuytkens** [comment]
Thanks for the clear (and quick!) example Brian!
It was something I also had in mind but it's more clear now with the API involved.
Also I have a weak spot for fluent API libraries because of their declarative way of configuration. :wink:

**Comment by Devvox93** [comment]
The example @bchavez provided (or at least a link to it) should be added to the main Readme imo.
I've been searching for this for a while and I'm betting there are more people that want this.

Anyway, at least thanks for this clear example. I'm going for number 2 too :)

**Comment by bchavez** [comment]
Thanks, @Devvox93. I'll consider it,

Also, #295 is another good one too if you're in a situation with a circular/cyclic reference hierarchy. :sunglasses: :+1:

**Comment by Devvox93** [comment]
I have implemented a slightly different approach that matches the rest of my setup and is inspired by your previous solution (I return Faker<T> so that I can chain multiple extension methods).
I have rewritten it to match the case mentioned in this issue:
```csharp
public static Faker<Parent> WithChildren(this Faker<Parent> faker, short amount = 1, Action<Faker<Child>> childFakerAction = null)
{
	return faker
		.RuleFor(c => c.Children, (f, parent) => {
			var childFaker = Fakers.ChildFaker.WithParent(parent);
			childFakerAction?.Invoke(childFaker);
			return childFaker.Generate(amount);
		});
}

public static Faker<Child> WithParent(this Faker<Parent> faker, Child child)
{
	return faker
		.RuleFor(c => c.Parent, f => parent)
		.RuleFor(c => c.LastName, f => parent.LastName);
}
```

@bchavez Besides offering this alternative approach for future readers, I also wonder what extension you use to display the hierarchy (in your screenshots). It looks really neat! :slightly_smiling_face:

**Comment by bchavez** [comment]
Thanks a lot for posting your approach @Devvox93. I'm sure others will find it useful. :+1: 

The tool I'm using is **LINQPad**: https://www.linqpad.net - super useful for code explorations and trying things out without firing up a full-fledged project in the IDE.

When writing code in **LINQPad**, there is a built-in object extension called `.Dump()` that you can use on any object and it gets written to the results pane. eg:
![image](https://user-images.githubusercontent.com/478118/82760707-43758d80-9daa-11ea-8fb5-c2ffa23c3ace.png)
