### ISSUE TITLE
Is it possible to make Bogus use parameterful constructor without custom setup?

### ISSUE THREAD

**Issue by azsdaja** [bchavez/Bogus#291]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |    29.0.2     |
| .NET Core?                   |          3.1     |
| .NET Full Framework?   |                 |
| Windows OS?              |          10      |
| Linux OS?                    |                  |
| Visual Studio?              |       no, Rider        |

### What locale are you using with Bogus?
pl-pl
### What's the problem?
My class doesn't have a parameterless constructor (lets assume it has a single ctor with single `int` parameter). I want to be able to use Bogus like this: `var myObject = new Faker<MyClass().Generate();`.
### What possible solutions have you considered?
There is a blog post about using CustomInstantiator (https://putridparrot.com/blog/auto-generating-test-data-with-bogus/), but I think I shouldn't be forced to write additional code. If Bogus can discover and fill properties, why wouldn't it be able to discover constructor parameters?
### Do you have sample code to show what you're trying to do?
``` csharp
public class MyClass
{
public int MyInt{get; set;}
public MyClass(int arg)
{
MyInt= arg;
}
}
```

**Comment by bchavez** [comment]
[1]:https://www.nuget.org/packages/AutoBogus/
Hi Pawel,

Your easiest solution is to use [**AutoBogus**][1] by Nick Dodd. I believe **AutoBogus** supports this scenario out of the box:

```csharp
void Main()
{
   var x = AutoFaker.Generate<Foo>();
   x.Dump();
}

public class Foo
{
   public Foo(int arg){
      this.Arg = arg;
   }
   public int Arg {get;}
}
```
![image](https://user-images.githubusercontent.com/478118/79405241-b2a8c800-7f48-11ea-91ab-4e31f9e02630.png)

------

If you don't want to use **AutoBogus**, you can teach Bogus by writing a simple `MagicFaker<T>` utility faker class:

```csharp
void Main()
{
   var fooFaker = new MagicFaker<Foo>();
   
   var foo = fooFaker.Generate();
   
   foo.Dump();
}

public class Foo
{
   public Foo(int arg){
      this.Arg = arg;
   }
   public int Arg {get;}
}

public class MagicFaker<T> : Faker<T> where T : class
{
   public MagicFaker()
   {
      this.CustomInstantiator(f => ResolveConstructor(f));
   }
   
   private T ResolveConstructor(Faker f)
   {
      var constructor = typeof(T).GetConstructors().First();
      
      var pi = constructor.GetParameters();
      
      var liveParameters = new List<object>();
      
      foreach( var param in pi ){
         if( param.ParameterType == typeof(int))
         {
            liveParameters.Add(f.Random.Int(min: 0));
         }
         //etc.. for the parameters you want to support.
      }
      
      return Activator.CreateInstance(typeof(T), liveParameters.ToArray()) as T;
   }
}
```

I hope this helps. Ultimately, **Bogus** won't natively support the auto-discovery of constructors. Some reasons are:

* What do you do if there is more than one constructor? Which one do you pick?
* For a given parameter, how do we know which range of values are appropriate for your class? Maybe `0` to `int.MaxValue` is okay but a negative number is not.
* What about parameters that we do not know how to generate? `new Foo(Bar b)`?

I think the auto-discovery of constructors is too ambiguous for general use to make it the default.

I hope this helps.

Thanks,
Brian
