### ISSUE TITLE
Integration with VS 2019 Windows

### ISSUE THREAD

**Issue by wbadry** [bchavez/Bogus#292]
Hello,
Is Bogus premium integrated with VS2019 Windows? Thanks

**Comment by bchavez** [comment]
Hi Waleed,

Thank you for your question. Yes, Bogus Premium should work with Visual Studio 2019.

I tested **VS2019 16.5.2** on **Windows 7** and all seems well:

![image](https://user-images.githubusercontent.com/478118/79512825-20abc880-7ff7-11ea-8db5-74db888f749d.png)

![JPEGView_3780](https://user-images.githubusercontent.com/478118/79513050-c19a8380-7ff7-11ea-8009-377819a33cd0.png)

Also, I have updated the [**Bogus Premium Wiki** page][1] to include **Visual Studio 2019**. If you run into any issues, please let me know and I'll be happy to help.

Thanks again for your question and support.

Thanks,
Brian Chavez

[1]:https://github.com/bchavez/Bogus/wiki/Bogus-Premium

**Comment by bchavez** [comment]
Also, here is the **.csproj** file I used with **Visual Studio 2019**.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
     <PackageReference Include="Bogus" Version="29.0.2" />
     <PackageReference Include="Bogus.Tools.Analyzer" Version="29.0.2">
       <PrivateAssets>all</PrivateAssets>
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
     </PackageReference>
     <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
  </ItemGroup>

</Project>
```

**Comment by wbadry** [comment]
Thank you so much. It would be great if ECG and PPG fake stream could be added to healthcare.

**Comment by bchavez** [comment]
Hi @wbadry , could you provide some links and resources for ECG and PPGs? I'm not familiar with these terms. I would like to learn more about the topics you had in mind for healthcare.

Thanks,
Brian

**Comment by wbadry** [comment]
Sure @bchavez 
Something like this:
https://github.com/peterhcharlton/RRest/tree/master/RRest_v2.0/Data_Import_Scripts/RRest_synth
