### ISSUE TITLE
Chapter.Theme to be in Chapter's Study.Themes

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#295]
**Context**

I have the following Fakers:

      Faker<Theme> themes = new Faker<Theme>();

      Faker<Chapter> chapters = new Faker<Chapter>()
        .RuleFor(x => x.Theme, x => themes.Genererate(1));

      Faker<Study> studies = new Faker<Study>()
        .RuleFor(x => x.Chapters, x => chapters.Generate(4))
        .RuleFor(x => x.Themes, x => themes.Generate(2));

      var result = studies.Generate(20);

I need the Theme in a Chapter to be one of the Themes in the Chapter's Study.

    public class Study {
       public ICollection<Chapter> Chapters { get; set; }
       public ICollection<Theme> Themes { get; set; }
    }

    public class Theme {
       public Study Study { get; set; }
       public ICollection<Chapter> Chapters { get; set; }
    }

    public class Chapter {
       public Study Study { get; set; }
       public Theme Theme { get; set; }
    }

Can this be done?

**Comment by bchavez** [comment]
@mdmoura Sure.

```csharp
var chapterId = 0;
var chapterFaker = new Faker<Chapter>()
   .RuleFor(c => c.Name, f => $"Chapter {chapterId++}");

var themeId = 0;
var themeFaker = new Faker<Theme>()
   .RuleFor(t => t.Name, f => $"Theme {themeId++}")
   .RuleFor(t => t.Chapters, f => chapterFaker.GenerateBetween(1, 5))
   .FinishWith( (f, t)=>{
      t.Chapters.ForEach( c => c.Theme = t);
   });

var studyId = 0;
var studyFaker = new Faker<Study>()
  .RuleFor(s => s.Name, f => $"Study {studyId++}")
  .RuleFor(s => s.Themes, f => themeFaker.GenerateBetween(1, 3))
  .RuleFor(s => s.Chapters, (f, s) => s.Themes.SelectMany(t => t.Chapters).ToList())
  .FinishWith((f, s) => {
      s.Chapters.ForEach( c => c.Study = s);
      s.Themes.ForEach( t => t.Study = s);
  });
  
studyFaker.Generate(1).Dump();
```
* Study 0 (6 chapters, 3 themes)
  * Theme 0
     * Chapter 0
     * Chapter 1
  * Theme 1
     * Chapter 2
  * Theme 2
     * Chapter 3
     * Chapter 4
     * Chapter 5

![image](https://user-images.githubusercontent.com/478118/82133376-48ca4b00-97a0-11ea-9c9a-cdec7a3f85b5.png)

Although, I probably wouldn't use `Faker<T>` because the code is complicated and hard to reason about. To be honest, it took me a few minutes to try to understand what you were trying to do. I think a more imperative `Faker` facade approach would be better for creating this object graph.

Additionally, I probably wouldn't model my objects with a 3-way bi-directional circular dependency; but that's just me.

By the way, you can get the `Collection.ForEach(x => x..)` extension method in [`Z.ExtensionMethods`](https://www.nuget.org/packages/Z.ExtensionMethods.WithTwoNamespace/) NuGet package.

I hope that helps.
-Brian

**Comment by bchavez** [comment]
And for completeness, here is the imperative `Faker` facade approach:
```csharp
void Main()
{
   var f = new Faker();
   
   var study = CreateStudy(f);
   var studies = new List<Study>();
   studies.Add(study);
   studies.Dump();
}

static int studyId = 0;
public Study CreateStudy(Faker f)
{
   var study = new Study
   {
      Name = $"Study {studyId++}"
   };
   
   var themeCount = f.Random.Number(1,3);
   study.Themes = f.Make(themeCount, () => CreateTheme(f, study));                            
   
   study.Chapters = study.Themes
                         .SelectMany( t => t.Chapters)
                         .ToList();
                            
   return study;
}

static int themeId = 0;
public Theme CreateTheme(Faker f, Study s){
   var chapterCount = f.Random.Number(1, 5);
   var theme = new Theme()
   {
      Name = $"Theme {themeId++}",
      Study = s
   };

   theme.Chapters = f.Make(chapterCount, () => CreateChapter(s, theme));
   return theme;
}

static int chapterId = 0;
public Chapter CreateChapter(Study s, Theme t)
{
   return new Chapter
   {
      Name = $"Chapter {chapterId++}",
      Theme = t,
      Study = s
   };
}
```
* Study 0 (3 themes, 5 chapters)
  * Theme 0
    * Chapter 0
  * Theme 1
    * Chapter 1
  * Theme 2
    * Chapter 2
    * Chapter 3
    * Chapter 4

![image](https://user-images.githubusercontent.com/478118/82133900-06a40800-97a6-11ea-9450-993fd6c6889c.png)

Hope that helps,
Brian

**Comment by mdmoura** [comment]
>> Additionally, I probably wouldn't model my objects with a 3-way bi-directional circular dependency; but that's just me.

Maybe you're right. But the reason why I did this is because a Study can have Themes or not but it will always have Chapters. But I am also thinking in other ways to do this.

Thank you for all the code you posted it ... It helped a lot.
