### ISSUE TITLE
New index start on each object generated.

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#296]
I have the following code:

          Faker<Chapter> chapters = new Faker<Chapter>()
            .RuleFor(x => x.Position, x => (Byte)x.IndexVariable++);

          Faker<Theme> themes = new Faker<Theme>()
             .RuleFor(x => x.Chapters, x => chapters.Generate(8));

I need that for each Theme the position of its Chapters to start in 1.

I tried IndexVariable and IndexFaker but I wasn't able to do this.

Could such an Index be added?

**Comment by bchavez** [comment]
Hi @mdmoura,

Sure. Continuing from our last discussion #295, the easiest way is to maintain "state" outside of `Faker<T>` as shown below:

-----
### Option 1: Variable state outside `Faker<T>`
When you maintain state outside `Faker<T>` this option is by far the easiest:
```csharp
void Main()
{
   var chapterId = 1; // <--- INIT STATE HERE
   var chapterFaker = new Faker<Chapter>()
      .RuleFor(c => c.Name, f => $"Chapter {chapterId++}");

   var themeId = 0;
   var themeFaker = new Faker<Theme>()
      .RuleFor(t => t.Name, f => $"Theme {themeId++}")
      .RuleFor(t => t.Chapters, f => chapterFaker.GenerateBetween(1, 5))
      .FinishWith((f, t) =>
      {
         t.Chapters.ForEach(c => c.Theme = t);
         chapterId = 1; // <--- RESET CHAPTER STATE HERE
      });

   themeFaker.Generate(1).Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/82763603-dbc93d80-9dbd-11ea-9d11-e0fa4c5cb661.png)

 -----
### Option 2: Access `IFakerTHub` internal variables
Using the following extension method:
```csharp
public static class ExtensionsForFakerT
{
   public static void SetIndexVeriable<T>(this Faker<T> faker, int val) where T : class
   {
      var hub = faker as Bogus.IFakerTInternal;
      hub.FakerHub.IndexVariable = val;
   }
}
```
The second option probes into `IFakerTInternal` to get access to the `Faker` facade where we can manually set the `IndexVariable` to some specific state.
```csharp
void Main()
{
   var chapterFaker = new Faker<Chapter>()
      .RuleFor(c => c.Name, f => $"Chapter {++f.IndexVariable}");

   var themeId = 0;
   var themeFaker = new Faker<Theme>()
      .RuleFor(t => t.Name, f => $"Theme {themeId++}")
      .RuleFor(t => t.Chapters, f => chapterFaker.GenerateBetween(1, 5))
      .FinishWith((f, t) =>
      {
         t.Chapters.ForEach(c => c.Theme = t);
         chapterFaker.ResetIndexVeriable(0); // <--- RESET CHAPTER STATE HERE
      });

   themeFaker.Generate(2).Dump();
}
```

![image](https://user-images.githubusercontent.com/478118/82763566-94db4800-9dbd-11ea-83e1-da382b5be17c.png)

----

The choice is yours.

Thanks,
Brian
