### ISSUE TITLE
Generic rules for interfaces

### ISSUE THREAD

**Issue by GrantHoffman** [bchavez/Bogus#297]
Hey I'm trying to figure out how I can reuse rules for interfaces for my fakers.
Lets say I have this structure

    public interface IHasHeader
    {
       int Id { get; set; }
       string Code { get; set; }
       string Description { get; set; }
    }

    public class Divisions: IHasHeader
    {
           //...
    }

    public class Companies: IHasHeader
    {
       //...
    }

Is there a way that I can add rules for IHasHeader so that they are applied by default whenever I create a Faker<T> where T : IHasHeader

**Comment by GrantHoffman** [comment]
I'm trying to create a factory for it, but I keep running into issues 

        public class FakerFactory
        {
            protected List<Action<StatefulFaker<object>>> _rules = new List<Action<StatefulFaker<object>>>();

            public void AddRuleFor<T, TProperty>(Expression<Func<T, TProperty>> property, Func<Faker, T, TProperty> setter)
                where T : class
            {
                this._rules.Add(f => f.RuleFor(property, setter))
            }

            public StatefulFaker<T> GetStatefulFaker<T>()
                where T : class
            {
                var faker = new StatefulFaker<T>();
                this.ApplyRules(faker);
                return faker;
            }

            private void ApplyRules<T>(StatefulFaker<T> faker) where T : class
            {
                this._rules.ForEach(rule => rule(faker));
            }
        }

**Comment by bchavez** [comment]
Hi @GrantHoffman, sure. There are a few ways. Given the following models:

```csharp
public interface IHasHeader
{
   int Id { get; set; }
   string Code { get; set; }
   string Description { get; set; }
}
public class Divisions : IHasHeader
{
   public int Id { get; set; }
   public string Code { get; set; }
   public string Description { get; set; }
}
public class Companies : IHasHeader
{
   public int Id { get; set; }
   public string Code { get; set; }
   public string Description { get; set; }
}
```

## Option 1: Extension methods
My preferred way:
```csharp
void Main()
{
   var divisionFaker = new Faker<Divisions>()
         .WithDefaultRules();

   var companyFaker = new Faker<Companies>()
         .WithDefaultRules();
         
   divisionFaker.Generate().Dump();
   companyFaker.Generate().Dump();
}
```
```csharp
public static class RulesForIHasHeader
{
   public static Faker<T> WithDefaultRules<T>(this Faker<T> faker) where T : class, IHasHeader
   {
      faker.RuleFor(i => i.Id, f => f.IndexFaker++);
      faker.RuleFor(i => i.Code, f => f.Random.Replace("####"));
      faker.RuleFor(i => i.Description, f => "default description");
      return faker;
   }
}
```
![image](https://user-images.githubusercontent.com/478118/83318896-fc462d00-a1ed-11ea-845e-4a2361a20083.png)

## Option 2: `Faker<T>` inheritance
```csharp
void Main()
{
   var divisionFaker = new HeaderFaker<Divisions>();

   var companyFaker = new HeaderFaker<Companies>();

   divisionFaker.Generate().Dump();
   companyFaker.Generate().Dump();
}
```
```csharp
public class HeaderFaker<T> : Faker<T> where T : class, IHasHeader
{
   public HeaderFaker()
   {
      this.RuleFor(i => i.Id, f => f.IndexFaker++);
      this.RuleFor(i => i.Code, f => f.Random.Replace("####"));
      this.RuleFor(i => i.Description, f => "default description");
   }
}
```

![image](https://user-images.githubusercontent.com/478118/83318971-c8b7d280-a1ee-11ea-9919-17bb8d342616.png)

I hope that helps.

Thanks,
Brian

**Comment by GrantHoffman** [comment]
@bchavez  Thanks, that will work when the types are known ahead of time but I'm still not sure of how to implement this with a factory I'll open another issue and link it here
