### ISSUE TITLE
Generically Apply Rule to Faker

### ISSUE THREAD

**Issue by GrantHoffman** [bchavez/Bogus#299]
I'm trying to create a MockDataGenerator which contains a repository of rules.  I would like the repository of rules to operate the child interfaces in which a class derrives.

    using RuleSet = System.Collections.Generic.List<System.Action<object>>;
    public class MockDataGenerator
    {
        Dictionary<Type, object> _generatorMap = new Dictionary<Type, object>();
        Dictionary<Type, RuleSet> _ruleMap = new Dictionary<Type, RuleSet>();

        public T Generate<T>()
            where T : class
        {
            if (false == this._generatorMap.TryGetValue(typeof(T), out var fakerObj))
            {
                fakerObj = new StatefulFaker<T>();
                var faker = (fakerObj as StatefulFaker<T>);
                this.ApplyRules<T>(faker);
                this._generatorMap.Add(typeof(T), faker);
            }

            return (fakerObj as StatefulFaker<T>).Generate();
        }

        public void AddGlobalRule<T, TProperty>(Expression<Func<T, TProperty>> property, Func<Faker, TProperty> rule)
            where T: class
        {
            var ruleType = typeof(T);
            if (false == this._ruleMap.ContainsKey(ruleType))
            {
                this._ruleMap.Add(ruleType, new RuleSet());
            }

            var ruleset = this._ruleMap.Get(ruleType);

            var propertyName = ((MemberExpression)property.Body).Member.Name;

            Action<object> applyRule = o => {
                //This Fails because Faker is of the We're not a faker of T were a Faker<TSuper> where TSuper: T
                //var faker = o as StatefulFaker<T>;
                //faker.RuleFor(property, rule);
            };

            ruleset.Add(applyRule);
        }

        #region Protected Methods

        protected Type[] GetDerrivedTypes(Type type)
        {
            //TODO: this is just a sample but it should recursively check base types and interfaces
            return type.GetInterfaces();
        }

        protected void ApplyRules<T>(StatefulFaker<T> faker) where T : class
        {
            var typeToFake = typeof(T);
            var derrivedTypes = this.GetDerrivedTypes(typeToFake);
            foreach (var derrivedType in derrivedTypes)
            {
                if (false == this._ruleMap.TryGetValue(derrivedType, out var ruleSet))
                {
                    continue;
                }

                this.ApplyRuleSet(faker, ruleSet);
            }
        }

        private void ApplyRuleSet<T>(StatefulFaker<T> faker, RuleSet ruleSet) where T : class
        {
            foreach(var applyRule in ruleSet)
            {
                applyRule(faker);
            }
        }

        #endregion
    }

My Issue is that I want to apply a rule generically for a derriving class:

            Action<object> applyRule = o => {
                //This Fails because Faker is of the We're not a faker of T were a Faker<TSuper> where TSuper: T
                //var faker = o as StatefulFaker<T>;
                //faker.RuleFor(property, rule);
            };

Is there a way I can apply a rule to a faker generically? with out having the typed arugment at runtime?

**Comment by bchavez** [comment]
Hi Grant,

There is a `string` overload that can accept a property name:
```csharp
Action<object> applyRule = o =>
{
   var faker = o as StatefulFaker<T>;
   faker.RuleFor(propertyName, rule);
};
```

Also, I did not see any issue or compiler error with your original code. Your original code below seemed to compile fine. However, I did not check runtime - mostly because I'm not fimilar with your `MockDataGenerator`.
```csharp
Action<object> applyRule = o => {
    var faker = o as StatefulFaker<T>;
    faker.RuleFor(property, rule);
};
```

---

Also, I had a random thought just now. You could also store more rules in `Faker<T>` than properties that actually exist by doing the following:
```csharp
void Main()
{
   var fooFaker = new RelaxedFaker<Foo>()
            .RuleFor("Bar", f => f.Random.Word())
            .RuleFor("Car", f => f.Random.Int())
            .RuleFor("Tar", f => f.Random.Bool())
            .RuleFor("Jar", f => f.Random.Float());
            
   fooFaker.Generate().Dump();
}

public class Foo
{
   public string Bar {get;set;}
   public int Car {get;set;}
}

public class RelaxedFaker<T> : Faker<T> where T : class
{
   protected override void EnsureMemberExists(string propNameOrField, string exceptionMessage)
   {
      return;
   }
}
```
![image](https://user-images.githubusercontent.com/478118/83950610-e7b2f780-a7e0-11ea-93f1-094bb6db48b4.png)

-----

Finally, you might want to consider checking out **AutoBogus.Conventions** for more inspiration. https://github.com/nickdodd79/AutoBogus

There might be some parallels with **AutoBogus.Conventions** that you might find useful.

Thanks,
Brian

Re: #297
