### ISSUE TITLE
Feature: Global Faker rules per type

### ISSUE THREAD

**Issue by weitzhandler** [bchavez/Bogus#304]
**Context**

Currently, the `RuleFor` work against specific property.
Ideally, I'd like to be able to set rules for multiple properties by type. This can potentially divide into several categories:

- `RuleFor`/`RuleForType<T>(value: t)` - applies to any property of type `T`.
- `RuleForCollection<T>(value: t, maxCount: 5)` - applies to any collection item of type `T`
- `RuleForCollection(maxCount: 5)` any collection will generate max 5 items
- `Ignore<T>()` - ignores any property of type `T`
- And so on

I'm willing to contribute on this.
But this first need some thoughtful decision making and design.

**Comment by bchavez** [comment]
Regarding rules for collections, see issue #55. The TL;DR; is that we get into a tricky situation when most of `Faker<T>` rules are contextually meant to operate on a single instance of `T`, ie: `.RuleFor`, `.RuleForType`, `.CustomInstantiator`.

When you generate a collection of objects, the context is no longer a single `T`, but a group of `T[]`. Having operative collection APIs that operate on a "group of" objects of type `T` on `Faker<T>` introduces a code smell I'm not comfortable with. Check #55 for the details.

The way you potentially might want to get around this is by doing the following:
```csharp
void Main()
{
   var fakerOfThings = new Faker<Thing>()
      .RuleForType(typeof(string), f => f.Random.Word())
      .RuleForType(typeof(int), f => f.Random.Int());

   var collectionOfThings = fakerOfThings.Generate(10);
   
   collectionOfThings.Apply((f, t) => t.ValueC = f.Random.Number(1, 10));
   
   collectionOfThings.Dump();
}

public class Thing
{
   public string Value1;
   public string Value2;
   public string Value3;
   public int ValueA;
   public int ValueB;
   public int ValueC;
}

public static class ExtensionsForFakerCollections
{
   private static Faker f = new Faker();
   
   public static void Apply<T>(this List<T> group, Action<Faker, T> setter) where T : class
   {
      foreach( var t in group ){
         setter(f, t);
      }
   }
}
```
![image](https://user-images.githubusercontent.com/478118/85214564-6780ac00-b321-11ea-83bd-df95c5bd6d39.png)

-------

My suggestion for most of these API operations is to create extension methods over Bogus that fit your API style and needs.

Extension methods for collections like "the first item in the collection should always have ValueC = 0" would be to write an extension method for collections you want to specify rules for. ie: `collectionOfThings.WithFirstItemValueCEqualToZero()`.

When the extension methods over Bogus become unwieldy, then I start looking at how we can add some primitive operations to Bogus core to alleviate some of the heavy lifting.

**Comment by weitzhandler** [comment]
What does the `Faker<T>` generate for this:

```c#
public class Person
{
  public List<Phone> { get; set; }
}
```

**Comment by bchavez** [comment]
By default, `Faker<Person>` does nothing with the `Phones` property. No Rule = No Data. In this case, `Phones = null` just as `new Person()` would do.

`Faker<T>` only populates a property if it has a rule. No surprises. :sunglasses:

**Comment by weitzhandler** [comment]
Oh I see now. I guess I miss understood what "unstrict" means. I guess I now understand the purpose of AutoBogus.

**Comment by weitzhandler** [comment]
Oh I see now. I guess I miss understood what "unstrict" means. I guess I now understand the purpose of AutoBogus.
Thanks for your intense help!
