### ISSUE TITLE
Some user agents are invalid according to System.Net.Http

### ISSUE THREAD

**Issue by Trolldemorted** [bchavez/Bogus#307]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |  29.0.2    |
| .NET Core?                   | netcoreapp3.1 |

### What locale are you using with Bogus?
`de`

### What is the expected behavior?
Everything returned by `.Internet.UserAgent` is a valid user agent which we can use with `HttpClient`.

### What is the actual behavior?
This code sometimes throws:
```c#
var request = new HttpRequestMessage(HttpMethod.Post, url);
request.Headers.Add("User-Agent", new Faker("de").Internet.UserAgent());
```
```
The format of value '(X11; Linux i686 AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/20.0.894.0 Safari/537.0.2' is invalid. (System.FormatException)
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
```

**Comment by bchavez** [comment]
Hi @Trolldemorted, thank you for reporting. Indeed, this is a bug in the **faker.js** version too.

The formatting issue is fixed in **Bogus** `v30.0.1-beta-3`: https://www.nuget.org/packages/Bogus/30.0.1-beta-3

Let me know how it goes.

Thanks,
Brian
