### ISSUE TITLE
How do you get a single random word.

### ISSUE THREAD

**Issue by acrov** [bchavez/Bogus#308]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |  29.0.2               |
| .NET Core?                   |     2.1            |
| .NET Full Framework?   |                 |
| Windows OS?              |          10        |
| Linux OS?                    |                  |
| Visual Studio?              |   Community 16.6.2               |

### What locale are you using with Bogus?
EN GB

### What's the problem?
I can't see how to generate a single word. 

### What possible solutions have you considered?
 If I use Random.Word() I get phrases as well.  If I use Random.String types I don;t get real words.  I just want one word.

### Do you have sample code to show what you're trying to do?

_(Please be complete. Include any class models necessary to run your code.)_

**Comment by bchavez** [comment]
Hello @acrov,

![image](https://user-images.githubusercontent.com/478118/86299571-76831c00-bbb5-11ea-92fe-fae183e0e332.png)

`Randomizer.Word()` returns a word ***or phrase*** in English.

If you want a word without any spaces, I think your best bet is `.Lorem.Word()`.

We could do a little better on naming here and possibly rename `Randomizer.Word()` to `Randomizer.WordOrPhrase()`.

**Comment by acrov** [comment]
Thanks for the quick response Brian. Very helpful.
