### ISSUE TITLE
Generate child entities with one culture each

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#31]
Hello,

I am trying to generate localized data on an application so I have:

          Faker<EbookI18N> ebookI18Ns = new Faker<EbookI18N>()
            .RuleFor(x => x.LanguageCode, y => "en")
            .RuleFor(x => x.Description, y => y.Lorem.Paragraphs(1))
            .RuleFor(x => x.Title, y => y.Lorem.Sentence(4));

          List<Ebook> ebooks = new Faker<Ebook>()
            .RuleFor(x => x.Id, () => 0)            
            .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(2))
            .Generate(8).ToList();

The question is on the following line on ebook faker:

            .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(2))

How can I create two ebookI18Ns with one having LanguageCode="en" and the other with LanguageCode="pt" instead of the constant "en" value I have on ebookI18Ns?

The first thing I though was passing values to the Generate method. Something like:

            .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(2, new { LanguageCode = "something" }));

Any ideas?

Thank You,
Miguel

**Comment by bchavez** [comment]
Ah, I think this should be easier with the new `RuleSet` API I recently implemented but not yet released here: https://github.com/bchavez/Bogus/commit/42cff0efa7c10c36aa0e36cacd4accbbef139f2d

Basically, it would look like:
```
Faker<EbookI18N> ebookI18Ns = new Faker<EbookI18N>()
    .RuleFor(x => x.LanguageCode, y => "en")
    .RuleFor(x => x.Description, y => y.Lorem.Paragraphs(1))
    .RuleFor(x => x.Title, y => y.Lorem.Sentence(4))
    .RuleSet("ptRuleSet", set =>
        {
            set.RuleFor(x => x.LanguageCode, () => "pt");
        });

List<Ebook> ebooks = new Faker<Ebook>()
    .RuleFor(x => x.Id, () => 0)
    .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(1).Concat(ebookI18Ns.Generate(1, ruleSets:"default,ptRuleSet")))
    .Generate(8).ToList();
```

**Comment by mdmoura** [comment]
What if it would be necessary 20 languages? It would be necessary 20 rulesets? I think there might be a better way no?

**Comment by bchavez** [comment]
If you don't want to use `RuleSet`, you'd probably need to write a rule that selects out of 20.

```
.RuleFor(x => x.LanguageCode, y => y.PickRandom("en","br", "pt", .....) )
```
or, have a variable `LANG_CODE`:
```
var LANG_CODE = string.Empty;
Faker<EbookI18N> ebookI18Ns = new Faker<EbookI18N>()
    .RuleFor(x => x.LanguageCode, y => LANG_CODE)
    .RuleFor(x => x.Description, y => y.Lorem.Paragraphs(1))
    .RuleFor(x => x.Title, y => y.Lorem.Sentence(4));

List<Ebook> ebooks = new Faker<Ebook>()
    .RuleFor(x => x.Id, () => 0)
    .RuleFor(x => x.EbookI18Ns, () =>
        {
            LANG_CODE = "en";
            var en = ebookI18Ns.Generate(1).ToList();
            
            LANG_CODE = "pt";
            var pt = ebookI18Ns.Generate(1).ToList();
            return en.Concat(pt);
        })
    .Generate(8).ToList();
```

:art: :dash: [**Marshmello - CoLoUR**](https://www.youtube.com/watch?v=6UhNJC8OyVA)

**Comment by mdmoura** [comment]
I can't pick random because I need to generate one of each. About the LangCode why not letting ebook faker pass as a parameter in generate to ebooki18n faker which would use it. Does not make sense to you that a parent faker could adjust how a child faker behaves? I think it might be useful in many ways.

**Comment by bchavez** [comment]
Well, I think it makes sense to have parent control child fakers... If you need more control, I would suggest deriving from `Faker<T>` because I still think there are many options you can use without explicit **Bogus** support for passing parameters. In fact, the following example is probably the better way and more maintainable to do what you're looking for:

```
public class EbookI18NFaker : Faker<EbookI18N>
{
    public EbookI18NFaker() : base(locale:"en", binder: null)
    {
        RuleFor(x => x.LanguageCode, y => "en");
        RuleFor(x => x.Description, y => y.Lorem.Paragraphs(1));
        RuleFor(x => x.Title, y => y.Lorem.Sentence(4));
    }

    public IEnumerable<EbookI18N> GenerateSequence( params string[] langCodes)
    {
        return langCodes.Select(code =>
            {
                var ebook = this.Generate(1).First();
                ebook.LanguageCode = code;
                return ebook;
            });
    }
}
```
Use like:
```
EbookI18NFaker ebookI18Ns = new EbookI18NFaker();

List<Ebook> ebooks = new Faker<Ebook>()
    .RuleFor(x => x.Id, () => 0)
    .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.GenerateSequence("en", "pt"))
    .Generate(8).ToList();
```

**Comment by mdmoura** [comment]
I am using the following (it seems simpler):

        List<String> _languages = new List<String> { "en", "pt" };

        Faker<EbookI18N> ebookI18Ns = new Faker<EbookI18N>()
          .RuleFor(x => x.LanguageCode, y => _languages[y.UniqueIndex % _languages.Count])
          .RuleFor(x => x.Description, y => y.Lorem.Paragraphs(1))
          .RuleFor(x => x.Title, y => y.Lorem.Sentence(4));

        List<Ebook> ebooks = new Faker<Ebook>()
          .RuleFor(x => x.Id, () => 0)
          .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(_languages.Count).ToList())
          .Generate(8 * _languages.Count).ToList();

What do you think?

Never the less I think passing values from the parent faker to child ones would be a nice feature.
