### ISSUE TITLE
Is there a way for PickRandom to return null when collection count is 0?

### ISSUE THREAD

**Issue by uchagani** [bchavez/Bogus#310]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |   29.02     |
| .NET Core?                   |   3.1.202   |
| Windows OS?              |    10          |
| Visual Studio?              |     2019     |

### What locale are you using with Bogus?
Default (US?)

### What's the problem?
`PickRandom` method throws an `ArgumentOutOfRangeException` when collection has a 0 count.  Some of my properties are dependent on some API call or other dependency that may return a collection with 0 count.

### What possible solutions have you considered?
I tried making the properties nullable hoping that `PickRandom` would return `null` but that didn't work.  Open to any other suggestions.

### Do you have sample code to show what you're trying to do?

```
public class Hobby
{
	public int Id { get; set; }
	public string Text { get; set; }
}

public class User
{
	public int Id { get; set; }
	public string Name { get; set; }
	public Hobby? Hobby { get; set; }
}

public class UserFactory
{
	private readonly Faker<User> user;
	
	public User()
	{
		user= new Faker<User>()
			.RuleFor(u => u.Id, f => 1)
			.RuleFor(u => u.Name, f => f.Name.FirstName)
			.RuleFor(u => u.Hobby, f => f.PickRandom(new List<Hobby>()));
                        // Assume Hobby is coming from some data source that can return 0 count
	}
}
```

**Comment by bchavez** [comment]
Hi @uchagani,

Thank you for posting your question. I really appreciate it.

You can augment the `Faker f => f` object with a C# extension method `.PickRandomWithDefault()` to work around your issue of `.PickRandom()` throwing an exception.

Here's an example:
```csharp
void Main()
{
   var userFaker = new Faker<User>()
            .RuleFor(u => u.Id, f => 1)
            .RuleFor(u => u.Name, f => f.Name.FirstName())
            .RuleFor(u => u.Hobby, f => f.PickRandomWithDefault(new List<Hobby>()));
            
   userFaker.Generate(5).Dump();
}

public static class ExtensionsForFaker
{
   public static T PickRandomWithDefault<T>(this Faker f, IEnumerable<T> items, T defaultValue = default)
           where T : class
   {
      if( items.Any() ) return f.PickRandom(items);
      return defaultValue;
   }   
}
```
```csharp
public class Hobby
{
   public int Id { get; set; }
   public string Text { get; set; }
}
public class User
{
   public int Id { get; set; }
   public string Name { get; set; }
   public Hobby Hobby { get; set; }
}
```
![image](https://user-images.githubusercontent.com/478118/86853938-5ac3be00-c06c-11ea-919e-8258a6133ed8.png)

Let me know if you find the solution acceptable.

Thanks,
Brian
