### ISSUE TITLE
Add rules at runtime based on user input

### ISSUE THREAD

**Issue by uchagani** [bchavez/Bogus#311]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |   29.02     |
| .NET Core?                   |   3.1.202   |
| Windows OS?              |    10          |
| Visual Studio?              |     2019     |

### What locale are you using with Bogus?
Default (US?)

### What's the problem?
I'm trying to add rules at runtime based on user input.  I have a `Dictionary<string, object> overrides` where the `key` is the property name i want to create a rule for and `value` is the rule.  I'm using [fast-member](https://github.com/mgravell/fast-member/) to dynamically get at the property but running into an issue when setting the rule.

### What possible solutions have you considered?
I could generate the object then set the overrides but if there are other rules that depend on one of the override properties I'm not sure how to get those to run.  For example, if I have a `Car` model that has properties `Make`, `Model`, and `Trim` and I want to dynamically override `Model` based on user input, but `Trim` is dependent on the `Model` value.

### Do you have sample code to show what you're trying to do?

Usage:

```
var modelValue = "F-150"; //this comes from the user

var carOverrides = new Dictionary<string, object>()
{
    { "Model", modelValue }
};

var car = new CarFactory().Build(carOverrides);
```

Model:

```
public class Car
{
    public string Make { get; set; }
    public Model Model { get; set; }
    public Trim Trim { get; set; }
}
```

Factory:

```
public class CarFactory
{
	private readonly Faker<Car> carData;
	private readonly ModelProvider modelProvider;
	private readonly TrimProvider trimProvider;
	
	public CarFactory(IServiceProvider serviceProvider)
	{
		modelProvider = serviceProvider.GetService<ModelProvider>();
		trimProvider = serviceProvider.GetService<TrimProvider>();

		carData = new Faker<Car>()
			.RuleFor(car => car.Make, f => f.Vehicle.Manufacturer())
			.RuleFor(car => car.Model, (f, c) => modelProvider.GetModelByMake(c.Make));
			.RuleFor(car => car.Trim, (f, c) => trimProvider.GetTrimByModel(c.Model));
	}
	
	public Car Build(Dictionary<string, object> overrides)
	{
		var accessor = TypeAccessor.Create(typeof(Car));
		foreach (var kvp in overrides)
		{
			switch (kvp.Key)
			{
				case "Model":
					var model = modelProvider.GetModelById((int)kvp.Value);
					carData.RuleFor(car => car.Model, f => model);
					break;
                                default:
                                      carData.RuleFor(car => accessor[car, kvp.key], f => kvp.value) /// looking for a way to do this
			}

		}

		return carData.Generate();
	}
}
```

**Comment by uchagani** [comment]
I guess maybe the better question is, how would I generate `Expression<Func<T, TProperty>>` dynamically with the `TProperty` coming from a string.

**Comment by uchagani** [comment]
My first example was a brain fart, i added a `default` case to the switch statement that explains what i'm trying to do

**Comment by uchagani** [comment]
Taking fast-member out of the picture and just using plain reflection, I'm unable to get this to work either:

`carData.RuleFor(car => car.GetType().GetProperty(kvp.key), f => kvp.Value);`

**Comment by bchavez** [comment]
Hi @uchagani ,

The following seems to work:
```csharp
void Main()
{
   var modelValue = "F-150"; //this comes from the user

   var carOverrides = new Dictionary<string, object>()
      {
          {"Model", modelValue},
          {"Year", 1997}
      };
      
   var modelProvider = new ModelProvider();
   var trimProvider = new TrimProvider();

   var car = new CarFactory(modelProvider, trimProvider)
                     .Build(carOverrides);
   
   car.Dump();
}
```
```csharp
public class CarFactory
{
   private readonly Faker<Car> carFaker;
   private readonly ModelProvider modelProvider;
   private readonly TrimProvider trimProvider;

   public CarFactory(ModelProvider m, TrimProvider t)
   {
      modelProvider = m;
      trimProvider = t;

      carFaker = new Faker<Car>()
         .RuleFor(c => c.Make, f => f.Vehicle.Manufacturer());
   }

   public Car Build(Dictionary<string, object> overrides)
   {
      var accessor = TypeAccessor.Create(typeof(Car));
      
      foreach (var kvp in overrides)
      {
         switch (kvp.Value)
         {
            case int modelId when kvp.Key == "Id":
               var modelById = modelProvider.GetModelById(modelId);
               carFaker.RuleFor(c => c.Model, f => modelById);
               carFaker.RuleFor(c => c.Trim, (f, c) => trimProvider.GetTrimByModel(c.Model));
               break;
            case string modelName when kvp.Key == "Model":
               var modelByName = modelProvider.GetModelByMake(modelName);
               carFaker.RuleFor(c => c.Model, f => modelByName);
               carFaker.RuleFor(c => c.Trim, (f, c) => trimProvider.GetTrimByModel(c.Model));
               break;
            default:
               carFaker.RuleFor(kvp.Key, f => kvp.Value);
               break;
			}
      }

      return carFaker.Generate();
   }
}
```
```csharp
public class Car
{
   public string Make { get; set; }
   public int Year {get;set;}
   public Model Model { get; set; }
   public Trim Trim { get; set; }
}
public class Model
{
   public string Text{get;set;}
}
public class ModelProvider
{
   public Model GetModelByMake(string make)
   {
      return new Model { Text = $"Model '{make}'"};
   }
   public Model GetModelById(int i)
   {
      return new Model { Text = $"Model by ID '{i}'"};
   }
}
public class Trim
{
   public string Text{get;set;}
}
public class TrimProvider
{
   public Trim GetTrimByModel(Model m)
   {
      return new Trim { Text = $"Trim for '{m.Text}'"};
   }
}
```

![image](https://user-images.githubusercontent.com/478118/87619031-17062f80-c6d0-11ea-9981-f3750c6b5514.png)

In the future, please make sure to provide code and examples that can run in **LINQPad** with complete models. In this case, I had to guess at what `ModelProvider` and `TrimProvider` did. I don't like guessing when giving answers because it leads to a lot of back and forth and too much ambiguity. Basically, I had to guess at what the code is doing when parts are left out -- and that's not good. :(

I hope the code above helps.

Thanks,
Brian

**Comment by uchagani** [comment]
First, my apologies for the incomplete example.  I was trying to simplying my usecase and forgot a bunch of stuff.  

Thank you for the help, can't believe it was this simple.

**Comment by bchavez** [comment]
No problem @uchagani , sorry if my answer was a little short. I get a little frustrated when I don't have the complete picture -- I want to provide the best possible answer to your question and it's really hard when I don't have the full picture. Either way, I'm very glad the code helped.

Also, a little more observations on this issue:
* Maybe be a little careful pushing `Faker<T>` too far beyond its use case. Sometimes pushing `Faker<T>` too far can cause more complex code than necessary. Sometimes keeping it simple with a regular `Faker` object with an imperative/iterative approach as described in the "Without Fluent Syntax" section [here](https://github.com/bchavez/Bogus#without-fluent-syntax) can sometimes lead to simpler code.
* The order in which `.RuleFor` are ***initially*** defined is the order they will execute. If you have two or more rules that will very in dependency with respect to one another, then we have to take them out of where they are initially defined and place the rules in a location where order matters. See #279 for all the details on rule ordering.

If you have any more questions, feel free to ask and I'll try to help.

Thanks,
Brian

**Comment by uchagani** [comment]
No worries.  Regarding Rules, is there a way to get Rules to execute when `Generate` is called instead of when the rules are defined?  I have a lot of dependent properties and it seems cumbersome to add all the dependent fields twice (once for default and again for "overrides".

**Comment by bchavez** [comment]
I think it really depends on what the dependency graph looks like for the `.RuleFor()` rules. :thinking: How much reordering of `.RuleFor()` rules can occur if a single override is specified? Does a lot of re-ordering need to occur?

You might want to take a look at this `ReorderFaker<T>` I wrote for #279 and replace `Faker<T>` with [`ReorderFaker<T>`](https://github.com/bchavez/Bogus/blob/224bd6c13a5e3e022e275ad8d64df736ea7b432f/Source/Bogus.Tests/GitHubIssues/Issue279.cs#L162-L272) and see if it helps the situation.

If it doesn't help, I'm thinking we might be in a situation where using a simple `Faker` object might be better than `Faker<T>`. This way, we can take care of special dependencies with simple `if/else` and `Faker` statements.

Let me know what you think could work better.

**Comment by uchagani** [comment]
ReorderFaker is behaving the same way for me.  My use case is something like this:

```
Given I set the following rules in the constructor:
	Make: "Ford"
	Model: (f,c) => f.PickRandom(GetModelsByMake(c.Make))
	Trim: (f,c) => f.PickRandom(GetTrimByModel(c.Model))
When I override the rule for Make:
	Make: "Honda"
Then Model and Trim should be reevaluated to reflect the new Make
```
### Expected Result:

**Before override:** `{ Make: "Ford", Model: "F-150", Trim: "Limited" }`
	
**After override:** `{ Make: "Honda", Model: "Accord", Trim: "EX" }`
	
### Actual Result:

**Before override:** `{ Make: "Ford", Model: "F-150", Trim: "Limited" }`
	
**After override:** `{ Make: "Honda", Model: "F-150", Trim: "Limited" }`

**Comment by bchavez** [comment]
Hey @uchagani , I have to try to get some sleep, I'll try to answer this tomorrow after work or over the weekend. In the meantime, could you throw together a small GitHub repo or Gist with some examples of the unit tests you're using? and the full code for the `CarFactory`. I think I'm getting a little lost about what the actual problem is. I think it's the `switch` statement with the `.RuleFor` but I'm not totally sure.

**Comment by uchagani** [comment]
Will do. I'm not even worried about the overrides and switch statement at
this point. More so that Rules are re-evaluated when Generate is called.
I'll put something together in the morning for you.

Thank you for all your help!

**Comment by uchagani** [comment]
@bchavez I have to apologize again.  I did a very simple test version of what I wanted to do and _of course_ Bogus behaves as expected.  It helped me discover a bug in the querying logic.

I bought a premium license just to support you because of how helpful you are to the community.  Thank you.

**Comment by bchavez** [comment]
Hi @uchagani wow. I don't know what to say -- pretty humbling for sure. All I can say is, thank you for your support and recognition. It is moments like these that fill me with joy and make my day. One of the best things about OSS is helping people.

I'm glad you were able to resolve your issue. As always, if you have any questions, concerns, or feedback, please feel free to let me know. And thanks again for supporting Bogus. :+1: :trophy:
