### ISSUE TITLE
Polish locale is now featured in faker.js

### ISSUE THREAD

**Issue by arekminajj** [bchavez/Bogus#314]
**Context**

Polish locale is now featured in faker.js. You can update locales to use the latest locale data set.

**Comment by bchavez** [comment]
Hi @arekminajj,

Thanks for posting an issue. I think Bogus' locale data should be current with faker.js. Please give the latest version [`v30.0.1-beta-4`](https://www.nuget.org/packages/Bogus/30.0.1-beta-4) a try and let me know how it goes.

```csharp
void Main()
{
   var f = new Faker("pl"); // Polish
   f.Name.FullName().Dump();
}
```
![image](https://user-images.githubusercontent.com/478118/88467093-0308bd80-ce88-11ea-9ac0-2ec13b2d9f61.png)

**Comment by arekminajj** [comment]
Thank you @bchavez, Updated to the latest version and everything works great!
