### ISSUE TITLE
Is it possible to add new locale not globally?

### ISSUE THREAD

**Issue by yauhenikh** [bchavez/Bogus#315]
Greetings
I want to add a custom locale (just with a small amount of values like 10 firstnames, 10 lastnames etc.) to generate data (on my language) for my small non-commercial project.
Is it possible to do locally? And how to build the library (added ...locale.js file, but it doesn't work)? 
Thanks.

**Comment by bchavez** [comment]
Hi @yauhenikh ,

The first simplest way to extend Bogus is to use an extension method with custom data as shown below.

## Method 1 - Using Extension Methods
```csharp
void Main()
{
   var userFaker = new Faker<User>()
      .RuleFor(u => u.Name, f => f.Name.MyTenSimpleNames())
      .RuleFor(u => u.Age, f => f.Random.Number(18,38));
   
   userFaker.Generate(3).Dump();
   
   var faker = new Faker();
   faker.Name.MyTenSimpleNames().Dump();
}
```
```csharp
public class User
{
   public string Name {get;set;}
   public int Age {get;set;}
}

public static class MyCustomDataExtensions
{
   private static string[] SimpleNames = new string[]
      {
         "Billy Bob",
         "Sally Jay",
         "Marry Anne"
      };
      
   public static string MyTenSimpleNames(this Bogus.DataSets.Name n)
   {
      return n.Random.ArrayElement(SimpleNames);
   }
}
```
![image](https://user-images.githubusercontent.com/478118/89359386-8d1c0780-d67a-11ea-8fa4-ebd646f4d997.png)

---

## Method 2 - Patch an exiting locale

The example below patches the "en" locale at runtime:

```csharp
void Main()
{
   //using Bogus.Bson namespace
   var enLocale = Database.GetLocale("en");
   var nameObject = enLocale["name"];
   nameObject["male_first_name"] = new BArray{"bob", "bill"};
   nameObject["female_first_name"] = new BArray{"marry", "kate"};
   nameObject["first_name"] = new BArray{"sam", "karla"};
   nameObject["last_name"] = new BArray{"morris", "adams"};

   var userFaker = new Faker<User>()
      .RuleFor(u => u.Name, f => f.Name.FullName())
      .RuleFor(u => u.Age, f => f.Random.Number(18, 38));

   userFaker.Generate(3).Dump();
}
```
```csharp
public class User
{
   public string Name { get; set; }
   public int Age { get; set; }
}
```
![image](https://user-images.githubusercontent.com/478118/89366984-d1180800-d68c-11ea-8e51-6b9e4267f3cb.png)


---

## Method 3 - Custom Compiled Locale
If you want a custom compiled version with your custom locale, read and do the following found here:
https://github.com/bchavez/Bogus#building-from-source

To summarize:

1. Make locale file in `data`, **foobar.locale.json**:

![image](https://user-images.githubusercontent.com/478118/89365323-3669fa00-d689-11ea-94bf-f80c4c39e7d4.png)


2. You ***must*** follow the general format and JSON structure that Bogus & and faker.js use. For example, to add names to a custom locale:
**foobar.locale.json**
```
{
  "name":{
      "male_first_name": ["bob", "bill"],
      "female_first_name": ["marry", "kate"],
      "first_name": ["sam", "karla"],
      "last_name": ["morris", "adams"]
  }
}
```
3. Run `C:\...\Bogus\Source\Builder>npx gulp importLocales`

![image](https://user-images.githubusercontent.com/478118/89365578-be500400-d689-11ea-85d3-f1e6f3cfbbbe.png)
![image](https://user-images.githubusercontent.com/478118/89365622-df185980-d689-11ea-9593-0f816402086e.png)

The result is the **foobar.locale**.***bson*** file being created.

4. Compile Bogus.

   `C:\....\Bogus>build.cmd zip`

![image](https://user-images.githubusercontent.com/478118/89365794-3e766980-d68a-11ea-911f-9a26f20f386e.png)

5. **foobar** locale should be ready to use with DLL.

![image](https://user-images.githubusercontent.com/478118/89365970-ab89ff00-d68a-11ea-8d18-78968d936e02.png)

6. `new Faker("foobar")` and `new Faker<T>("foobar")` should be ready to use.

Let me know if that helps.

Thanks,
Brian

**Comment by yauhenikh** [comment]
Hello, @bchavez !
Thank you for the great explanation.
Method 3 is exactly what I need.

Best regards,
Yauheni

**Comment by bchavez** [comment]
Hi @yauhenikh, what do you think about the possible solution here?

https://github.com/bchavez/Bogus/blob/issue315/Source/Bogus.Tests/GitHubIssues/Issue315.cs

In this 4th method, you would not need to recompile. Basically, you would be able to add a custom locale at runtime.

I'm thinking about making a change, but I'm unsure how useful it would be.

**Comment by yauhenikh** [comment]
Hello, @bchavez !
Interesting feature, thanks!
The 4th method is good but I think it is better not to put non-latin characters in the source code.
But this feature could be added as possibility.
