### ISSUE TITLE
How to pass array parameter to handlebars expression?

### ISSUE THREAD

**Issue by fglaeser** [bchavez/Bogus#316]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |  29.0.2   |
| .NET Core?                   |     3.1      |
| .NET Full Framework?   |               |
| Windows OS?              |   Win10   |
| Linux OS?                    |                 |
| Visual Studio?              |      2019   |

### What's the problem?
I want to use the expression {{randomizer.arrayelement([A, B, C])}} and I get the following exception `{"Invalid cast from 'System.String' to 'Bogus.Bson.BArray'."}`

Is there a way to pass an array as paramater ?

### Do you have sample code to show what you're trying to do?
```csharp

var faker = new Faker();
faker.Parse("{{randomizer.arrayelement(['A', 'B', 'C'])}}");

```
_(Please be complete. Provide all code necessary to run your example in LINQPad.)_
_(The more complete code examples are, the more accurate answers will be.)_
_(https://www.linqpad.net)_

**Comment by fglaeser** [comment]
I found this in the faker.js unit test, perhaps this could show what I tried to do.

```js
        it("replaces a token with a random value for a method with an array parameter", function () {
            var arr = ["one", "two", "three"];
            var random = faker.fake('{{helpers.randomize(["one", "two", "three"])}}');
            assert.ok(arr.indexOf(random) > -1);
        });
```

**Comment by bchavez** [comment]
Hi @fglaeser, unfortunately, Bogus doesn't support creating arrays for function arguments. The `faker.Parse()` method is very limited in capability and barely supports function arguments (see #144). Bogus manually parses handlebar text because we're running in a .NET runtime compared to a JavaScript runtime with faker.js.

**Comment by fglaeser** [comment]
Ok. Thanks.

**Comment by bchavez** [comment]
The future enhancement to this to write a custom parser and DSL with an internalized version of **Sparche**: https://github.com/sprache/Sprache
