### ISSUE TITLE
Boolean does now get random?

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#32]
Hello,

I just tried the following faker:

          List<Ebook> ebooks = new Faker<Ebook>()
            .RuleFor(x => x.Id, () => 0)
            .RuleFor(x => x.IsApproved, y => y.Random.Bool())
            .RuleFor(x => x.EbookI18Ns, () => ebookI18Ns.Generate(_languages.Count).ToList())
            .RuleFor(x => x.Updated, (y, x) => y.Date.Between(DateTime.Now.AddDays(-40), DateTime.Now.AddDays(-20)))
            .Generate(20).ToList();

But the IsApproved is false in all items.

How can I get items with true or false in IsApproved?

Thank You,
Miguel

**Comment by bchavez** [comment]
Hi,

Can you check again? Works here...

```
[
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": true
  },
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": false
  },
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": false
  },
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": true
  },
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": false
  },
  {
    "Id": 0,
    "EbookI18Ns": null,
    "IsApproved": true
  },
```

:collision: :dizzy: [***"Crashing, hit a wall. Right now I need a miracle..."***](https://www.youtube.com/watch?v=s8XIgR5OGJc)

**Comment by mdmoura** [comment]
You are right! It was something else on my application.
