### ISSUE TITLE
Compability on .NET 5

### ISSUE THREAD

**Issue by arthuraugsten** [bchavez/Bogus#327]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  | 31.0.2   |
| .NET Core?                   |  Yes      |
| .NET Full Framework?  |  No      |
| Windows OS?              | Yes         |
| Linux OS?                    | Yes       |
| Visual Studio?             | No        |

### What locale are you using with Bogus?
pt-BR

### What is the expected behavior?
Generate fake data for Persons.

### What is the actual behavior?
'f.Person' generated an exception of type 'System.ArgumentOutOfRangeException'

### Any possible solutions?
Generate a release candidate version for .NET 5, It will able us to work on migrations project for new version.

### How do you reproduce the issue?
Use .NET 5 Release Candidate Version (5.0.100-rc.1.20452.10)

### Do you have a unit test that can demonstrate the bug?
```
new Faker<CriarUsuarioCommand>(FakerSingleton.Idioma)
                .CustomInstantiator(f =>
                    new CriarUsuarioCommand(
                        f.Person.FullName,
                        f.Person.Email,
                        FuncoesConstants.IdIeproMaster,
                        idInstituicao
                    )
                );
```

### Can you identify the location in Bogus' source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
Yes
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by bchavez** [comment]
Hi @arthuraugsten, could you please try v31.0.3 on .NET 5 and see if the problem has been resolved? I think we had a small issue with the `pt_BR` locale in #328 that caused an `ArgumentOutOfRangeException`.

https://www.nuget.org/packages/Bogus/31.0.3


Thanks,
Brian

**Comment by arthuraugsten** [comment]
Hello @bchavez , I've updated the nuget package version and the issue was solved!

Thank you!
