### ISSUE TITLE
Problem with person fullname in pt_BR

### ISSUE THREAD

**Issue by weguest** [bchavez/Bogus#328]
I got this message on generate a person fullname in pt_BR: "System.ArgumentOutOfRangeException: 'Index was out of range. ". 
When i use other languages, works fine.

**Comment by bchavez** [comment]
Are you using .NET 5? Possibly regarding #327

**Comment by weguest** [comment]
Net Core 3.1

**Comment by bchavez** [comment]
You'll have to give me some code that fails. I can't reproduce with `new Person("pt_BR").FullName.Dump();`

![image](https://user-images.githubusercontent.com/478118/95005758-01a6f000-05b1-11eb-8116-1a4efaa96eb5.png)

**Comment by weguest** [comment]
Here, i figure out the problem is when it gets the city name in person object.

"You'll have to give me some code that fails"
 
var f = new Faker("pt_BR");
Console.WriteLine(f.Person.FullName);

Its broke because the person object is null.

**Comment by bchavez** [comment]
Sorry Jose, but the code does not fail on my machine:

![image](https://user-images.githubusercontent.com/478118/95005965-84c94580-05b3-11eb-8438-13fd57e5e7d9.png)

Try providing a full stack trace of the exception so we can try to narrow this down further.

Thanks,
Brian

**Comment by weguest** [comment]
![image](https://user-images.githubusercontent.com/429524/95006061-4a24d480-05d6-11eb-9280-cf881e29da11.png)

I create a new net core 3.1 console application, add Bogus nugget package, and i got this message like the screenshot.

**Comment by weguest** [comment]
at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Bogus.Bson.BArray.get_Item(Int32 index)
   at Bogus.Randomizer.ArrayElement(BArray props, Nullable`1 min, Nullable`1 max)
   at Bogus.DataSet.<ParseTokens>b__27_0(Match x)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Bogus.DataSet.ParseTokens(String value)
   at Bogus.DataSet.GetFormattedValue(String path)
   at Bogus.DataSets.Address.City()
   at Bogus.Person.Populate()
   at Bogus.Person..ctor(Randomizer randomizer, String locale)
   at Bogus.Faker.get_Person()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\jose.braz.ext\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 16

**Comment by bchavez** [comment]
Very strange. What version of the Bogus NuGet package are you using?

**Comment by weguest** [comment]
![image](https://user-images.githubusercontent.com/429524/95006130-3cbc1a00-05d7-11eb-8dd3-6900144dc4e6.png)
31.0.2

**Comment by weguest** [comment]
Very strange... I try to debug, and its fail on get the city name inside the person object.

**Comment by bchavez** [comment]
I cannot reproduce the exception with `31.0.2`. Can you try `30.0.4` does exception still happen?

**Comment by weguest** [comment]
30.0.4 works fine!

**Comment by bchavez** [comment]
Thanks Jose, must be this change here in v31.0.2: 

![image](https://user-images.githubusercontent.com/478118/95006261-6feeb100-05b7-11eb-93bb-6466aaa4bbf3.png)

I can reproduce now. I will release a fix once I find a solution.

**Comment by weguest** [comment]
Thanks!

**Comment by bchavez** [comment]
Thanks Jose. Turns out this is a bug in faker.js too:
https://rawgit.com/Marak/faker.js/master/examples/browser/index.html
![image](https://user-images.githubusercontent.com/478118/95007202-d7116300-05c1-11eb-912f-0c0a526295c5.png)

I released `v31.0.3` with the fix. Let me know if it works or if you have any problems with the new **Bogus v31.0.3** version.

Please try: https://www.nuget.org/packages/Bogus/31.0.3
