### ISSUE TITLE
For CountryCode "SS" (South Sudan) no IBAN code is available

### ISSUE THREAD

**Issue by kodfodrasz** [bchavez/Bogus#329]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  | 31.0.3       |
| .NET Core?                   |  yes, .NET Core 3.1               |
| .NET Full Framework?   |  no               |
| Windows OS?              |   yes, 2004 build 19041.508             |
| Linux OS?                    |   no               |
| Visual Studio?              |   yes, 16.7.5   |

### What locale are you using with Bogus?
HU-hu (Hungarian)

### What is the expected behavior?
Be able to reliably use Bogus.Faker for generating IBAN codes for country codes it returned itself.

The code I executed:

```fsharp
let fake    = Faker()
let country = fake.Address.CountryCode() // returned "SS"
let iban    = fake.Finance.Iban(countryCode=country) // throw exception for not supporting country code "SS"
```

### Any possible solutions?

 - either don't return country codes not supported by other parts of Faker,
 - or add support for South Sudan in the IBAN module

### How do you reproduce the issue?

~~~
let fake    = Faker()
let iban = fake.Finance.Iban(countryCode="SS") 
assert ( 0 < iban.Length )
~~~

### Do you have a unit test that can demonstrate the bug?

Yes, see above.

### Can you identify the location in Bogus' source code where the problem exists?

No, I didn't look for it. Probably in some static data files lack entries for the country

### If the bug is confirmed, would you be willing to submit a PR?

Yes, depending on the necessary effort.

**Comment by bchavez** [comment]
Hi Gábor,

You're correct. The data returned from `fake.Address.CountryCode()` can't be joined with `fake.Finance.Iban(countryCode=country)`. The Iban data is not fully complete compared to the address country code dataset in this regard.

As an immediate workaround, you could create an extension method off the `Finance` data set that will only return "Iban" available country codes as shown below:

```csharp
void Main()
{
   var fake = new Faker();
   var ibanCountryCode = fake.Finance.IBanCountryCode();
   var iban = fake.Finance.Iban(countryCode: ibanCountryCode);
   
   ibanCountryCode.Dump();
   iban.Dump();
}

public static class ExtensionsForFinance
{
   private static string[] countryCodes = null;
   public static string IBanCountryCode(this Bogus.DataSets.Finance finance)
   {
      if ( countryCodes is null )
      {
         var formats = Database.Get("finance", "iban_formats") as Bogus.Bson.BArray;
         
         countryCodes = formats.OfType<Bogus.Bson.BObject>()
                               .Select(bo => bo["country"].StringValue)
                               .ToArray();
      }

      return finance.Random.ArrayElement(countryCodes);
   }
}
```
```
BG
BG84OWBK1509062904XE47
```

The best fix is to create an Iban format for every country code supported by the address data set. Unfortunately, I don't have the knowledge of all Iban formats in the world. The best we can do is to deal with the slight discrepancy until we get a full data set.

If you want to send a PR for the SS country code and/or additional formats, you can add an `iban_format` here:
https://github.com/bchavez/Bogus/blob/6d8e3b43c2a85845590c919a475550c175809679/Source/Bogus/data_extend/en.locale.json#L322-L323

I hope that helps.

Thanks,
Brian

**Comment by bchavez** [comment]
Hey Gábor, I'm going to close the issue now. Feel free to reference this issue number in your PR if you decide to update the `iban_formats` array.

**Comment by kodfodrasz** [comment]
I'll try to dedicate some time to this, to be able to send a PR. Thanks for the workaround, and for the library in general!

**Comment by bchavez** [comment]
No problem Gábor! Happy you like Bogus. Always gives me great joy hearing from devs using Bogus! :+1:
