### ISSUE TITLE
ArgumentOutOfRangeException when generating a Cpf in locale pt_BR

### ISSUE THREAD

**Issue by letsgetithipster** [bchavez/Bogus#331]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| .NET Core?                   |       x          |

### What locale are you using with Bogus?
pt_BR

### What is the expected behavior?
Generate a random Cpf.

### What is the actual behavior?
throws a ArgumentOutOfRangeException

### Any possible solutions?
No
 
### How do you reproduce the issue?
var f = new Faker("pt_BR");
Console.WriteLine(f.Person.Cpf());

### Do you have a unit test that can demonstrate the bug?
No

### Can you identify the location in Bogus' source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by letsgetithipster** [comment]
it is similar to the issue #328

**Comment by bchavez** [comment]
Hi Guilherme,

Please be sure to fill out the full bug ticket; including the version numbers. All the information in the template helps me debug the issue. What version of Bogus are you referencing?

I cannot reproduce the issue with `v31.0.3`. Are you running **Bogus** `v31.0.2`? Also, do you have a stack trace?

Thanks,
Brian

**Comment by bchavez** [comment]
Hi Guilherme, feel free to re-open the ticket if the problem still exists after upgrading to **Bogus** `v31.0.3`. I think the problem will be resolved after you upgrade the NuGet package version. Also, if it's still a problem, please post a **stack trace** so we can pinpoint where things went wrong. Thanks! :sunglasses:
