### ISSUE TITLE
This library is not suitable for exposure to the public: Please remove violent words from "Rant"

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [bchavez/Bogus#343]
This library has problems for public exposure as it contains many violent phrases, for example "behead", "kidnap", "electrocute", "slay", "maul", "maim" and many others.  I don't know if this was some inside joke or something but if your intention is to make a library only for private internal testing it's still not a great idea to contain those words as private internal work has a way of getting out into the world.

This is not the first time I've come across problematic words in this library that would be offensive to many, if the intent is to make a library intended only for internal private testing then please make that intent **very clear** in the docs or post a warning that it's not suitable for exposure to the public to anyone whom a positive reputation is important.

**Comment by bchavez** [comment]
Hello, my response is the same. Please see: https://github.com/bchavez/Bogus/issues/228#issuecomment-505660045

If you'd like to improve the `.Rant` section of Bogus, please send a PR with the improvements. Thanks.
