### ISSUE TITLE
unreconizable strings with Random.String() when using locale "pt_BR"

### ISSUE THREAD

**Issue by ucavalcante** [bchavez/Bogus#344]
![image](https://user-images.githubusercontent.com/13587928/103414692-bd9a9b80-4b5d-11eb-8cc8-ec34e989cda2.png)

### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |    32.0.2             |
| .NET Core?                   |      3.1           |
| .NET Full Framework?   |       no          |
| Windows OS?              |         1809 - 17763.16.73         |
| Linux OS?                    |           no       |
| Visual Studio?              |         vs code 1.51.1        |

### What locale are you using with Bogus?
pt_BR
### What is the expected behavior?
some western strings when call 
   ```
 var f = new Faker("pt_BR");
 var word = f.Random.String(10)
```

### What is the actual behavior?
show korean or chinese string

### Please provide a stack trace.
No exception are generated.

### Any possible solutions?
No

### How do you reproduce the issue?
```
           var f = new Faker("pt_BR");
            var o = new 
                {
                    OrderId = f.Random.Number(1, 100),
                    Item = f.Lorem.Sentence(),
                    Quantity = f.Random.Number(1, 10),
                    word = f.Random.String(10),
                    city = f.Address.City()
                };
```
### Do you have a unit test that can demonstrate the bug?
No

### Can you identify the location in Bogus' source code where the problem exists?
No

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by bchavez** [comment]
Hello,

This is not a bug. The `.String()` method is working as designed. Please be sure to check the **XmlDoc** comments on the method:

https://github.com/bchavez/Bogus/blob/8346c32fba14d781e2733ff499e71e764afc9400/Source/Bogus/Randomizer.cs#L329-L338

The method will return a string with characters from `char.MinValue` to `char.MaxValue`.

If you want characters in the ASCII range, try `.Random.String2()` or `.Lorem.Sentence()`.

```csharp
void Main()
{
   var f = new Faker();
   f.Random.String2(10).Dump();
   f.Lorem.Sentence().Dump();
}
```
```
hkardwsltw
Fuga sint quidem eligendi architecto omnis impedit.
```

Thanks,
Brian

**Comment by Nefcanto** [comment]
This took me hours. I wish you would include the name of the range in the method name. Something like `UnicodeString` and `AsciiSring` would be much better.
