### ISSUE TITLE
DevSecOps pipeline

### ISSUE THREAD

**Issue by kulov** [bchavez/Bogus#348]
### Please describe why you are requesting a feature
Using built-in GitHub workflow system enables security checks and integrated CI/CD experience.

### Please provide a code example of what you are trying to achieve

[GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions)

### Please answer any or all of the questions below

* Is the feature something that currently cannot be done?
Code scanning, version and security checks, static analysis.

* What alternatives have you considered?
GitHub Actions, Azure DevOps Service, SonarCloud, CodeQL, TestSpace.

* Is this feature request any issues or current problems?
Open security vulnerabilities must be fixed.

* Has the feature been requested in the past?
No information.

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by bchavez** [comment]
Unfortunately, the pull-request is rejected for the following reasons. Please see: https://github.com/bchavez/Bogus/pull/349#issuecomment-761587301 Again, I apologize for the PR rejection.
