### ISSUE TITLE
Add a few extra Random Helpers

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#35]
I suggest adding the following to Bogus:

1. Generate a random Double between a Minimum and Maximum number:

    .RuleFor(x => x.Double, y => y.Random.Double(1, 4))

2. Generate other random types as Single, Decimal, ...:

    .RuleFor(x => x.Decimal, y => y.Random.Decimal(1, 4))

What do you think?

**Comment by bchavez** [comment]
You got it bro. https://www.nuget.org/packages/Bogus/7.1.5

Enjoy :+1: :sunglasses: 

:busstop: :bus: [***"Fe, Fi, Fo, Fum... Well, I'll be darn here it comes... The Double Dutch Bus is on the street"***](https://www.youtube.com/watch?v=fK9hK82r-AM)
