### ISSUE TITLE
[Feature request] Implement lean GitHub DevSecOps pipeline

### ISSUE THREAD

**Issue by kulov** [bchavez/Bogus#353]
#### 1. Outstanding issues

- dependency of AppVeyor as third-party build system
- build orchestration as single command line utility
- lack of visual step by step build and test execution
- no secrets management

#### 2. Proposed improvements

- Lean DevSecOps pipeline to visualize step by step build orchestration using GitHub Actions with integrated secret management and security checks
- CI/CD Documentation - complete, step-by-step guide for every feature
- Free support included (up to 1 year)

@kulov from [Pipeline Foundation](https://pipeline.foundation/)

**Comment by bchavez** [comment]
@kulov, I've reviewed the PR.
* What is the *value* we are proposing with the PR?

As far as I can understand, PR #354 uses GitHub Actions for build and test. For what purpose? Are we not using AppVeyor for this ***exact*** purpose? What value does it add for us except waste computational resources in some GitHub datacenter far-far away?

Effectively, you are asking me to enable a new build CI/CD pipeline. I do not need a new CI/CD pipeline with Bogus; the one I have with AppVeyor has worked for 100s of builds; 1,061 builds to be exact.

As I mentioned before, I have GitHub Actions disabled on all my public repositories. I do not use Actions on GitHub.

With respect, please do not submit any new PRs that change the CI/CD pipeline process.
