### ISSUE TITLE
Update faker.js to have gendered pt-br names

### ISSUE THREAD

**Issue by peterson3** [bchavez/Bogus#355]
### Please describe why you are requesting a feature

Please update faker.js to have gendered pt-br names.
Dont know if i need to request like this or PR the change.

TY,

**Comment by bchavez** [comment]
@peterson3, new **Bogus** `v33.0.1` contains latest changes from at tip https://github.com/Marak/faker.js/commit/5478d65dcb99a3c5f1a941d6a9d101d02bc467c2

https://www.nuget.org/packages/Bogus/33.0.1

Let me know how it goes.

Thanks,
Brian
