### ISSUE TITLE
Missing `Commerce` dataset from `Faker`

### ISSUE THREAD

**Issue by jenyayel** [bchavez/Bogus#36]
Hi,

Is it intentional that [Faker](https://github.com/bchavez/Bogus/blob/3d6fb914417219243466da8be2a6227f18acac9c/Source/Bogus/Faker.cs) class is missing `Commerce` dataset that documented in readme?

Thanks.
CC: @eugene-senexx

**Comment by bchavez** [comment]
Hey @jenyayel , good eye. Nice catch. It was an oversight on my part.

[`Bogus v7.1.6`](https://www.nuget.org/packages/Bogus/7.1.6) pushed. Enjoy.

:walking: :sunglasses: [***"So don't delay... act now supplies are running out..."***](https://www.youtube.com/watch?v=LQj--Kjn0z8)
