### ISSUE TITLE
Cannot use Images in my rules

### ISSUE THREAD

**Issue by gsscoder** [bchavez/Bogus#362]
Hi, maybe I'm getting stupid for working too much (lol), but event if add `Bogus.DataSets`, compiler can't resolve `Image` symbol.

```
var faker = new Faker<Product>()
    .RuleFor(p => p.ImageUri, f => new Uri(f.Images.LoremFlickrUrl())); // doesn't compile
```

Am I missing to add another assembly?

Thanks for excellent project!

Regards,
Giacomo S. S.

**Comment by bchavez** [comment]
The following seems to compile okay:

```csharp
void Main()
{
   var faker = new Faker<Product>()
      .RuleFor(p => p.ImageUri, f => new Uri(f.Image.LoremFlickrUrl()) );
      
   faker.Generate().Dump();
}
public class Product
{
   public Uri ImageUri;
}
```

![image](https://user-images.githubusercontent.com/478118/108616618-b8223a80-73c3-11eb-837a-dbed20272995.png)

Let me know if you continue to have trouble. There were a few typos in your example. Feel free to continue to discuss after I close the issue.

**Comment by gsscoder** [comment]
Sorry, @bchavez, I wasted your time.

It was a typo also in code `Images `instead of Image. I also cloned the code to check but the 's' escaped from my eyesight. lol

Thank you for spotting it!

Have a nice day
