### ISSUE TITLE
Limit character length for Company.CompanyName()

### ISSUE THREAD

**Issue by rachael-ross** [bchavez/Bogus#369]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |    33.0.2             |
| .NET Core?                   |       3.1          |
| .NET Full Framework?   |                 |
| Windows OS?              |    10              |
| Linux OS?                    |                  |
| Visual Studio?              |      16.9.2  |

### What's the problem?

I'm wondering how to know what character length constraints are in place for predefined types of generated data, such as Company.CompanyName() or Address.StreetAddress(). 

Do we have a way to set the constraints ourselves?

```
return new Faker<Org>()
                .StrictMode(false)
                .Rules((f, o) => {
                    o.EIN = f.Company.Ein();
                    o.Name = f.Company.CompanyName();
                    o.AddressLine1 = f.Address.StreetAddress();
                    o.AddressLine2 = f.Address.SecondaryAddress();
                    o.City = f.Address.City();
                    o.ZipCode = f.Address.ZipCode();
                });
```

### Do you have sample code to show what you're trying to do?

_(Please be complete. Provide all code necessary to run your example in LINQPad.)_
_(The more complete code examples are, the more accurate answers will be.)_
_(https://www.linqpad.net)_

**Comment by bchavez** [comment]
Hi Rachael, thank you for your question.

Generally, there is no bound on the length of characters that **Bogus** can generate; unless the specific method supports a `length` or some `limit` parameter. For example,

![image](https://user-images.githubusercontent.com/478118/112562034-a7cef800-8d93-11eb-917c-07a3e0812404.png)

In cases where we would like to limit the length of characters without explicit parameter support, we can use the `.ClampLength(max: 10)` string extension method shipped with **Bogus**. For example,

![image](https://user-images.githubusercontent.com/478118/112562636-f6c95d00-8d94-11eb-9b20-1827f3e2560a.png)

Additionally, we also have the option to use other API  methods or augment and extend the existing APIs as shown below:

```csharp
void Main()
{
   var faker = new Faker();
   faker.Address.StreetAddressFixed(len: 12).Dump();
}
public static class MyAddressExtensionsForBogus
{
   public static string StreetAddressFixed(this Bogus.DataSets.Address addr, int len)
   {
      //whatever custom code that is accetible in our given scenario
      if( len - 11 <= 0) throw new ArgumentOutOfRangeException(nameof(len), "len must be >= 12 characters");
      var name = addr.StreetName().ClampLength(max: len - 11);
      return addr.Random.Replace($"### {name} Street");
   }   
}
```
![image](https://user-images.githubusercontent.com/478118/112564475-90463e00-8d98-11eb-80c8-7bbf6d807d3b.png)

I hope that helps. If you have any more questions; feel free to carry on the conversation after I close the issue.

Thanks,
Brian
