### ISSUE TITLE
Can't able to generate address by specific country

### ISSUE THREAD

**Issue by nilekshdhimer91** [bchavez/Bogus#371]
Hi there below is my code:

public List<BogusUser> GenerateAUserData()
        {
            Random r = new Random();
            var newage = r.Next(18, 50);
            var userFaker = new Faker<BogusUser>(locale: "en_US")
            .RuleFor(u => u.Gender, f => f.Person.Gender.ToString())
            .RuleFor(u => u.BirthDate, f => f.Date.Past(newage))
            .RuleFor(u => u.FirstName, f => f.Person.FirstName)
            .RuleFor(u => u.LastName, f => f.Person.LastName)
            .RuleFor(u => u.Email, f => f.Person.Email.ToLower())
            .RuleFor(u => u.PhoneNumber, f => f.Phone.PhoneNumber("(###)-###-####"))            
            .RuleFor(u => u.Address, f => f.Address.StreetAddress() + " " + f.Address.StreetName())
            .RuleFor(u => u.City, f => f.Address.City())
            .RuleFor(u => u.State, f => f.Address.State())
            .RuleFor(u => u.Country, f => f.Address.Country())
            .RuleFor(u => u.ZipCode, f => f.Address.ZipCode());
            var users = userFaker.Generate(10);
            return users;
        }

**I want to generate address, street name, city, state and phone number based on USA country only.**

**Comment by bchavez** [comment]
```csharp
...
.RuleFor(u => u.State, f => f.Address.State())
.RuleFor(u => u.Country, f => "USA")
.RuleFor(u => u.ZipCode, f => f.Address.ZipCode());
```
