### ISSUE TITLE
Simple Quesiton in relation Data sample

### ISSUE THREAD

**Issue by davidbuckleyni** [bchavez/Bogus#374]
In your sample simple you show a user and shopping cart example I want to store the cartId also in the orders section it doesnt show clearly how one would do that you just have this.

       .RuleFor(u => u.Orders, f => testOrders.Generate(3))
       .RuleFor(u => u.SomeGuid, Guid.NewGuid()
 I would need F to use the same Guid for the cart Id as U how would i do this.

     var orderIds = 0;
            var testOrders = new Faker<Order>()
               //Ensure all properties have rules. By default, StrictMode is false
               //Set a global policy by using Faker.DefaultStrictMode if you prefer.
               .StrictMode(true)
               //OrderId is deterministic
               .RuleFor(o => o.OrderId, f => orderIds++)
               //Pick some fruit from a basket
               .RuleFor(o => o.Item, f => f.Commerce.ProductName())
                 .RuleFor(u => u.CartId, f =>    Guid.NewGuid())

               //A random quantity from 1 to 10
               .RuleFor(o => o.Quantity, f => f.Random.Number(1, 10))
               //A nullable int? with 80% probability of being null.
               //The .OrNull extension is in the Bogus.Extensions namespace.
               .RuleFor(o => o.StockCode, f => f.Random.Int(0, 100).OrNull(f, .8f))
               .RuleFor(o => o.BarCode, f => f.Commerce.Ean13());

**Comment by bchavez** [comment]
The question is not clear. I don't have access to your code and I don't know the context.

Does this answer your question?
```csharp
var cartId = theCartIdComesFromSomehere_DatbaseOrSomeOtherObject;
var testOrders = new Faker<Order>()
   .RuleFor(u => u.CartId, f => cartId)
   ....
```

**Comment by bchavez** [comment]
You will need to create a full and **_working_** unit test or a LINQPad example that demonstrates your issue. I need to be able to run some code in order to help more.
