### ISSUE TITLE
Fake values are not assigned to the members of the generated fake object, that don't have 'setter'

### ISSUE THREAD

**Issue by yadviv** [bchavez/Bogus#377]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |     33.0.2     |
| .NET Core?                   |       3.5       |
| .NET Full Framework?   |      3.5        |
| Windows OS?              |       10        |
| Linux OS?                    |       -       |
| Visual Studio?              |       -       |

### What locale are you using with Bogus?
Not applicable

### What's the problem?
This is not a problem, instead I want to know the work-around. This is a special case, and it would make more sense if we go through the sample code below to understand the question, instead of writing down the things. I hope you understand :).

#### Sample code
```
// ------------------------ Interface ------------------------

public interface IPersonInfo
{
   public string FirstName { get; }
   public string LastName { get; }
   public string Email { get; }
}

// ------------------------ Impl/Concrete Class ------------------------

public class PersonInfo : IPersonInfo
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public string Email { get; set; }
}

// ------------------------ Faker Class ------------------------

public class FakePersonInfo
{
    private readonly Faker<IPersonInfo> _faker;              // --- Interface used for Generic here

    public FakePersonInfo()
    {
        // --- >>> CustomInstantiator(... Impl/Concrete Class ...)
        _faker = new Faker<IPersonInfo>().CustomInstantiator(_ => new PersonInfo()); 

        var person = new Bogus.Person();

        _faker.RuleFor(pi => pi.FirstName, () => person.FirstName);
        _faker.RuleFor(pi => pi.LastName, () => person.LastName);
        _faker.RuleFor(i => i.Email, () => person.Email);
    }

    public IPersonInfo Generate()
    {
        return _faker.Generate();
    }
}

// ------------------------ Main ------------------------

internal static class ExecuteFakerExample
{
    private static void Main(string[] args)
    {
        var fakePersonInfo = new FakePersonInfo();
        var personInfo = fakePersonInfo.Generate();

        const string NA = "Not generated";

        WriteLine("First name: " + (personInfo.FirstName.IsNullOrEmpty() ? NA : personInfo.FirstName));
        WriteLine("Last name: " + (personInfo.LastName.IsNullOrEmpty() ? NA : personInfo.LastName));
        WriteLine("Email: " + (personInfo.Email.IsNullOrEmpty() ? NA : personInfo.Email));
    }
}
```

Output
```
First name: Not generated
Last name: Not generated
Email: Not generated
```

Expected Output:
```
First name: Ira
Last name: Murphy
Email: Ira71@yahoo.com
```

### What possible solutions have you considered?
1. Introduce setter for the Interface members. (Setter can't be added, in my case)
    - Problem: ` FirstName { get; }  `
    - Solution: ` FirstName { get; set; } `
2. Assign class `PersonInfo` as the Generic, which has setter for all the members. (Last resort, in my case)
     - Problem: ` Faker<IPersonInfo> _faker = new Faker<IPersonInfo>().CustomInstantiator(_ => new PersonInfo()); `
     - Solution: ` Faker<PersonInfo> _faker = new Faker<PersonInfo>; `

### Do you have sample code to show what you're trying to do?
Yes.  See section: What's the problem? -> Sample code

**Comment by bchavez** [comment]
IMHO, **_keep it simple_**. Not all problems should be solved with the complexity of `Faker<T>`:

```csharp
void Main()
{  
   var personInfo = GeneratePersonInfo();
   personInfo.Dump();
}
public static IPersonInfo GeneratePersonInfo()
{
   //var f = new Faker(); // if you need other fake generation methods
   var p = new Bogus.Person();
   var pi = new PersonInfo
   {
      FirstName = p.FirstName,
      LastName = p.LastName,
      Email = p.Email
   };
   return pi;
}

public interface IPersonInfo
{
   public string FirstName { get; }
   public string LastName { get; }
   public string Email { get; }
}
public class PersonInfo : IPersonInfo
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public string Email { get; set; }
}
```
![image](https://user-images.githubusercontent.com/478118/125217501-0c985a80-e27e-11eb-818f-2d327a47ae48.png)


Alternatively, please see this post to using interfaces with `new Faker<Interface>`: https://github.com/bchavez/Bogus/issues/372#issuecomment-840883905
