### ISSUE TITLE
Feature: RuleFor Type

### ISSUE THREAD

**Issue by grehovm** [bchavez/Bogus#38]
I have class with 50-100 properties. I would like something like

```
.RuleFor<int>(y => y.Random.Int(1, 100))
.RuleFor<double>(y => y.Random.Double())
.RuleFor(x=>x.SomeIntProperty, y=>y.Int(100,200))
```

or

```
.RuleFor(typeof(int), y => y.Random.Int(1, 100))
```

ability to set rules for types and override rule for specific property.

**Comment by bchavez** [comment]
Hi @grehovm ,

Thanks for your suggestion. I think it makes sense. Your scenario could be enabled by using a convention based approach that allows you to create your own convention rules.

Reference #8

**Comment by grehovm** [comment]
if you mean convention for name - it's bad idea because of specificity of property names(physical \ chemical calculations):
```
        public double Ro { get; set; }
        public double D0 { get; set; }
        public double D { get; set; }
        public double WobbeV0 { get; set; }
        public double WobbeN0 { get; set; }
        public double WobbeV { get; set; }
```
if you mean convention for type - i would like a simple syntax, as i stated in the opening post.
But, of course, it's up to you.

**Comment by bchavez** [comment]
Hi @grehovm 

Understood, I'll need a few weeks to think about this and a proper API that will work well in a situation like this given my current time constraints.  

Thanks, 
Brian

**Comment by bchavez** [comment]
Hi @grehovm 

We have a new method [`RuleForType` (sample unit test)](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/FluentTests.cs#L156-L168) that allows setting up a rule for a particular type on a class.

This should ease your scenario.

[`v8.0.3`](https://www.nuget.org/packages/Bogus/) should be available on NuGet soon.

:cloud: :sunny: [**Bassnectar - Chasing Heaven - Into the Sun**](https://www.youtube.com/watch?v=a2BAia075lE)

**Comment by grehovm** [comment]
Thanks!
