### ISSUE TITLE
Parent have children && one to many

### ISSUE THREAD

**Issue by HelloValue** [bchavez/Bogus#380]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |       33.0.2          |
| .NET Core?                   |       /         |
| .NET Full Framework?   |          .NET 5       |
| Windows OS?              |        /          |
| Linux OS?                    |       /           |
| Visual Studio?              |       2019           |

### What locale are you using with Bogus?
.NET 5
### What's the problem?
I have two class：
```
public class  Order{
    public string OrderId { get; set; }
    public string EncounterType {get;set;}
    public string OrderCreateTime {get;set;}
    public List<TestItem> TestItems { get; set; }
  }

  public class  TestItem {
    public string OrderId { get; set; }
    public String ItemCode { get; set; }
  }

```
i want generate 10 order, and OrderId  is different. 
then it contains any TestItem and OrderId should be Order's OrderId.

Thanks.

### Do you have sample code to show what you're trying to do?
```
var itemcodeGenerator = new Faker<TestItem>()
			 .RuleFor(o => o.OrderId, Guid.NewGuid().ToString())
			 .RuleFor(o => o.ItemCode, f => f.Name.ItemCode());

			var itemcodes = itemcodeGenerator.Generate(10).ToList();

			var orderGenerator = new Faker<Order>()
			 .RuleFor(c => c.Diagnosis, f => f.Phone.PhoneNumber())
			 .RuleFor(c => c.OrderId, f => Guid.NewGuid().ToString())
			 .RuleFor(c => c.EncounterType, f => f.Name.EncounterType())
			 .RuleFor(c => c.TestItems, f => itemcodeGenerator.Generate(f.Random.Number(8)).ToList());

var orders  =  orderGenerator.Generate(10);
```

_(Please be complete. Provide all code necessary to run your example in LINQPad.)_
_(The more complete code examples are, the more accurate answers will be.)_
_(https://www.linqpad.net)_

**Comment by HelloValue** [comment]
++,This is the json data I want：

```
[{
        "OrderId":"1",
        "EncounterType":"S",
        "OrderCreateTime":"20210401",
        "TestItem":[
          {"OrderId":"1","ItemCode":"K"},{"OrderId":2,"ItemCode":"NA"}
        ]

      },
      {
        "OrderId":"2",
        "EncounterType":"R",
        "OrderCreateTime":"20210401",
        "TestItem":[
          {"OrderId":"2","ItemCode":"K1"},{"OrderId":2,"ItemCode":"NA2"}
        ]
}]
```

**Comment by davidbuckleyni** [comment]
I two am wanting this u think something so simple would be answered quick but been still waiting on an answer @HelloValue

**Comment by bchavez** [comment]
Please read the examples here for `Blog` (parent) and `Post` (child) relationships:
https://github.com/bchavez/Bogus/blob/9fc7614274f7f80b889151aa31a5fd2f2d0e610d/Examples/EFCoreSeedDb/Program.cs#L64-L153

**Comment by HelloValue** [comment]
@davidbuckleyni @bchavez  Thanks.

Sorry, it's my problem, I didn't find the post.

**Comment by bchavez** [comment]
@HelloValue , no worries. Let me know if you have any other questions.

Feel free to post in https://github.com/bchavez/Bogus/discussions
