### ISSUE TITLE
What is the Ignore function do?

### ISSUE THREAD

**Issue by HillCat** [bchavez/Bogus#391]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |         33.1.1        |
| .NET Core?                   |    .net core 5.0            |
| .NET Full Framework?   |       no          |
| Windows OS?              |        windows 10 pro 21H1         |
| Linux OS?                    |         no         |
| Visual Studio?              |        visual studio 2019  16.11.2       |

### What's the problem?
I want to let Bogus don't generator some properties, I use the 'Ignore' function, but the property Id is generated at all because my SQL database primary key Id is auto-generated, the id can't be given by mock data. I don't need the Id.
![TnWHvaXnN2](https://user-images.githubusercontent.com/41800196/131316646-a07c26a3-1746-4b72-b9b4-8a70ecab2218.png)

### What possible solutions have you considered?
I have no idea.
### Do you have sample code to show what you're trying to do?
no

**Comment by salixzs** [comment]
If your property is not nullable - it will have default value, which is 0 (zero) for integer/long.
