### ISSUE TITLE
Random Date/Time Only

### ISSUE THREAD

**Issue by rgarrison12345** [bchavez/Bogus#397]
### Please describe why you are requesting a feature
With .NET 6 comes the new DateOnly and TimeOnly types. Would like to see a random value for both of these types just like random generators for date time and datetimeoffset.

### Please provide a code example of what you are trying to achieve

_(Please be complete. Include all code necessary to run your example in LINQPad.)_
_(The more complete code examples are, the more accurate answers will be.)_
_(https://www.linqpad.net)_

### Please answer any or all of the questions below

* Is the feature something that currently cannot be done?
No

* What alternatives have you considered?
N/A

* Is this feature request any issues or current problems?
No

* Has the feature been requested in the past?
No

**If the feature request is approved, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_
Yes

**Comment by bchavez** [comment]
Sounds good - I think we can do this. However, some points:

* The new `DateOnly` and `TimeOnly` method generations need to use `#if NET6` preprocessor directives.
* We won't merge this until **.NET 6** is RTM **_and_** **AppVeyor** CI/CD supports **.NET 6**.

The bad part about this is that the `Bogus.nupkg` is going to grow in size by another factor because we are shipping a new `net6` specific TFM/DLL.

**Comment by prasadtelkikar** [comment]
Hi @bchavez ,

I am new to this repository but following it from long time.
If @rgarrison12345  did not started working on this open issue, I would like to contribute to this repository.

@rgarrison12345 can I go ahead and try this out?

**Comment by bchavez** [comment]
Hey @prasadtelkikar, cool! That's fine with me. I'm sure we can all collaborate on it. 

However, for whoever works on the PR initially, please just a few tips to keep in mind would be great:

* Please be sure to keep the contribution guidelines in focus: https://github.com/bchavez/Bogus/blob/master/CONTRIBUTING.md
* Keep the PR small and simply focused on only the changes that need to occur for this ticket.
* Try to avoid any unnecessary whitespace changes or code reformatting.
* Please add unit tests with the PR.
* Keep the PR editable so I can add commits if needed before merging.
* Also, please follow the existing coding style and conventions in **Bogus** as much as possible.

Thanks so much @prasadtelkikar and @rgarrison12345. All these tips should help the review/merge process go smoothly.

**Comment by rgarrison12345** [comment]
Hello @prasadtelkikar you can take on the PR if you would like.

**Comment by prasadtelkikar** [comment]
Hi @bchavez,

I just shared a design document for this feature implementation. I would like to know your thoughts on it.
@rgarrison12345  I did not find your email address. I can forward you the same email if you would go through it, before I start implementing it.

**Comment by bchavez** [comment]
@prasadtelkikar , you can post the design doc in in the Discussions tab: https://github.com/bchavez/Bogus/discussions

I would say, **Approach 1**: Add new functions to `Date` dataset instead of using inheritance.

For an initial start, here's the methods I would start with:

* `PastDateOnly` - Make defaults consistent with Past() DateTime
* `SoonDateOnly` - Make defaults consistent with Soon() DateTime
* `SoonTimeOnly` - Some time in the next 15 minutes
* `FutureDateOnly` - Make defaults consistent with Future() DateTime
* `BetweenDateOnly` - Make defaults consistent with Between() DateTime
* `BetweenTimeOnly` - Some TimeOnly Between Start and End; always in a clockwise direction
* `RecentDateOnly` - Make defaults consistent with Recent() DateTime
* `RecentTimeOnly` - Some time in the last 15 minutes

When implementing Approach 1, try to keep all of these new methods grouped into one code section (at the end of `Date.cs`) so that `#if NET6 / #endif` directive is only used once.

**Comment by pdevito3** [comment]
I'm also running in to this and am blocked from some refactoring I was hoping to start tackling. Details here if it helps: https://github.com/nickdodd79/AutoBogus/issues/76

@bchavez those options would work well for my use cases

**Comment by bchavez** [comment]
Hi @pdevito3, thanks a bunch for checking in and linking to the AppVeyor news. That's great.

After reading the news, looks like we're going to need a tooling update to get access to .NET 6.

https://github.com/bchavez/Bogus/blob/1406a8ba7ae326dca106bbf5bb827fcd7e47be82/appveyor.yml#L2

So, it looks like there is still some blocking work we need to do before merging a `Date/TimeOnly` PR.

Basically, we need to update our 1) AppVeyor image and 2) my tooling on my local dev box, and 3) our tests working on the .NET 6 SDK before we can merge a `Date/TimeOnly` PR.

**Comment by bchavez** [comment]
This is done now.

It's very late right now... but I'll make a new release within the next few days.

**Comment by pdevito3** [comment]
thanks guys! 🎉

**Comment by bchavez** [comment]
Hey all, **Bogus** `v34.0.1` released with **.NET 6** support for `DateOnly` and `TimeOnly`.
* https://www.nuget.org/packages/Bogus/34.0.1

**Comment by candritzkynet** [comment]
I came across this in Dec 2024 and it's still not working with **AutoBogus 2.13.1** and **Bogus 35.6.1** (both latest available as of today). Here's my code:

```csharp
    [Fact]
    public void DateOnlyTest()
    {
        AutoFaker<MyEntity> faker = new();
        MyEntity result = faker.Generate();
    }

    public class MyEntity
    {
        public DateOnly DateOfBirth { get; set; }
    }
```

And here's what I get:

```
System.ArgumentOutOfRangeException
Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateOnly..ctor(Int32 year, Int32 month, Int32 day)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

What am I missing?

**Comment by candritzkynet** [comment]
OK, found it. A rule for the DateOnly type was missing:

```csharp
        faker.RuleForType(typeof(DateOnly), _ => DateOnly.FromDateTime(DateTime.Today));
```

Now this works:

```csharp
    [Fact]
    public void DateOnlyTest()
    {
        AutoFaker<MyEntity> faker = new();
        faker.RuleForType(typeof(DateOnly), _ => DateOnly.FromDateTime(DateTime.Today));
        MyEntity result = faker.Generate();
    }

    public class MyEntity
    {
        public DateOnly DateOfBirth { get; set; }
    }
```

**Comment by candritzkynet** [comment]
But this still doesn't work:

```csharp
    [Fact]
    public void DateOnlyTest()
    {
        AutoFaker<MyEntity> faker = new();
        faker.RuleForType(typeof(DateOnly), _ => DateOnly.FromDateTime(DateTime.Today));
        MyEntity result = faker.Generate();
    }

    public class MyEntity
    {
        public MyPerson Person {get; set;}
    }

    public class MyPerson
    {
        public DateOnly DateOfBirth { get; set; }
    }
```

Where can I configure a general rule for all my properties of type `DateOnly`?

**Comment by candritzkynet** [comment]
Could finally solve it by providing my custom AutoBinder derived implementation. Here's the code in case someone runs into the same problem:

```csharp
/// <summary>
/// Extends the <see cref="AutoBinder"/> class with support for properties
/// of type <see cref="DateOnly"/> or <see cref="TimeOnly"/>.
/// </summary>
/// <example>
/// <![CDATA[
/// AutoFaker<MyClass> faker = new(new AutoBinderWithDateTimeOnlySupport());
/// MyClass instance = faker.Generate();
///
/// private MyClass
/// {
///   public DateOnly DateOfBirth { get; set; }
/// }
/// ]]>
/// </example>
public class AutoBinderWithDateTimeOnlySupport : AutoBinder
{
    /// <summary>
    /// Extends the base class implementation with support for
    /// <see cref="DateOnly"/> and <see cref="TimeOnly"/> types.
    /// </summary>
    /// <typeparam name="TType">The type of instance to create.</typeparam>
    /// <param name="context">The <see cref="AutoGenerateContext"/> instance for the generate request.</param>
    /// <returns>The created instance of <typeparamref name="TType"/>.</returns>
    /// <remarks>
    /// The problem with the <see cref="DateOnly"/> and <see cref="TimeOnly"/> types
    /// is that they have public constructor overloads that don't accept default values.
    /// E.g. the first public DateOnly constructor is the one that takes year, month and day.
    /// But none of these arguments must be 0 (must be 1 or greater).
    /// The stupid AutoBogus library picks the first constructor (which is a bit random)
    /// and calls it with some random/bogus values.
    /// </remarks>
    public override TType CreateInstance<TType>(AutoGenerateContext context)
    {
        Type type = typeof(TType);
        if (type == typeof(DateOnly) || type == typeof(TimeOnly))
        {
            return default!;
        }

        return base.CreateInstance<TType>(context);
    }
}

```
