### ISSUE TITLE
Vehicles manufacturer is not matching to model correctly

### ISSUE THREAD

**Issue by Mateusz19021996** [bchavez/Bogus#409]
When we create car with model and manufacturer properties, we get result for example :

Chevrolet	Jetta
Cadillac	PT Cruiser
Porsche	Charger
Fiat	        A8
Cadillac	ATS

There is no correct matching, any chance to correct it?

**Comment by bchavez** [comment]
Hello,

there is no chance to correct it -- that data comes from upstream `faker.js`. The `vehicle.manufacture` and `vehicle.model` are disjoint arrays in our data source (and also in `faker.js` upstream):

https://github.com/bchavez/Bogus/blob/59985ee11fb2a34b89d940d5da8b34617f6f9f6f/Source/Bogus/data/en.locale.json#L20620-L20714

You have a few choices:
* Make your own dataset with vehicle data more attuned to your own scenario. See: https://github.com/bchavez/Bogus/tree/master/Examples/ExtendingBogus
* Try requesting data change upstream in `faker.js`: https://github.com/faker-js/faker  
  note: once your change is modified upstream in `faker.js` there is a possibility to update Bogus and port over any new code for the update with better vehicle matches.
