### ISSUE TITLE
IPFS is using real images with no sign of consent? Maybe use faked images

### ISSUE THREAD

**Issue by dmadisetti** [bchavez/Bogus#410]
I could copy and paste, or see https://github.com/faker-js/faker/issues/465
But I think collectively as the faking/bogus community, you should work this out

**Comment by bchavez** [comment]
Hi, we are using the same ones uifaces.com and `marak/faker.js` were using. Since we're a port of `faker.js`, generally we consume updates from upstream `faker-js` as needed. Feel free to raise the issue upstream.
