### ISSUE TITLE
Allow for different Pseudo Random Number Generators (PRNGs)

### ISSUE THREAD

**Issue by DaveRMaltby** [bchavez/Bogus#411]
### Please describe why you are requesting a feature
Different [PRNGs](https://www.geeksforgeeks.org/pseudo-random-number-generator-prng/) have different tradeoffs on CPU, memory and distribution of results.  Bogus is currently bound to using the [.NET Random class](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-6.0) which is constrained to only one PRNG algorithm (See remarks of the previous link).  Bogus is designed in such a manner that adding this feature requires minimal changes.

### Please provide a code example of what you are trying to achieve

```
namespace Bogus
{
   public interface IRandom
   {
      int Next();
      int Next(int minValue, int maxValue);
      void NextBytes(byte[] buffer);
      double NextDouble();
   }

   internal class RandomWrapper : IRandom
   {
      private readonly Random random;

      public RandomWrapper(Random random)
      {
         this.random = random ?? throw new ArgumentNullException(nameof(random));
      }

      public int Next()
      {
         return random.Next();
      }

      public int Next(int minValue, int maxValue)
      {
         return random.Next(minValue, maxValue);
      }

      public void NextBytes(byte[] buffer)
      {
         random.NextBytes(buffer);
      }

      public double NextDouble()
      {
         return random.NextDouble();
      }
   }

   public class Randomizer
   {
...

//CHANGED from the data type Random
      private readonly IRandom localSeed;

      public Randomizer()
      {
//CHANGED
         this.localSeed = new RandomWrapper(Seed);
      }

      public Randomizer(int localSeed)
      {
//CHANGED
         this.localSeed = new RandomWrapper(new Random(localSeed));
      }

...
      /// <summary>
      /// Constructor that uses <see cref="random"/> parameter interface as an abstraction for Random.
      /// Completely ignores the global static <see cref="Seed"/>.
      /// </summary>
      public Randomizer(IRandom random)
      {
         this.localSeed = random;
      }
...
   }
}

namespace Bogus.Tests
{
      private class PseudoRandomNumberGenerator : IRandom
      {
         public int Next() => (int)(DateTime.Now.Ticks & 0xFFFFFFFFL);
         public int Next(int minValue, int maxValue) => Next() % (maxValue - minValue) + minValue;
         public void NextBytes(byte[] buffer) => throw new NotImplementedException();
         public double NextDouble() => throw new NotImplementedException();
      }

      [Fact]
      public void custom_random_interface()
      {
         var nameAlg = new DataSets.Name();
         nameAlg.Random = new Randomizer(new PseudoRandomNumberGenerator());

         var firstName = nameAlg.FirstName();
      }
}
```

NOTE:  The PRNG here (called PseudoRandomNumberGenerator) is only for simplicity and does not at all represent the standard or custom PRNGs that I'd like to use in my final code.

### Please answer any or all of the questions below

* Is the feature something that currently cannot be done?
Yes.  The .NET Random class is used directly in the Bogus' Randomizer class.  The final Pull Request will abstract that into an interface as shown in the code example above.

* What alternatives have you considered?
Forking a personal copy of Bogus for modification.  I currently see no workaround without modifying a copy of the Bogus source code and compiling on my own.

* Is this feature request any issues or current problems?
Not that I'm aware of.

* Has the feature been requested in the past?
The closest issues that I can find deal with work at optimizing Bogus algorithms or deal with the lack of currency support in Microsoft's Random class.

**If the feature request is approved, would you be willing to submit a PR?**
Yes.  I already have a working solution and will provide some unit tests as well.

**Comment by bchavez** [comment]
Fixed in #413

**Comment by bchavez** [comment]
@DaveRMaltby, new version released with your PR changes: https://www.nuget.org/packages/Bogus/34.0.2

thanks again for the help!

**Comment by DaveRMaltby** [comment]
Thank you sir!  I'm glad now to be able to return to your NuGet package.  I really like your work here.  If you need some help on stuff keep me in mind.  Again, appreciate it!
