### ISSUE TITLE
Person gender

### ISSUE THREAD

**Issue by tcartwright** [bchavez/Bogus#423]
Please add a ctor that allows the gender to be specified when creating a new Person like so: Person(string locale, Name.Gender gender).

**Comment by bchavez** [comment]
Hello, thank you for creating an issue. You'll need to
  1. create a factory method, or 
  2. inherit from `Bogus.Person`, or
  3. override `Person.Populate()` with your desired implmentation.

For example, option 2):

```csharp
void Main()
{
   var male = new Person2(Name.Gender.Male);
   male.Dump();
}

public class Person2 : Bogus.Person
{
   public Person2(Name.Gender gender, string locale = "en") : base(locale)
   {
      this.Gender = gender;
      this.FirstName = this.DsName.FirstName(this.Gender);
      this.LastName = this.DsName.LastName(this.Gender);
      this.FullName = $"{this.FirstName} {this.LastName}";
      
      this.UserName = this.DsInternet.UserName(this.FirstName, this.LastName);
      this.Email = this.DsInternet.Email(this.FirstName, this.LastName);
   }
}
```

![image](https://user-images.githubusercontent.com/478118/166838682-1155d15f-1bd9-4355-8331-eaf5d3496221.png)
