### ISSUE TITLE
Where are the en_US phone number formats?

### ISSUE THREAD

**Issue by jmenashe** [bchavez/Bogus#424]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  | v34.0.2 build 1173 |
| .NET Core?                   |   6.0            |
| .NET Full Framework?   |     4.8          |
| Windows OS?              |        Win10 x64       |
| Linux OS?                    |      Ubuntu    22.04        |
| Visual Studio?              |     VS2022 Version 17.1.5          |

### What locale are you using with Bogus?
en_US

### What's the problem?
There are no phone number formats defined.

### What possible solutions have you considered?
Searching exhaustively through GitHub for terms like "phone", "formats", "###-###-####",  etc.

### Do you have sample code to show what you're trying to do?
Same thing as every other country. For example, formats are defined in the [en_GB.locale.json](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/data/en_GB.locale.json#L104-L118) file.

**Comment by bchavez** [comment]
If `phone_number.formats` is not defined in the _specific_ and _specified_ locale (eg: `en_US`); then **Bogus** **_always_** falls back to the `en` locale using `phone_number.formats` as defined here:

https://github.com/bchavez/Bogus/blob/e29f0205f6af6d736570646f4b08231eda6dba19/Source/Bogus/data/en.locale.json#L7677-L7700
