### ISSUE TITLE
The locale 'en-CA' does not exist.

### ISSUE THREAD

**Issue by loukaspd** [bchavez/Bogus#444]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  | 34.0.2                |
| .NET Core?                   | 6.0                |

I'm trying to use bogus with locale `en-CA` but I get the following error:  
```C#
Bogus.BogusException: The locale 'en-CA' does not exist. To see all available locales visit https://github.com/bchavez/Bogus.
   at Bogus.DataSet..ctor(String locale)
   at Bogus.DataSets.Address..ctor(String locale)
   at Bogus.Faker..ctor(String locale)
```

The error appears when I'm trying to instantiate the `Faker` class with this locale:  
```C#
var faker = new Faker("en-CA");
```

**Comment by bchavez** [comment]
Use an underscore, not a hyphen as shown below:
```csharp
void Main()
{
   try {
      var f1 = new Faker("en_CA");
      f1.Address.State().Dump();
   }
   catch {
      "Underscore 'en_CA' doesn't work".Dump(); 
   }

   try
   {
      var f2 = new Faker("en-CA");
      f2.Address.State().Dump();
   }
   catch {
      "Hyphen 'en-CA' doesn't work".Dump();
   }
}
```

![image](https://user-images.githubusercontent.com/478118/191628719-ae8dfa55-e253-4864-bc08-3f9a6791ba8f.png)
