### ISSUE TITLE
Bogus generates invalid VINs. VIN can't contain letters I, O and Q

### ISSUE THREAD

**Issue by andrey-shvets** [bchavez/Bogus#449]
https://eu.statesman.com/story/news/2012/09/25/what-the-vin-tells-you-about-your-vehicle/9848258007/

According to federal law, the VIN must appear on a part of the vehicle that won’t be removed. Each character in the VIN must be either a letter from the alphabet or a number from 0 through 9. They cannot contain the letters I, O or Q to help cut down on mistaken characters. VINs appear on the left side of the dash and must be visible through the windshield. The VIN is also stamped on the frame and other locations in case of a fire.

https://github.com/bchavez/Bogus/blob/b9049abf8b40203c09079741bcb328da95899f81/Source/Bogus/DataSets/Vehicle.cs#L13-L23

**Comment by skwasjer** [comment]
@andrey-shvets I submitted #421 addressing this a few months prior to your OP but received no response yet.
