### ISSUE TITLE
Possible deadlock during populate internal

### ISSUE THREAD

**Issue by Mpdreamz** [bchavez/Bogus#46]
We use bogus in our unit/integration tests to generate fake data and sometimes we see the runner never completing and usually the pending threads look very similar to this:

![image](https://cloud.githubusercontent.com/assets/245275/20961661/3d8f7e5e-bc66-11e6-9638-04521a30e20d.png)

The lock here: https://github.com/bchavez/Bogus/blob/198bf735aeb4e7ab063b3ec38a1d28be193da11c/Source/Bogus/Faker%5BT%5D.cs#L228

which directs to:

https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Randomizer.cs#L22

feels like the culprit but have not spend enough time on it but it looks like that object does not need to be lazy?

**Comment by bchavez** [comment]
Hi @Mpdreamz ,

Sorry about the trouble you're having. I wrote a few unit tests to try to simulate a deadlock; however, I'm not able to reproduce the behavior you're seeing.

Is this in the [`elasticsearch-net`](https://github.com/elastic/elasticsearch-net) repo? Is it easy to run unit tests? Is there anything special I need to run the unit tests?

Thanks,
Brian

**Comment by Mpdreamz** [comment]
Hi @bchavez 

It is yeah, you should be able to clone it and checkout the https://github.com/elastic/elasticsearch-net/tree/5.0.0-rc4 tag and run `build` from the commandline. This will build and run the unit tests. 

The deadlock does not happen always, as deadlocks tend to do. It doesn't even happen often enough for us to get into gear but when it does it tends to happen constantly during that period.

I do think having the lazy execute with `ExecutionAndPublication` be a safer option so no synchronization has to happen on the winning threads returned `object` that everyone wants to lock on.

**Comment by bchavez** [comment]
Hey @Mpdreamz ,

I think you're right. I was able to reproduce the issue with the `elasticsearch` repo. Seems like there was quite a few `static` field `Faker` initializations that were being fired up at the same time.

I changed the locker to `ExecutionAndPublication` and it seemed to solve the issue after running the elasticsearch unit tests a few times now.

Please feel free to re-open the issue if you run into the issue again.

[**Bogus** `v8.0.2`](https://www.nuget.org/packages/Bogus/8.0.2) with the `ExecutionAndPublication` should available soon as it gets indexed shortly.

Thanks,
Brian

**Comment by Mpdreamz** [comment]
Awesome thanks Brian!
