### ISSUE TITLE
Is it possible to have default behaviour for properties not defined?

### ISSUE THREAD

**Issue by Ian1971** [bchavez/Bogus#47]
For example on quite a wide class I only really want to define a rule for a couple of properties and and the rest can be random strings.
So something like

`faker.DefaultRuleFor<string>(f => "a string")`

**Comment by bchavez** [comment]
Related #38 

Feature is now implemented in [`v8.0.3`](https://www.nuget.org/packages/Bogus/) available on NuGet soon. The new method is:

`RuleForType(typeof(string), f => "a string")`

Thanks!
:headphones: :notes: [***Antiserum & Mayhem - Trippy***](https://www.youtube.com/watch?v=o95ZTp5fuF8)
