### ISSUE TITLE
Add Extensions.Romanian

### ISSUE THREAD

**Issue by totpero** [bchavez/Bogus#477]
### Please describe why you are requesting a feature
Add Romanian CNP Generator for person
https://ro.wikipedia.org/wiki/Cod_numeric_personal_(Rom%C3%A2nia)

### Please provide a code example of what you are trying to achieve
I already create pull request for this implementation here https://github.com/bchavez/Bogus/pull/466

### Please answer any or all of the questions below

* Is the feature something that currently cannot be done?
No

* What alternatives have you considered?
None

* Has the feature been requested in the past?
No

**If the feature request is approved, would you be willing to submit a PR?**
YES

**Comment by totpero** [comment]
I add pr here https://github.com/bchavez/Bogus/pull/466

**Comment by bchavez** [comment]
Fixed by PR #466.

Bogus `v35.3.2` contain Romanian CNP:
* https://www.nuget.org/packages/Bogus/35.3.2

Thanks,
Brian
