### ISSUE TITLE
Update link to faker.js in Creating Locales Wiki page

### ISSUE THREAD

**Issue by AlexRadch** [bchavez/Bogus#478]
Update link to faker.js in [Creating Locales Wiki page](https://github.com/bchavez/Bogus/wiki/Creating-Locales) to https://github.com/faker-js/faker/tree/5478d65dcb99a3c5f1a941d6a9d101d02bc467c2

**Comment by bchavez** [comment]
Awesome. Thanks for GH issue; Wiki should be updated now:
* https://github.com/bchavez/Bogus/wiki/Creating-Locales
