### ISSUE TITLE
Generating a deep object graph based on rules

### ISSUE THREAD

**Issue by CNBoland** [bchavez/Bogus#495]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  | 34.0.2 |
| .NET Core?                   | .NET 6 |
| Windows OS?              | Windows 10 |
| Visual Studio?              | VS 2022 |

Given the following class structure, how can an instance of the top level class (C) be generated? I'm using `.RuleForType()` rules, but don't see a way to generate the subject of those rules.

```
class A
{
    public string Value { get; set; }
}

class B
{
    public A A { get; set; }
}

class C
{
    B B { get; set; }
}

class CFaker : Faker<C>
{
    public CFaker()
    {
        RuleForType(typeof(A), f => new A { Value = f.Random.AlphaNumeric(5) });
        // How to construct type A using existing rules?
        //RuleForType(typeof(B), f => new B { A = f.Generate<A>() });
    }
}

var c = new CFaker().Generate();
Debug.Assert(c.B != null, "B is null.");
Debug.Assert(c.B.A != null, "B.A is null.");
Debug.Assert(c.B.A.Value != null, "B.A.Value is null.");
```

**Comment by bchavez** [comment]
When you call `Faker<T>.RuleForType()`; it strictly applies to the immediate and top-level declared types of properties or fields of `T`.

That is, if `C.B.A` and `Faker<C>.RuleForType(A)`; `C` has no immediate field or property of type `A` and is only indirectly related to `A` via type of `B`.

In other words,

```csharp
void Main()
{
   var c = new CFaker().Generate();
   Debug.Assert(c.B != null, "B is null.");
   Debug.Assert(c.B.A != null, "B.A is null.");
   Debug.Assert(c.B.A.Value != null, "B.A.Value is null.");
   c.Dump();
}

class A
{
   public string Value { get; set; }
}

class B
{
   public A A { get; set; }
}

class C
{
   public B B { get; set; }
}

class CFaker : Faker<C>
{
   public CFaker()
   {
      var bFaker = new BFaker();
      RuleForType(typeof(B), f => bFaker.Generate());
   }
}
class BFaker : Faker<B>
{
   public BFaker()
   {
      RuleForType(typeof(A), f => new A { Value = f.Random.AlphaNumeric(5) });
   }
}
```

![image](https://github.com/bchavez/Bogus/assets/478118/3e83d4be-4eed-4a6b-ae03-8fdb3c249348)
