### ISSUE TITLE
Xamarin fails to publish due to Nordic characters in Method names

### ISSUE THREAD

**Issue by takthetank** [bchavez/Bogus#497]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |        34.0.2         |
| .NET Core?                   |        Xamarin with  .Net Standard 2.1        |
| .NET Full Framework?   |        -         |
| Windows OS?              |          10        |
| Linux OS?                    |         -         |
| Visual Studio?              |         17.7.3 (2022)         |

### What locale are you using with Bogus?
Default, EN.
### What is the expected behavior?
When compiling a Xamarin.Forms bundle for Android, it should compile successfully. 
### What is the actual behavior?
Compilation fails due to weird Scandinavian characters in some methods.
![image](https://github.com/bchavez/Bogus/assets/6099270/9b058f2f-dd33-4434-8c74-d47caa283904)

### Please provide a stack trace.
(Does not apply)
### Any possible solutions?
Rename these methods to include plain latin characters.
### How do you reproduce the issue?
Use the library in a Xamarin.Forms Android project and create a bundle for publishing.
### Do you have a unit test that can demonstrate the bug?
(Does not apply)
### Can you identify the location in Bogus' source code where the problem exists?
[Bogus.Extensions.Finland.ExtensionsForFinland.Henkilötunnus()](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Extensions/Finland/ExtensionsForFinland.cs)
[Bogus.Extensions.Norway.ExtensionsForNorway.Fødselsnummer()](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Extensions/Norway/ExtensionsForNorway.cs)
### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by bchavez** [comment]
Hm. Wow. Pretty interesting bug report. Thank you for the report. Looks like we'll have to work on removing those glyphs in method names.

**Comment by bchavez** [comment]
The issue should be fixed in `Bogus v35.2.0`:
* https://www.nuget.org/packages/Bogus/35.2.0

Thanks again for the report.
