### ISSUE TITLE
.Net CORE support?

### ISSUE THREAD

**Issue by bigteejay** [bchavez/Bogus#50]
I'm about to try it anyways, but figured I would ask so that it could be documented should any others happen by with the same question.

**Comment by bchavez** [comment]
.NET Core is already supported. See the NuGet page here: https://www.nuget.org/packages/Bogus/, `.NETStandard 1.3`

-Brian
:car: :police_car: :rotating_light: ***["Drive it like you stole it..."](https://www.youtube.com/watch?v=dd00Qh9yZUg)***

**Comment by bigteejay** [comment]
Doh, that was exactly the page I was looking at and somehow managed to miss it.  You're absolutely correct, it is clearly stated there.  Thanks!
