### ISSUE TITLE
Faker.Tv() is missing from Bogus.Hollywood

### ISSUE THREAD

**Issue by Mathiasw** [bchavez/Bogus#505]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |       34.0.2          |
| .NET Core?                   |         6.0        |
| .NET Full Framework?   |                 |
| Windows OS?              |    Nope !             |
| Linux OS?                    |     Nope!             |
| Mac OS?                    |     Sonama  14.0           |
| Visual Studio?              |     Rider 2023.3.2             |

### What locale are you using with Bogus?

Default english - en-US I guess?

### What is the expected behavior?

Faker.Tv() is not in the library. I think it's missing (I have a premium licence).

### What is the actual behavior?

This compiles:

        var movieReviews = Enumerable.Range(0, 10)
            .Select(_ => $"{f.Movies().MovieTitle()} is terrible, {f.Movies().ActorName()} was awful in it. {f.Movies().Production()} should be ashamed")
            .ToList();

I can't compile this:

        var tvReviews = Enumerable.Range(0, 10)
            .Select(_ => $"I have just finished watching {f.Tv().Series()}, {f.Tv().ActorName()} was awful in it. {f.Tv().Production()} should be ashamed")
            .ToList();

### Please provide a stack trace.

Didn't compile.

### Any possible solutions?

Nope. I have Bogus, Bogus.text and Bogus.Hollywood installed. Movies() works fine, Tv() can't be found.

### Can you identify the location in Bogus' source code where the problem exists?

Sorry, no. I had a look but to no avail.

### If the bug is confirmed, would you be willing to submit a PR?

Yes or No?

yes.

**Comment by bchavez** [comment]
Ah yeah, looks like I forgot an extension method to create the TV dataset; I'll try to get a fix out today. Thank you for the bug report.

![image](https://github.com/bchavez/Bogus/assets/478118/996998f9-ba69-4134-93ca-7d6e6469c120)

**Comment by bchavez** [comment]
Hello, the `Bogus.Hollywood` should be fixed now; `v9` premium packages released:

* https://www.nuget.org/packages/Bogus.Healthcare/34.0.2.9
* https://www.nuget.org/packages/Bogus.Healthcare/34.0.2.9#release-body-tab

![image](https://github.com/bchavez/Bogus/assets/478118/79ce925c-9395-4e98-80b0-3cc6b491bb36)

![image](https://github.com/bchavez/Bogus/assets/478118/0b474040-a348-41d1-b13e-2d31bbd9966e)

Please let me know if that fixes the problem.

Thanks again for your OSS support.

-Brian

**Comment by Mathiasw** [comment]
Works great now, thanks for the quick fix, especially at the weekend. Now please go out and pay a bit instead of writing code at the weekend!
