### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by Duetting** [bchavez/Bogus#52]
The assembly is missing a strong name at the moment, so it can't be used in assemblies that are themselves strong named.
All our assemblies have a strong name as company policy, so at the moment we always have to recompile and can't use the nuget package.

**Comment by bchavez** [comment]
Hi @Duetting ,

Starting with [`v9.0.1`, **Bogus**](https://www.nuget.org/packages/Bogus/9.0.1) is now strongly named / signed. Enjoy.

```
R:\Bogus.9.0.1\lib\net40>sn -Tp Bogus.dll

Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000001000100d981a0be5616f4
50cc0528f88cf96e7bb782edb8ea9a06517cc42b340cdd644a931aab0c7c4902c129eff3d09a3f
8c331026286d55c36f225f33f4709be9352fdf16c7b6781652528c2b77063f19a6ab21ee79368f
552f60da8f503832e2d6ab6aafce934cc8736c24fd391ac286aa14dd5b5959fa546eb25841e41c
fb625aa2

Public key token is fa1bb3f3f218129a

R:\Bogus.9.0.1\lib\net40>sn -vf Bogus.dll

Assembly 'Bogus.dll' is valid

R:\Bogus.9.0.1\lib\net40>
```

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***
