### ISSUE TITLE
LoremPixel service does not exist anymore and should be removed

### ISSUE THREAD

**Issue by marijnz0r** [bchavez/Bogus#555]
### Bogus NuGet Package

v35.5.1 build 1436

### .NET Version

.NET 8

### Visual Studio Version

17.8

### What operating system are you using?

Windows

### What locale are you using with Bogus?

en_GB

### Problem Description

https://lorempixel.com/ does not exist anymore.
Suggestion: remove it from the codebase as it is obsolete for a long time already.

### LINQPad Example or Reproduction Steps

-

### Expected Behavior

-

### Actual Behavior

-

### Could you help with a pull-request?

Yes

**Comment by bchavez** [comment]
Hi @marijnz0r , thank you for the PR. A new release has been made with your changes:
* https://www.nuget.org/packages/Bogus/35.6.0
