### ISSUE TITLE
Set License expression rather than URL

### ISSUE THREAD

**Issue by thompson-tomo** [bchavez/Bogus#573]
### Description

**Is your feature request related to a problem? Please describe.**
The licence type is not being populated on nuget & in the cyclonedx bom

**Describe the solution you'd like**
I would like the the license expression property to be populatedas part of the nuget package

**Additional context**
Name should be: MIT

### LINQPad Code Example

n/a

### What alternatives have you considered?

n/a

### Could you help with a pull-request?

Yes

**Comment by bchavez** [comment]
Hello. Thank you for the GH issue, we have an open issue that should be tracking the updated NuGet license metadata here: https://github.com/bchavez/Bogus/issues/499

I plan on fixing this soon in the next few weeks. If there's anything very specific to your request that is not listed in GH #499, please add a comment in #499.

Thanks,  
Brian
