### ISSUE TITLE
Request for cancellation not honoured

### ISSUE THREAD

**Issue by tombiddulph** [bchavez/Bogus#576]
### Bogus NuGet Package

none

### .NET Version

none

### Visual Studio Version

none

### What operating system are you using?

Other

### What locale are you using with Bogus?

none

### What's the problem?

I emailed `support@bitarmory.com` on 1/12/23 with a request to cancel my subscription. The email wasn't responded to and I've now been charged again. Please can you cancel my subscription and refund the latest payment taken from me.

I've emailed `support@bitarmory.com` again today as the form on the website has a character 255 character limit for the message box.

### Provide LINQPad Example

n/a

### What other possible solutions or alternatives have you considered?

n/a

**Comment by bchavez** [comment]
Hello,

Hm. There is no record of your email cancellation in 2023 (1/12/2023)

![image](https://github.com/user-attachments/assets/15e0bd4a-3558-464f-8558-3b38c9b988a5)

Only one payment message in 2023: 

![image](https://github.com/user-attachments/assets/b1a681d1-412e-41b5-a4e8-cc0ffee942c6)

Additionally, nothing in spam:

![image](https://github.com/user-attachments/assets/40622807-cfe5-47b1-a356-d62da47d14fe)

The only record of cancellation request is today, 12/1/2024 at 12:03 PM:

![image](https://github.com/user-attachments/assets/fd7b4865-56d4-4006-995a-16d45defd30d)

If you get a chance, please post a screenshot along with the **_original_** SMTP headers that show you sent an email on 1/12/2023 so I can try to track down what went wrong with your original email cancellation.

------

Regardless, I've processed the subscription cancellation and issued a refund for the most recent transaction:

![image](https://github.com/user-attachments/assets/25a4bd03-f046-4d7c-9881-4bcc49a5ecd4)

![image](https://github.com/user-attachments/assets/d207ae36-a70a-4cd4-b1a9-1a45f2f2b6a0)
