### ISSUE TITLE
Define Hashids options in Faker

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#61]
Would it be possible to make available HashIds options

    public Hashids(string salt = "", int minHashLength = 0, string alphabet = DEFAULT_ALPHABET, string seps = DEFAULT_SEPS)

As faker options:

    Faker.Hashids.Settings = new HashidsSettings {       
        Alphabet = "abcd";
    }

So in this case the alphabet "abcd" would be used along with the other default options already defined in Hashids.

Thank You,
Miguel

**Comment by bchavez** [comment]
Hi Miguel, hope you are well.

I'm not sure it's a good idea to start managing an API options interface for `hashids`. However, you could use a base/derived faker to accomplish your specific goals:
```
public class BaseFaker<T> : Faker<T> where T : class 
{
    public BaseFaker()
    {
        this.FakerHub = new Faker
            {
                Hashids = new Hashids(alphabet: "abcd")
            };
    }
}
```
:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by mdmoura** [comment]
Hi, how are you,

Yes, that was one option I considered but I would prefer not having a derived class.

I understand your opinion of not managing Hashids API options in Faker but at the same time you included Hashids directly into Faker source ... Wouldn't be a better idea to have a package like Fakers.Hashids which would add Hashids to Faker with full options?

And when I mean Faker.Hashids I would also mean other extensions to Faker that would rely on other projects keeping the Faker code "clean" and yet adding other options to Faker.

No?

Thank You

**Comment by bchavez** [comment]
Hi Miguel, I'm doing good. Thanks.

Not wanting to derive from `Faker<T>` is understandable. But to be honest, that was one of the reasons why I opened up so many internal variables of `Faker<T>` so that it could be derived from for special cases like this one.

Yeah, Hashids was added from source (I forgot the original reason why I added Hashids in the first place), but I think it had to do with .NET Core support. Originally, Hashids didn't work with .NET Core at the time and I had already made modifications to make Hashids compatible. So, I kinda threw it in Bogus and now kinda regret it. I think some day I will remove Hashids when I find a better way to expose `Faker<T>.FakerHub` as a strongly typed facade. Possibly if C# language ever gets **Extension Properties**, that would be really cool.

For now though, I would say derive from `Faker<T>` is the best workaround for now. I think I might add a state dictionary to `FakerHub` nearterm help with cases like this. It would allow C# **Extension Methods** to extend `Faker<T>.FakerHub` by storing state associated with `FakerHub`. Like this:

```
public class SomeUser
{
    public string Id { get; set; }
    public int TrackingNumber { get; set; }
}

[Test]
public void allow_storing_state_from_extension_method()
{
    var faker = new Faker<SomeUser>()
        .RuleFor(o => o.Id, f => f.Hashids().Encode(  f.Random.Digits(3)  ))
        .RuleFor(o => o.TrackingNumber, f => f.Random.Number(3));

    faker.Generate(5).Dump();
}

public static class HashidsExtension
{
    public static Hashids Hashids(this Faker fakerHub)
    {
        return fakerHub.GetState<Hashids>("hashid_extension") ??
               fakerHub.SaveState("hashids_extension", new Hashids(alphabet: "~!@#$%.&*()_+-=;<>"),
                   ExpireState.Never);
    }
}
```
And my quick hack works :smile: :+1: 
```

[
  {
    "Id": "_<~*!>",
    "TrackingNumber": 2
  },
  {
    "Id": "-(~*~)",
    "TrackingNumber": 2
  },
  {
    "Id": "+>$+#_",
    "TrackingNumber": 0
  },
  {
    "Id": "*<!*%&",
    "TrackingNumber": 0
  },
  {
    "Id": "+<!<#-",
    "TrackingNumber": 3
  }
]
```
I'll have to think about this a little more.

:crescent_moon: :stars: ***["Nothing good happens past 2am..."](https://www.youtube.com/watch?v=VOlcDBXKhSU)***

**Comment by mdmoura** [comment]
I believe you added Hashids by my suggestion when I needed something to be unique, for example a name, but not using a number. So by doing Hashids.Encode(UniqueIndex) you get exactly that ...

It just feels strange to have Hashids directly into Fake and not being able to define its settings.

Yes, FakerHub might be a solution ... Since the beginning I feel Bogus could have better defined extension points ... But that is just an idea.

**Comment by bchavez** [comment]
Ah, yea, that's right, It was a long time ago Miguel. :+1: 

So, I was playing around, refactored `Faker<T>` to add `Faker<T, HubT>`, so, we can also get something like this:
```
[Test]
public void can_extend_faker_hub_with_extension_method()
{
    var faker = new Faker<SomeUser>()
        .RuleFor(o => o.Id, f => f.Hashids().Encode(f.Random.Digits(3)))
        .RuleFor(o => o.TrackingNumber, f => f.Random.Number(3));

    faker.Generate(5).Dump();
}

[Test]
public void can_extend_faker_hub_with_generic_type_param()
{
    var faker = new Faker<SomeUser, CustomHub>()
        .RuleFor(o => o.Id, f => f.Hashids.Encode(f.Random.Digits(3)))
        .RuleFor( o => o.TrackingNumber, f => f.Random.Number(3));

    faker.Generate(5).Dump();
}

public class CustomHub : Faker
{
    public CustomHub()
    {
        this.Hashids = new Hashids(alphabet: "~!@#$%.&*()_+-=;<>");
    }

    public Hashids Hashids { get; set; }

    //[RegisterMustasheMethods]
    //public CustomDataSet {get; set;} = new CustomDataSet();
}

public static class ExtensionForFaker
{
    public static Hashids Hashids(this Faker fakerHub)
    {
        return fakerHub.GetState<Hashids>("hashid_extension") ??
               fakerHub.SaveState("hashids_extension", new Hashids(alphabet: "~!@#$%.&*()_+-=;<>"),
                   ExpireState.Never);
    }
}
```

The first one uses C# **Extension Methods** as a way to customize `FakerHub`, and the second uses an extra **Generic Parameter** on `Faker<T, THub>`. Of course, the default `Faker<T>` will always be available. Which method of extending `TFakerHub` do you like more?

The one advantage **Generic Parameter** of `FakerHub` has over **Extension Methods** is the ability to use `[RegisterMustasheMethods]` that can automatically register `CustomDataSet.Methods` that have default/zero parameters so, something like this is also possible when parsing mustaches: `"hello {{customdataset.method}}`

Pretty cool. Dunno, maybe we could have both ways. Gotta think more about it though.

:dancer: :heart: **[Mark Knight & Adrian Hour feat Indiana - Dance On My Heart](https://www.youtube.com/watch?v=S1W5rUok9MM)**

**Comment by mdmoura** [comment]
I think the second approach, e.g. 

    var faker = new Faker<SomeUser, CustomHub>()

seems more clear of what is going on ...

**Comment by bchavez** [comment]
Yea, but also requires deriving from `Faker` for it to work :/
`public class CustomHub : Faker`



:grey_question: :microphone: ***["Where it's at... I got two turntables and a microphone"](https://www.youtube.com/watch?v=EPfmNxKLDG4)***

**Comment by mdmoura** [comment]
Yes, that is not very nice ... 

What comes to mind, but maybe it is a big change, is make easy to create plugins extending Fake base functionality. Each plugin would need to implement two parts:

1. Extension method so it can be applied as it is now:
    .RuleFor(o => o.Id, f => f.CustomPluginMethod())

2. A class where the plugin settings are defined so when the plugin is added to Fake those default settings would also be applied.

    Bogus.Plugins.Add(new CustomPlugin { FirstDefaultValue = 1 })

The extension methods in each plugin would extend something in Fake. And they would take their default values from a plugin settings class which would implement an Interface defined in Bogus IPluginSettings.

This is just an idea ... Didn't look at the code yet.

**Comment by bchavez** [comment]
Hi @mdmoura ,

Your other issue #65 gave me an idea about a possible solution to "*extending*" Bogus. You can use `using static` to "*extend*" the fluency of the `RuleFor`. It's not really "*extending*" Bogus per se but gives you a very good feel for writing `RuleFor`s with custom data generators. Here's an example with your `Hashids` customization:
```
using NUnit.Framework;
using static Bogus.Tests.GitHubIssues.Issue61.HashIdExtension;

namespace Bogus.Tests.GitHubIssues
{
    public class Issue61
    {
        public static class HashIdExtension
        {
            public static Hashids Hashid { get; set; }
        }

        [Test]
        public void can_have_custom_hashid_extension()
        {
            //Custom
            Hashid = new Hashids(alphabet: "~!@#$%.&*()_+-=;<>");

            var faker = new Faker<SomeUser>()
                .RuleFor(o => o.Id, f => Hashid.Encode(f.Random.Digits(3)))
                .RuleFor(o => o.TrackingNumber, f => f.Random.Number(3));

            faker.Generate(5).Dump();
        }

        public class SomeUser
        {
            public string Id { get; set; }
            public int TrackingNumber { get; set; }
        }
    }
}
```
```
{
  "Id": "+>$(!*",
  "TrackingNumber": 3
},
{
  "Id": ";<~&@>",
  "TrackingNumber": 0
},
....
```
I think this is a much better solution than the **extension state** solutions I previously tried.  I think this is how we're going to go forward in the future with "how do I extend Bogus". I like this solution so much I'm thinking of deprecating `f => f.Hashids` and going with a `using static` solution.

Thanks,
Brian

**Comment by mdmoura** [comment]
@bchavez I also like that option ... I just don't like very much having `using static` but probably that is just me ... I am using it as follows:

    public static partial class Bogus {

        public static Hashids Hashids { get; set; }

        public static String Dummy(this Images images, Int32 width = 640, Int32 height = 480) {
            // Extension code   
        }

        // Other extensions
      }

Then I can use the extensions as before or Hashids similar to your suggestion:

    .RuleFor(x => x.Name, f => Bogus.Hashids.Encode(f.IndexGlobal))

I used it as a partial class because I can have extensions defined on a base library and on a main project. I named the class Bogus to keep it short. And in fact it works because you only have a Namespace. 

Well at least it works for me ...
