### ISSUE TITLE
Sentence with minimum and maximum random of words

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#62]
I need to create a sentence with 2 to 4 random words. I read the following:

    Sentence - Get a random sentence. Default minimum of 3 words but at most 10 words (range = 7). If you want a sustenance with 5 words always call Sentence(5, range: 0);

Maybe I am missing something but it seems range is not being used ... Is it?

How can I define a minimum and maximum number of random words to be created in a sentence?

**Comment by bchavez** [comment]
Thanks for catching that omission Miguel. [`v11.0.3`](https://www.nuget.org/packages/Bogus/11.0.3) is out with your fix.

See: https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/LoremTests.cs#L70

The API should be: `.Sentence(exactWordCount, rangeFrom0ToN)`

:clubs: :game_die: ***["I'm just doing ma thang, you know the Units the game..."](https://www.youtube.com/watch?v=ngH0fkiNo-g#t=30s)***

**Comment by mdmoura** [comment]
Thanks
