### ISSUE TITLE
Get unique global values for child property

### ISSUE THREAD

**Issue by mdmoura** [bchavez/Bogus#66]
I have the following:

        Faker<ProductI18N> productsI18N = new Faker<FoodI18N>()
          .RuleFor(x => x.Name, y => $"{y.Lorem.Word()} {y.Hashids.Encode(y.IndexGlobal)}");

        List<Product> products = new Faker<Product>()
          .RuleFor(x => x.ProductsI18N, () => productsI18N.Generate(2).ToList())
          .RuleFor(x => x.IsApproved, x => x.Random.Bool())
          .Generate(2000).ToList();

Each ProductI18N should have an unique name that is why I added:

        $"{y.Lorem.Word()} {y.Hashids.Encode(y.IndexGlobal)}")

However I get duplicates ... Why? How to overcome this?

**Comment by bchavez** [comment]
Hi @mdmoura ,

First, the code you've posted in the issue doesn't compile. Please submit something that can compile on my end otherwise, it's very hard to figure out what's going on with your code.

Also, not sure how you're getting duplicates because the following unit test passes:
```
[Test]
public void issue_66_unique_global_values()
{
    var productsI18N = new Faker<FoodI18N>()
        .RuleFor(x => x.Name, y => $"{y.Lorem.Word()} {y.Hashids.Encode(y.IndexGlobal)}");

    List<Product> products = new Faker<Product>()
      .RuleFor(x => x.ProductsI18N, () => productsI18N.Generate(2).Cast<ProductI18N>().ToList() )
      .RuleFor(x => x.IsApproved, x => x.Random.Bool())
      .Generate(2000).ToList();

    products.SelectMany(p => p.ProductsI18N)
        .Cast<FoodI18N>()
        .Select(i8 => i8.Name).Distinct().Count().Should().Be(4000);
}
public class Product
{
    public List<ProductI18N> ProductsI18N { get; set; }
    public bool IsApproved { get; set; }
}
public class FoodI18N : ProductI18N
{
    public string Name { get; set; }
}

public class ProductI18N
{
}
```
I would like to ***recommend*** to write a failing unit test in the [test project here](https://github.com/bchavez/Bogus/tree/master/Source/Bogus.Tests) with what the expected result should be. It would greatly help me reproduce the issue you are seeing.

Thanks,
Brian

:man: :checkered_flag: ***["Louie Louie, oh no... Me gotta go... Aye-yi-yi-yi, I said"](https://www.youtube.com/watch?v=4V1p1dM3snQ)***

**Comment by mdmoura** [comment]
@bchavez sorry that my code did not compile. I am posting new one:

    public class Product {
      public List<ProductI18N> ProductsI18N { get; set; }    
      public Boolean IsApproved { get; set; }
    }

    public class ProductI18N {
        public String Name { get; set; }
        public String LanguageCode { get; set; }
    }

And to create the products:

        var productsI18N = new Faker<ProductI18N>()
          .RuleFor(x => x.LanguageCode, y => languages[y.IndexFaker % languages.Count])
          .RuleFor(x => x.Name, y => $"{y.Lorem.Word().ToFirstLetterUppercase()} {y.Hashids.Encode(y.IndexGlobal)}");

        List<Product> products = new Faker<Product>()
          .RuleFor(x => x.ProductsI18N, () => productsI18N.Generate(languages.Count).Cast<ProductI18N>().ToList())
          .RuleFor(x => x.IsApproved, x => x.Random.Bool())
          .Generate(2000).ToList();

        var count = products.SelectMany(x => x.ProductsI18N).Select(y => new { Name = y.Name, LanguageCode = y.LanguageCode }).Distinct().Count();

I figure out what is the problem. It is true that `y.IndexGlobal` gives unique values but `y.Hashids.Encode(y.IndexGlobal)` does not give unique values if you consider "abW" equals to "abw" which is what the database where I am inserting the values considers due to its collation ... 

When inserting a lot of products these collisions start to occur ... So again, would be nice to in the future integrate a way to set plugins default values. In case of HashIds would be to set the alphabet only with lowercase and numbers and this would be solved.
