### ISSUE TITLE
new Randomizer().Int() returns only int.MinValue and int.MinValue+1

### ISSUE THREAD

**Issue by praschl** [bchavez/Bogus#67]
The Method `Int()` of the `Randomizer` class returns only the values `int.MinValue` or `int.MinValue+1` when called without parameters, 
The default parameters suggest, that it should return any integer between `int.MinValue` and `int.MaxValue`.

**Comment by bchavez** [comment]
Hi @praschl ,

Thanks for reporting this bug. The issue is fixed in [`v12.0.1`](https://www.nuget.org/packages/Bogus/12.0.1).

Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by praschl** [comment]
Great, thanks!
