### ISSUE TITLE
Company Name appears twice in Readme

### ISSUE THREAD

**Issue by Alonski** [bchavez/Bogus#79]
CompanyName - Get a company name
CompanyName - Get a company name. The format can use any name.* and company.* methods.

I would fix this but I don't know which is correct.

**Comment by bchavez** [comment]
Ah. Nice catch m8.[ This code needs to change](https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/README_Generator.cs#L27-L83) to remove method overloads with parameters. or run distinct on the final set. I'll fix this later or you can send a PR.

:boom: :fire: ***["Set it ablaze like a candle wick... Light it up, light it up..."](https://www.youtube.com/watch?v=qDcFryDXQ7U)***
