### ISSUE TITLE
Random issue in currency code generation

### ISSUE THREAD

**Issue by eugene-nikolsky** [bchavez/Bogus#80]
Hi guys,

I've faced with an issue where statement like following would generate invalid currency code:
```
return new Faker<Money>()
    .RuleFor(o => o.Amount, f => f.Finance.Amount())
    .RuleFor(o => o.CurrencyCode, f => f.Finance.Currency().Code)
    .Generate();
```
Generated data:
```
{
  "amount": 247.64,
  "currencyCode": "CLP CLF" <-- two codes in one?
}
```
Issue appears randomly. Run the provided sample in for-loop and you'll catch it.

**Comment by bchavez** [comment]
Hi @eugene-nikolsky,

I think what you're seeing are currency fund codes.

Either way, Bogus should probably exclude currency fund pairs by default; and add a parameter if you want them.

Thanks for bringing this to my attention.

:violin: :palm_tree: ***["'Cause it's a bittersweet symphony, this life..."](https://www.youtube.com/watch?v=1lyu1KKwC74)***
