### ISSUE TITLE
Rules with boolean values not being applied.

### ISSUE THREAD

**Issue by NeilTruick** [bchavez/Bogus#82]
_As a JavaScript Faker user, thank you for the port to .NET!_

If I add a rule like:
`.RuleFor(d => d.IsDeleted, f => true)`
the property is not updated. Is this by design?

**Comment by bchavez** [comment]
Hi @NeilTruick ,

You're welcome! Thanks for using **Bogus**.

You'll have to provide more information as I'm not able to reproduce your issue via LINQPad. Seems to work here:

```
void Main()
{
    var barFaker = new Faker<Bar>()
        .RuleFor( b => b.IsDeleted, f => true);
    
    var bars = barFaker.Generate(10).ToList();
    
    bars.Dump();
    bars.All( b => b.IsDeleted).Should().BeTrue();
}

public class Bar
{
    public bool IsDeleted { get; set;} = false;
}
```
Output:
![linqpad_442](https://user-images.githubusercontent.com/478118/28888854-f8253fbc-7776-11e7-8111-c59fd39cc9ba.png)

If you can, please provide a failing test and I'll look into it more.

Thanks,
Brian

:sunny: :crescent_moon: ***["I've been counting down the days and the nights..."](https://www.youtube.com/watch?v=uMcYRk_o82M)***

**Comment by bchavez** [comment]
Hi @NeilTruick ,

If you have any more questions please feel free to reach out in our [gitter channel](https://gitter.im/bchavez/Bogus).

I'm going to close your issue for now (unless we can identify an issue with Bogus' source code). I'm a little OCD when it comes to keeping our GitHub issue count to a minimum. :smiley:

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***
