### ISSUE TITLE
Add "time since" fake

### ISSUE THREAD

**Issue by ricardovsilva** [bchavez/Bogus#85]
I need to get a string that call me how much time has passed since some event. My idea is:

```csharp
Console.Writeline(faker.Date.TimeSince());
//print something like 3 days and 12 hours ago
```

**Comment by bchavez** [comment]
Hi @ricardovsilva ,

Thanks for your recommendation, I appreciate it. Also thank you for using **Bogus**. :smiley: 

However, I'm not totally convinced yet adding `.TimeSince()` is a good idea. I think there are plenty of libraries that do this already via **C# Extension Methods**. Here are a few I'd recommend:

#### [`Humanizer`](https://www.nuget.org/packages/Humanizer/)
```
faker.Date.Recent().Humanize(dateToCompareAgainst: DateTime.Now).Dump();
// OUTPUT: 10 hours ago
```

#### [`MomentSharp`](https://www.nuget.org/packages/MomentSharp/)
```
faker.Date.Recent().Moment().From(DateTime.Now).Dump();
// OUTPUT: 10 hours ago
```
Overall, I'd rather not re-invent the wheel here. The less code I have to maintain the better and bug-free world we'll be in. :+1:  Not to mention, "3 days and 12 hours ago" is `us-en` **English**, what about **Korean**? **Spanish**? **Portuguese**? The problem could quickly escalate out of hand from a maintenance perspective.

So, I think other libraries like `Humanizer` already do a much better job at solving this problem.

Hope that helps. :crossed_fingers: 

Thanks,
Brian

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***
