### ISSUE TITLE
Invalid e-mail in pt_BR

### ISSUE THREAD

**Issue by priorbg** [bchavez/Bogus#86]
Hello,
I've got an error while I was trying to run my tests and populating an **randomic** email, as may see in the image example bellow, the e-mail got and invalid character(the letter "í").
![invalidemail](https://user-images.githubusercontent.com/11156392/29275192-ab389f96-80e0-11e7-8895-f7bd8d6e464b.png)

And also don't know if I'm implementing that right, what I'm in this code in C# to get the e-mail:

        public static string GetEmailAddress()
        {
            var random = new Bogus.DataSets.Internet(locale: "pt_BR");
            string _email = random.Email();
            return _email;
        }

**Comment by digitalcoyote** [comment]
This looks like it may be an issue with the DataSet for that  locale. Those come from Faker.js and will need to be fixed there.  According to https://github.com/bchavez/Bogus/wiki/Creating-Locales.

**Comment by priorbg** [comment]
Ok, I think I will just change the location, because the way that is being used for a first name it's a valid information, but to create an e-mail that becomes an invalid character :(

**Comment by bchavez** [comment]
Hi @priorbg,

I think characters with accents are legitimate email addresses. At the very least, Google's Gmail handles them: https://googleblog.blogspot.com.au/2014/08/a-first-step-toward-more-global-email.html

I'm not sure how widely adopted the RFC is but here is some more on the topic:
https://en.wikipedia.org/wiki/Email_address#Internationalization

This is one of the great things about **Bogus**: it makes us think about the edge cases that could occur in a production system at development time. To me, this is really cool and pretty neat.

Anyhow, perhaps we should add a helper/extension method that strips characters beyond `a-Z,0-9`; in addition to maybe a parameter on `.Email(someParam:true)` to ease the pain.

Not totally sure yet about what to do about it; but leaning on an extension method for `string`. ***maybe***.

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by JerryNixon** [comment]
Your email test is invalid.

**Comment by bchavez** [comment]
Hey @priorbg,

After giving this issue some thought I decided against adding an extension method to remove diacritical marks. The primary reason is maintainability. The codebase for **Bogus** is growing as we keep up with faker.js. Also, I think there are extension libraries that already do a good job solving issues like this. For example, [**Z.ExtensionMethods**](https://github.com/zzzprojects/Z.ExtensionMethods/blob/master/src/Z.Core/System.String/String.RemoveDiacritics.cs)' `.RemoveDiacritics()` extension method:

![linqpad_585](https://user-images.githubusercontent.com/478118/30395879-8ad2a91e-987c-11e7-8a1c-50eb8e8464c5.png)

IMHO, `Z.ExtensionMethods` complements **Bogus** very well. I hope this is a reasonable solution for your issue. I'll keep an open mind for future issues like this if it continues being a problem. We *could* see some helper extensions in the future that make **Bogus** easier to use. In that future, though, I'd be copying `Z.ExtensionMethods`' code anyway. :smile_cat:  

Thanks,
Brian

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by silvioboehme** [comment]
Hi!

I have the same problem in DE locales. There are many names with german "Umlauts" eg. (ÄÖÜ).
Bogus doesn't create a valid email in this case. But it tooks many hours to find this error, because it is complete random.

I would never expect that  .Internet.Email() creates a invalid email.
Also for german "Umlauts" the official translation is a Little bit different:
Ö -> OE
Ä -> AE
Ü -> UE

Maybe the creation of emails should be complete independant of the firstname / lastname dataset.

**Comment by bchavez** [comment]
Hey @silvioboehme ,

I think https://github.com/Marak/faker.js/commit/eac07f55bfe36fa9898ab4164f9da79311d54648 is an outdated commit. The current code for `faker.internet.email` is [a bit different](https://github.com/Marak/faker.js/blob/master/lib/internet.js#L31-L34).  Regardless though, you are correct,  at the end of the day `faker.js` does strip out diacritics using `faker.helpers.slugify`.

After some testing, it looks like the underlying implementation of **Regex** in .NET and JavaScript work differently when processing diacritical marks.

Specifically, JavaScript regex [`[^\w\.\-]+` in `faker.helpers.slugify`](https://github.com/Marak/faker.js/blob/master/lib/helpers.js#L26-L29) triggers on diacritcs and the same regex in .NET used by [`Bogus.Utils.Slugify`](https://github.com/bchavez/Bogus/blob/master/Source/Bogus/Utils.cs#L16-L20) ***does not*** trigger on diacritics.

I'll look into bringing **Bogus** inline with faker.js' behavior. I still think allowing Unicode in email address is the correct thing to do but this is probably one of those issues where it's better to go with the [*Internet flow*](https://en.wikipedia.org/wiki/HTTP_referer). :smile_cat:

:violin: :palm_tree: ***["'Cause it's a bittersweet symphony, this life..."](https://www.youtube.com/watch?v=1lyu1KKwC74)***

**Comment by bchavez** [comment]
Okay friends,

[**Bogus `v18.0.2`**](https://www.nuget.org/packages/Bogus/18.0.2) now removes diacritic mark/accents (á, í, ó, ú, etc) from generated email addresses and user names.

Happy generating!
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
