### ISSUE TITLE
Feature: Name.FullName(gender)

### ISSUE THREAD

**Issue by JerryNixon** [bchavez/Bogus#88]
No need to force the developer to use the more complex approach for RuleFor() overload or interpolation/concatenation. Clearly this method should take in gender, too.

**Comment by bchavez** [comment]
Hi @JerryNixon ,

`Name.FullName(Gender)` is now in **Bogus v15.0.7**. Should be available on **NuGet** within a few minutes after CI is done.

Thank you for your feedback!

-Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
