### ISSUE TITLE
Call .ToList() in .Generate(n)

### ISSUE THREAD

**Issue by bchavez** [bchavez/Bogus#91]
Requiring the user to call `.ToList()` right after `.Generate(n)` to escape **LINQ**town ([deferred execution](https://blogs.msdn.microsoft.com/charlie/2007/12/10/linq-and-deferred-execution/)) seems to be a major gotcha for new users. Two people have already encountred this issue: See #75.

TBH, there's probably no reason **Bogus** should keep its execution deferred; as LINQ's deferred execution can lead to different values when writing test assertions. `.Generate` should really mean `.Generate`. Additionally, currently, the singly `.Generate()` is not deferred, but `.Generate(n)` is deferred via LINQ. One could argue this as an inconsistent semantic mismatch.

This is a major breaking change API wise to `.Generate`; so it should go in a **v16** release. If we're going to break, we could also consider changing the return type to `List<T> Generate(n)` to more explicitly break existing code as a signal that the underlying behavior has changed fundamentally.

@napalm684 suggests using `.GenerateLazy` to keep existing behavior. I think we'll add `.GenerateLazy` later if there's demand for it. Additionally, `.GenerateLazy` can just as easily be implemented by using singly `.Generate` without major effort like we do now:
```
public virtual IEnumerable<T> Generate(int count, string ruleSets = null)
{
    return Enumerable.Range(1, count)
        .Select(i => Generate(ruleSets));
}
```

:fallen_leaf: :leaves: **[Distance - Falling (ft Alys Be)](https://www.youtube.com/watch?v=WIfwIv4wNCE)**

**Comment by napalm684** [comment]
Just curious when do you expect the latest nuget version to be available?

**Comment by bchavez** [comment]
Hi @napalm684 ,

Just tagged `master` with [`v16.0.1`, should be in the next few minutes after CI is done](https://www.nuget.org/packages/Bogus/16.0.1) and when NuGet finishes indexing it.

https://www.nuget.org/packages/Bogus/16.0.1

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
