### ISSUE TITLE
Make Faker<T>.Generate lazy

### ISSUE THREAD

**Issue by wojciechrak** [bchavez/Bogus#92]
Hello,

I see that Generate method returns IEnumerable<T> but internally calls `.ToList()`.
Is it necessary? I use Bogus to generate a lot of objects (hundreds of thousands) that I stream to file.
But calling `Generate(int count)` allocates a lot of memory since all objects have to be created.

If it's not needed, then avoid calling `ToList()`.
If it is indeed requried, consider changing returning type to IList<> or ICollection<>, since IEnumerable<> suggests that elements will be lazily evaluated.

**Comment by bchavez** [comment]
Hi @wojciechrak ,

If we added `.GenerateLazy` would that be okay?

**Comment by wojciechrak** [comment]
For my use-case, sure 👍

**Comment by bchavez** [comment]
Hi @wojciechrak ,

[**Bogus** `v16.0.2`](https://www.nuget.org/packages/Bogus/16.0.2) (now available on NuGet) should contain the new `.GenerateLazy` method that keeps the old behavior.

Thank you for your feedback, I really appreciate it.

For reference: This was related to #91.

Thanks,
Brian

:zap: :runner: ***["I was struck by lighting. Walkin' down the street..."](https://www.youtube.com/watch?v=iypUpv9xelg)***
