### ISSUE TITLE
> 15.0.3 breaking change with PickRandom

### ISSUE THREAD

**Issue by maldworth** [bchavez/Bogus#93]
Great library, but I was recently updating past 15.0.3, and it broke a whole bunch of my unit tests.

Right now I have:

```csharp
var items = new List<MyObj>{ ... };

var getOne = Faker.PickRandom(items);
```

however any update past 15.0.3, I now have to go through all my unit tests and update to

```csharp
var items = new List<MyObj>{...};

var getOne = Faker.PickRandom(items.AsEnumerable());
```

It looks like an overload was added for params[], and it now thinks that I'm passing in a bunch of (params List<MyObj>[] ...) and returning me back one list, rather than one item from the list.

Any chance we can revert this back to what it was before?

**Comment by bchavez** [comment]
Hi @maldworth ,

Ouch, that's a nasty one.

I should have had a test to cover this. My apologies I'll get this fixed soon.

:cloud: :sunny: **[Bassnectar - Chasing Heaven - Into the Sun](https://www.youtube.com/watch?v=a2BAia075lE)**

**Comment by bchavez** [comment]
Hey @maldworth ,

[**Bogus** `v16.0.2`](https://www.nuget.org/packages/Bogus/16.0.2) (now available on NuGet) should contain the `PickRandom` overload fix that keeps the old behavior. Originally, that's what I had intended but I goofed with this commit https://github.com/bchavez/Bogus/commit/d91ba3bbdeb17f699241a92c707205b3257090be. Also added a test to protect against this in the future.

Also, as a quick reminder, with v16, there is a functional change in `.Generate` where we automatically call `.ToList` under the covers now (ref: #91). If you want the old behavior with deferred LINQ execution `.GenerateLazy` is available.

So, give [**Bogus** `v16.0.2`](https://www.nuget.org/packages/Bogus/16.0.2) a try and let me know if that fixes your issue. Also, feel free to re-open the issue if it's still a problem.

Thank you for your feedback, I really appreciate it.

-Brian

:car: :police_car: :rotating_light: ***["Drive it like you stole it..."](https://www.youtube.com/watch?v=dd00Qh9yZUg)***

**Comment by maldworth** [comment]
Yep works. Thanks for the fast fix!

**Comment by napalm684** [comment]
FYI this used to work for me and apparently is broken now.  I assume from this change?

```
.RuleFor(d => d.DocumentTypeId, f => f.PickRandom(1, 2, 3))
```

**Comment by bchavez** [comment]
Hi @napalm684,

Try `f.PickRandomParam(1, 2, 3)` instead. Yes, in v16, it was due to this change.

Essentially, the compiler was picking `f.PickRandom(params T[])` overload when using `List<T>` as a parameter instead of `f.PickRandom(IEnumerable<T>)`. So, I had to rename it to avoid the conflict.

Perhaps if I explicitly add some new additional overloads: `PickRandom(IList)` and `PicikRandom(List[T])` maybe we can get the compiler to pick the right one.

Let me investigate a bit more.

:fire: :volcano: ***["We're building it up, to break it back down..."](https://www.youtube.com/watch?v=dxytyRy-O1k)***

**Comment by bchavez** [comment]
Okay, worked on this a little more, I think we can get away with `PickRandom(1,2,3)` and still have the compiler pick the right one. Give [**Bogus** `v16.0.3`](https://www.nuget.org/packages/Bogus/16.0.3) a try and let me know.

Thanks again for the feedback. I appreciate it.

Thanks,
Brian


:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by napalm684** [comment]
Working for me as expected thanks again!
