### ISSUE TITLE
ArgumentException when using Faker<T> with locale not "en"

### ISSUE THREAD

**Issue by joopscheer** [bchavez/Bogus#99]
Version: **19.0.1**

When multiple tests use Faker<T> with a different locale then "en" an ArgumentException occurs.

Message:
`System.ArgumentException : An item with the same key has already been added. Key: nl`

Stacktrace:
```
at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Bogus.Database.GetLocale(String locale)
at Bogus.Database.HasKey(String category, String path, String locale, String fallbackLocale)
at Bogus.DataSets.Name..ctor(String locale)
at Bogus.Faker..ctor(String locale)
at Bogus.Faker`1..ctor(String locale, IBinder binder)
```

**Comment by bchavez** [comment]
Can you post up some sample faker code that exhibits the error? Are you using Xunit for these tests?

Having a hunch this is a threading issue. I think the locale dictionary (a recent change I made) might not be thread-safe.

**Comment by bchavez** [comment]
@joopscheer , just pushed a possible fix for your issue.

Build status: https://ci.appveyor.com/project/bchavez/bogus/build/384

It will get published on NuGet after everything is built and tested. So look for **v19.0.2** on NuGet within the next 15 minutes or so.

Please close the issue if it the new version resolves your issue.

I have to get some sleep now. Thanks.

:running: :sunrise_over_mountains: ***[And I ran. I ran so far away. I just ran. I ran all night and day. I couldn't get away...](https://www.youtube.com/watch?v=0_Pq0xYr3L4)***

**Comment by leticiagoes** [comment]
I had the same problem right, I just got the update from the version 19.0.2 and it worked for me with another locale.
Great job!
Thanks a lot.

**Comment by joopscheer** [comment]
Nice work @bchavez! The updated version works. Thanks again.
